bcgov/sbc-pay

jenkins/ZAP-Jenkinsfile
=> initial projects

jenkins/ZAP-Jenkinsfile
=> initial project

pay-api/Jenkinsfile, pay-api/tests/postman/pay-api.postman_collection.json
=> add pytest and postman test pipeline in Jenkins

pay-ui/Jenkinsfile
=> add display exception detail of each stage

jenkins/deploy-to-prod-Jenkinsfile, jenkins/deploy-to-test-Jenkinsfile, pay-api/Jenkinsfile, pay-ui/Jenkinsfile
=> fix jenkinsfile issues

pay-ui/Jenkinsfile
=> update ui pipeline

docs/docs/PayBC Mocking/paybc-1.0.0.yaml
Signed-off-by: IDIR\schen <steven.chen@gov.bc.ca>
=> Added PayBC mocking file for issue#: 406

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/task-or-ops.md, .github/PULL_REQUEST_TEMPLATE.md, pay-api/Jenkinsfile, pay-api/migrations/README, pay-api/migrations/alembic.ini, pay-api/migrations/env.py, pay-api/migrations/script.py.mako
*Issue #:*
- #### Common
- #### REST 
=> Add migrations folder

docs/docs/PayBC Mocking/paybc-1.0.0.yaml, pay-api/src/pay-api/model/__init__.py, pay-api/src/pay-api/model/db.py, pay-api/src/pay-api/model/fee.py
Signed-off-by: IDIR\schen <steven.chen@gov.bc.ca>
*Issue #:*
- #### Common
- #### REST 
=> 406-PayBC Mocking

pay-api/migrations/versions/c56d857d7282_add_dummy_table.py
*Issue #:*
- #### Common
- #### REST 
=> add a dummy table

jenkins/Sonarqube-Jenkinsfile.pipeline.param, jenkins/ZAP-Jenkinsfile.pipeline.param, jenkins/deploy-to-test-Jenkinsfile.pipeline.param, openshift/settings.sh, pay-ui/Jenkinsfile.pipeline.param, pay-ui/openshift/templates/pay-ui-build.json
*Issue #:*
- #### Common
- #### REST 
=> update pipeline config

docs/docs/api_contract/pay-api-1.0.0.yaml
*Issue #:*
#498 : Draft version of Pay API contract
=> 498   pay api contract

.gitignore, pay-api/requirements.txt, pay-api/requirements/prod.txt, pay-api/setup.py, pay-api/src/pay_api/__init__.py, pay-api/src/pay_api/models/__init__.py, pay-api/src/pay_api/resources/fee.py, pay-api/src/pay_api/resources/invoice.py, pay-api/src/pay_api/resources/pay.py, pay-api/src/pay_api/services/fee_schedule.py
*Issue #:*
https://github.com/bcgov/entity/issues/537
- #### Common
- #### REST 
=> enbale tracing for endpoint, service and db model.

pay-api/requirements.txt, pay-api/setup.py
*Issue #:*
- #### Common
- #### REST 
=> 537 tracing

pay-api/src/pay_api/__init__.py
*Issue #:*
- #### Common
- #### REST 
=> Fixed the tracer name

pay-api/src/pay_api/__init__.py
*Issue #:*
- #### Common
- #### REST 
=> Merge to master( test PR)

pay-api/src/pay_api/services/paybc.py
*Issue #:*
PayBC needs transaction number now
- #### Common
- #### REST 
=> Added random number

pay-api/src/pay_api/services/paybc.py
*Issue #:*
- #### Common
- #### REST 
=> adjustment error fixed

pay-api/src/pay_api/resources/transaction.py, pay-api/src/pay_api/services/payment_transaction.py, pay-api/src/pay_api/utils/util.py
*Issue #:*
https://github.com/bcgov/entity/issues/602
Fixing issue with CORS headers for transactions endpoint
- #### Common
- #### REST 
=> Fixing issue with CORS for transactions endpoint

docs/docs/PayBC Mocking/paybc-1.0.0.yaml
Signed-off-by: IDIR\schen <steven.chen@gov.bc.ca>
*Issue #:*
- #### Common
- #### REST 
=> 596 - Mocked test cases for PayBC

pay-api/src/pay_api/resources/invoice_receipt.py, pay-api/src/pay_api/services/receipt.py, pay-api/tests/postman/pay-api.postman_collection.json, pay-api/tests/unit/api/test_receipt.py, pay-api/tests/unit/services/test_receipt.py, report-api/tests/postman/pdf-create.postman_collection.json
Added few logs to check the timing of pdf
corrected few postman test cases
*Issue #:*
Added business exception if there are no receipts
Added few logs to check the timing of pdf
corrected few postman test cases
- #### Common
- #### REST 
=> Added business exception if there are no receipts

.gitignore, jenkins/pull-request-review-Jenkinsfile, openshift/dockerfile-jenkins-slave-python3-nodejs10, pay-api/setup.cfg, report-api/setup.cfg
*Issue #:*
- #### Common
- #### REST 
=> Setup pull request review pipeline for pay-api and report-api

pay-api/openshift/templates/pay-api-pre-deploy.json, report-api/jenkins/dev.groovy, report-api/openshift/templates/report-api-pipeline.json
*Issue #:*
- #### Common
- #### REST 
=> Fixed some configuration of template and pipeline.

pay-api/openshift/templates/pay-api-deploy.json, pay-api/openshift/templates/pay-api-pre-deploy.json, pay-api/requirements/dev.txt, report-api/requirements/dev.txt
*Issue #:*
- #### Common
- #### REST 
=> Replace env setting in deploy template

pay-api/openshift/templates/pay-api-deploy.json, pay-api/openshift/templates/pay-api-pre-deploy.json, pay-api/tests/unit/api/test_meta.py, pay-api/tests/utilities/decorators.py, report-api/openshift/templates/report-api-deploy.json, report-api/openshift/templates/report-api-pre-deploy.json, report-api/tests/__init__.py, report-api/tests/unit/api/test_meta.py, report-api/tests/utilities/decorators.py
*Issue #:*
- #### Common
- #### REST 
=>  Fixed pytest pipeline issue.

pay-api/tests/utilities/decorators.py
*Issue #:*
- #### Common
- #### REST 
=> Fixed a typo.

pay-api/tests/unit/conf/test_version.py, report-api/tests/unit/conf/test_version.py
*Issue #:*
- #### Common
- #### REST 
=> Skip test_version unit test during pytest run inside the pod.

pay-api/src/pay_api/services/receipt.py, pay-api/tests/unit/api/test_transaction.py, pay-api/tests/unit/conf/test_version.py, pay-api/tests/unit/services/test_payment_transaction.py, pay-api/tests/unit/services/test_queue_publisher.py, pay-api/tests/utilities/decorators.py
*Issue #:*
- #### Common
- #### REST 
=> Skipping the tests which needs docker in POD

pay-api/jenkins/dev.groovy, pay-api/requirements.txt, report-api/jenkins/dev.groovy
*Issue #:*
- #### Common
- #### REST 
=> Update the pytest pipeline parameter

pay-api/openshift/templates/pay-api-deploy.json, pay-api/openshift/templates/pay-api-pre-deploy.json, pay-api/src/pay_api/resources/status.py, pay-api/tests/conftest.py, pay-api/tests/postman/pay-api.postman_collection.json, pay-api/tests/unit/api/test_status.py, pay-api/tests/unit/api/test_transaction.py, pay-api/tests/unit/conf/test_version.py, pay-api/tests/unit/factory/test_payment_system_factory.py, pay-api/tests/unit/services/test_payment_transaction.py, pay-api/tests/unit/services/test_queue_publisher.py, report-api/openshift/templates/report-api-deploy.json
*Issue #:*
- #### Common
- #### REST 
=> Add a postman test for downtime status endpoint and clean up the code

pay-api/tests/postman/pay-api-dev.environment.json, pay-api/tests/postman/pay-api.postman_collection.json
*Issue #:*
Updating postman collection
Updating postman collection
=> Updating postman collection

jobs/update-stale-payment/config.py, jobs/update-stale-payment/openshift/cron-update-stale-payment.yaml, pay-api/config.py, pay-api/openshift/templates/pay-api-deploy.json, pay-api/openshift/templates/pay-api-pre-deploy.json, pay-api/src/pay_api/exceptions/__init__.py, pay-api/src/pay_api/resources/__init__.py, pay-api/src/pay_api/resources/payment.py, pay-api/src/pay_api/services/oauth_service.py, pay-api/src/pay_api/services/payment_transaction.py, pay-api/src/pay_api/utils/errors.py, pay-api/tests/conftest.py, pay-api/tests/unit/api/test_payment.py, pay-api/tests/unit/api/test_transaction.py, pay-api/tests/unit/services/test_oauth_service.py, pay-api/tests/unit/services/test_payment_service.py, pay-api/tests/unit/services/test_payment_transaction.py
*Issue #:*
https://github.com/bcgov/entity/issues/1016
- Changes to the transaction and payment endpoints to handle PayBC downtime
- #### Common
- #### REST 
=> #1016 : Handle PayBC error when it's down

pay-api/src/pay_api/services/queue_publisher.py
*Issue #:*
Changing the payment queue integration from nats to stan
=> Changing the payment queue integration

pay-api/openshift/templates/pay-api-deploy.e2e.json, pay-api/src/pay_api/jwt_wrapper.py, pay-api/src/pay_api/resources/__init__.py, pay-api/src/pay_api/resources/apihelper.py, pay-api/src/pay_api/services/status_service.py, pay-api/src/pay_api/utils/auth.py, pay-api/tests/unit/services/test_status_service.py
*Issue #:*
- #### Common
- #### REST 
=> Modify status service.

pay-api/src/pay_api/resources/status.py
*Issue #:*
- #### Common
- #### REST 
=> Fixed utc time cache issue happened in openshift.

report-api/report-templates/payment_receipt_coops.html
*Issue #:*
Changing the style of report templates
Changing the style of report templates
=> Changing the style of report templates

pay-api/requirements.txt, pay-api/requirements/repo-libraries.txt, pay-api/src/pay_api/__init__.py, pay-api/src/pay_api/factory/payment_system_factory.py, pay-api/src/pay_api/resources/__init__.py, pay-api/src/pay_api/resources/status.py, pay-api/src/pay_api/services/status_service.py, pay-api/src/pay_api/utils/auth.py, pay-api/tests/unit/services/test_status_service.py, report-api/requirements.txt, report-api/requirements/editable.txt, report-api/src/api/__init__.py, report-api/src/api/resources/__init__.py
*Issue #:* [#1034](https://github.com/bcgov/entity/issues/1034)
Add global exception handling to handle common exceptions:
AuthError
HttpException
SQLAlchemyError
default_exceptions from werkzeug.exceptions library
- #### Common
- #### REST 
=> Add global exception handling and clean up the code.

jobs/update-stale-payment/openshift/cron-update-stale-payment.yaml, pay-api/openshift/templates/pay-api-deploy.e2e.json, pay-api/openshift/templates/pay-api-deploy.json, pay-api/openshift/templates/pay-api-pre-deploy.json
*Issue #:*
#96 
- Updating deploy configs with AUTH_API_ENDPOINT variable
=> Updating deploy configs with new environment variable

pay-api/src/pay_api/services/oauth_service.py, pay-api/src/pay_api/services/paybc_service.py
*Issue #:*
PROD Fix to limit the account description to 30 characters
PROD Fix to limit the account description to 30 characters
=> PROD Fix to limit the account description to 30 characters

report-api/src/api/services/report_service.py, report-api/src/api/utils/constants.py
Jinja set to autoescape true
*Issue #:*
https://github.com/bcgov/entity/issues/1435
Jinja autoescape set to true
- #### Common
- #### REST 
=> fix for https://github.com/bcgov/entity/issues/1435 

report-api/src/api/services/report_service.py, report-api/src/api/utils/constants.py, report-api/tests/postman/pdf-create.postman_collection.json
*Issue #:*
https://github.com/bcgov/entity/issues/1435
Jinja auto escape set to True
Added oauth2 token for report generation
- #### Common
- #### REST 
=> fixes for bandit reported vulnerability

report-api/src/api/services/report_service.py
*Issue #:*
- #### Common
- #### REST 
=> removed unused variable

pay-api/src/pay_api/resources/transaction.py, pay-api/src/pay_api/schemas/schemas/transaction_request.json, pay-api/src/pay_api/services/payment_service.py, pay-api/src/pay_api/services/payment_transaction.py, pay-api/src/pay_api/services/receipt.py, pay-api/tests/unit/api/test_receipt.py, pay-api/tests/unit/api/test_transaction.py, pay-api/tests/unit/services/test_payment_service.py, pay-api/tests/unit/services/test_payment_transaction.py
*Issue #:*
https://github.com/bcgov/entity/issues/1585
- Changes for POST transaction to accept URLs in body
PS: I will create a new PR for postman collection changes
*Checklist:*
=> Changes for POST transaction to accept URLs in body

pay-api/migrations/versions/e6eb14b9d50e_fee_master_for_bcorps.py
*Issue #:*
https://github.com/bcgov/entity/issues/1609
- Adding BCORP Fee master data
*Checklist:*
=> Adding BCorp fee master data

pay-api/src/pay_api/services/internal_pay_service.py, pay-api/src/pay_api/services/receipt.py, pay-api/tests/unit/api/test_receipt.py, report-api/report-templates/payment_receipt_coops.html, report-api/src/api/utils/constants.py
*Issue #:*
https://github.com/bcgov/entity/issues/1690
- Changes to receipt for adding routing slip number
*Checklist:*
=> Staff Receipt Changes

pay-api/src/pay_api/factory/payment_system_factory.py
*Issue #:*
https://github.com/bcgov/entity/issues/1806
- Fixing issue with payment requests for BCORP
*Checklist:*
=> 1806: Fixing issue with payment requests for BCORP

jobs/update-stale-payment/update_stale_payment_records.py
=> Fixing job to reflect change in service in pay-api

pay-api/src/pay_api/utils/user_context.py
=> Adding null check in user context for the job

pay-api/requirements.txt, pay-api/src/pay_api/__init__.py, pay-api/src/pay_api/jwt_wrapper.py, pay-api/src/pay_api/models/payment_transaction.py, pay-api/src/pay_api/resources/payment.py, pay-api/src/pay_api/services/auth.py, pay-api/src/pay_api/services/bcol_service.py, pay-api/src/pay_api/services/invoice_reference.py, pay-api/src/pay_api/services/payment_service.py, pay-api/src/pay_api/services/payment_transaction.py, pay-api/tests/unit/factory/test_payment_system_factory.py, pay-api/tests/unit/models/test_payment.py, pay-api/tests/unit/services/test_fee_schedule.py, pay-api/tests/unit/services/test_invoice.py, pay-api/tests/unit/services/test_invoice_reference.py, pay-api/tests/unit/services/test_payment_line_item.py, pay-api/tests/unit/services/test_payment_service.py, pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/2280
- Fixing queue message issue
- Improving code coverage
*Checklist:*
=> Pay-API Fix to not send wrong message to queue

docs/docs/api_contract/report-api-1.0.0.yaml, pay-api/openshift/templates/pay-api-deploy.e2e.json
*Issue #:*
https://github.com/bcgov/entity/issues/1500
*Checklist:*
=> Add api contract for report API and fixed a name issue on e2e template.

pay-api/src/pay_api/services/paybc_service.py, pay-api/src/pay_api/services/payment_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/2322
- Adding async delete payment on delete payment-request
- If it fails, job will pick it up.
*Checklist:*
=> Adding async delete payment on delete payment-request

pay-api/migrations/versions/5cdd1c1d355e_correction_fee_codes.py, pay-api/src/pay_api/services/fee_schedule.py
*Issue #:*
https://github.com/bcgov/entity/issues/2658
- Adding correction fee codes 
*Checklist:*
=> Fee code for correction

pay-api/migrations/versions/7a86a5703e27_priority_fee_for_all.py
*Issue #:*
https://github.com/bcgov/entity/issues/2804
-Adding priority fees for all non-zero filing type codes
*Checklist:*
=> 2804: Adding priority fees for all non-zero filing type codes

.github/workflows/check-master.yml, .github/workflows/pay-api-check.yml, .github/workflows/pay-api-dev.yml, .github/workflows/pay-api-test.yml, .sonarcloud.properties, scripts/1pass_dc.sh, scripts/1pass_secret.sh
=> Add Github Actions.

pay-api/README.md
=> Test Github Actions.

.github/workflows/pay-api-dev.yml, .github/workflows/pay-api-test.yml, pay-api/config.py, pay-api/jenkins/dev.groovy, pay-api/openshift/templates/dc.json
=> Clean up the code.

.github/workflows/pay-api-test.yml
=> Fixed the push step

pay-api/README.md
=> Trigger deployment.

pay-api/README.md
=> Test trigger test deployment.

.github/workflows/pay-api-dev.yml, .github/workflows/pay-api-test.yml
=> Change to github workflow

pay-api/src/pay_api/schemas/schemas/business_info.json
=> Adding BC in schema

pay-api/migrations/versions/4cc39da0bee7_payment_system_account.py
=> Adding catch and message for migration if the affiliation doesn't exist

pay-api/src/pay_api/utils/user_context.py
=> User Context fall back username to preferred_username

.github/workflows/bcol-api-dev.yml, .github/workflows/bcol-api-test.yml, .github/workflows/pay-api-dev.yml, .github/workflows/pay-api-test.yml, .github/workflows/report-api-dev.yml, .github/workflows/report-api-test.yml, bcol-api/README.md, scripts/install_tools.sh
=> Update github actions scripts.

docs/docs/PayBC Mocking/paybc-1.0.0.yaml, docs/docs/api_contract/bcol-api-1.0.0.yaml, docs/docs/api_contract/pay-api-1.0.0.yaml
*Issue #:*
- Contract changes
*Checklist:*
=> Contract changes

.github/workflows/pay-api-check.yml, pay-api/config.py, pay-api/tests/docker/docker-compose.yml, pay-api/tests/docker/nginx.conf, pay-api/tests/unit/api/test_fee.py, pay-api/tests/utilities/base_test.py
*Issue #:*
- Changes to run the pytest with local keycloak
*Checklist:*
=> Changes to run the pytest with local keycloak

pay-api/src/pay_api/services/auth.py
*Issue #:*
https://github.com/bcgov/entity/issues/3075
- 3075: Handle account if the entity is not affiliated for staff payments
*Checklist:*
=> 3075: Handle account if the entity is not affiliated for staff payments

bcol-api/requirements.txt, bcol-api/src/bcol_api/__init__.py, bcol-api/src/bcol_api/exceptions/__init__.py, bcol-api/src/bcol_api/services/bcol_payment.py, bcol-api/tests/utilities/base_test.py, pay-api/requirements.txt, pay-api/src/pay_api/exceptions/__init__.py, pay-api/src/pay_api/resources/fee.py, pay-api/src/pay_api/resources/invoice.py, pay-api/src/pay_api/resources/invoice_receipt.py, pay-api/src/pay_api/resources/payment.py, pay-api/src/pay_api/resources/transaction.py, pay-api/src/pay_api/schemas/schemas/problem.json, pay-api/src/pay_api/services/bcol_service.py, pay-api/src/pay_api/services/internal_pay_service.py, pay-api/src/pay_api/services/oauth_service.py, pay-api/src/pay_api/services/payment_transaction.py, pay-api/src/pay_api/services/receipt.py, pay-api/src/pay_api/utils/errors.py, pay-api/tests/unit/api/test_payment.py, pay-api/tests/unit/api/test_receipt.py, pay-api/tests/unit/utils/test_error.py
*Issue #:*
https://github.com/bcgov/entity/issues/2892
- Changes for handling BC Online errors
- Changes to return application/problem+json response for errors
*Checklist:*
=> Changes for BCOL error handling

.github/workflows/bcol-api-check.yml, .github/workflows/bcol-api-test.yml, .github/workflows/check-master.yml, .github/workflows/pay-api-check.yml, .github/workflows/report-api-check.yml
=> Enable python 3.8 checks.

pay-api/src/pay_api/services/auth.py
*Issue #:*
Adding auth changes to handle cases where the action is not product based
*Checklist:*
=> Adding auth changes to handle cases where the action is not product based

pay-api/src/pay_api/__init__.py
*Issue #:*
Commenting out buildCache as it's causing issue with alembic migration
*Checklist:*
=> Commenting out buildCache as it's causing issue with alembic migration

pay-api/src/pay_api/__init__.py
*Issue #:*
-Adding the cache back with try except
*Checklist:*
=> Adding the cache back with try except

bcol-api/src/bcol_api/resources/bcol_payment.py, bcol-api/src/bcol_api/resources/bcol_profile.py
*Issue #:*
Adding cors for bcol endpoints
*Checklist:*
=> Adding cors for bcol endpoints

bcol-api/requirements.txt, bcol-api/src/bcol_api/exceptions/__init__.py, bcol-api/src/bcol_api/resources/bcol_payment.py, bcol-api/src/bcol_api/resources/bcol_profile.py, bcol-api/src/bcol_api/services/bcol_payment.py, bcol-api/src/bcol_api/services/bcol_profile.py, bcol-api/src/bcol_api/utils/errors.py, bcol-api/tests/conftest.py, bcol-api/tests/unit/api/test_bcol_profile.py
*Issue #:*
https://github.com/bcgov/entity/issues/3371
- Handling error for BCOL Profile lookup
- Error types : `INVALID_CREDENTIALS, NOT_A_PRIME_USER, SYSTEM_ERROR`
*Checklist:*
=> Changes for handling BCOL errors

.github/workflows/bcol-api-dev.yml, .github/workflows/bcol-api-test.yml, .github/workflows/check-master.yml, .github/workflows/pay-api-dev.yml, .github/workflows/pay-api-test.yml, .github/workflows/report-api-dev.yml, .github/workflows/report-api-test.yml
Only failure deployment will notify the channel.
*Checklist:*
=> Change gh actions RC rules.

pay-api/src/pay_api/services/payment.py
=> Fixing issue with pdf download of payment txns

.github/workflows/report-api-test.yml, report-api/README.md
=> Fixed push image issue.

.github/workflows/report-api-test.yml, pay-api/src/pay_api/services/payment.py, report-api/README.md
=> Fixed github actions issue.

pay-api/migrations/versions/f50d7a538b8f_changing_error_messages.py
*Issue #:*
https://github.com/bcgov/entity/issues/3543
- Changing the error description for the BCOL errors
*Checklist:*
=> 3543: Changes to error details for BCOL

pay-api/src/pay_api/services/receipt.py
*Issue #:*
Fixing issue with BCOL Account number in receipt
*Checklist:*
=> Fixing issue with BCOL Account number in receipt

report-api/report-templates/payment_receipt.html
=> footer alignment possible fix

report-api/report-templates/payment_receipt.html
=> alignment possible fix

report-api/report-templates/payment_receipt.html
=> footer alignment fix

bcol-api/src/bcol_api/exceptions/__init__.py, bcol-api/src/bcol_api/resources/bcol_payment.py, bcol-api/src/bcol_api/resources/bcol_profile.py, bcol-api/src/bcol_api/services/bcol_profile.py
*Issue #:*
Bcol profile fix to return error codes from BC Online
*Checklist:*
=> Bcol profile fix

pay-api/src/pay_api/services/bcol_service.py
=> Fixing issue with bcol error handling

bcol-api/src/bcol_api/services/bcol_profile.py
=> Fixing a small issue with strip of text

bcol-api/src/bcol_api/services/bcol_profile.py, pay-api/src/pay_api/services/bcol_service.py
=> Merging from dev to master

pay-api/src/pay_api/services/receipt.py, report-api/report-templates/payment_receipt.html
=> Fixing issue with priority fees not showing in receipt

report-api/report-templates/payment_receipt.html
=> Fixing issue with filing fees not showing in receipt for zero fees

pay-api/migrations/versions/a23093f25c56_add_status_codes.py
=> Fixing issue with invoice reference status migration

pay-api/migrations/versions/06f6e75c18d8_vital_statistics_fee_code.py, pay-api/src/pay_api/services/fee_schedule.py
*Issue #:*
https://github.com/bcgov/entity/issues/3251
- Adding vital statistics fee code
- Adding transaction fee will be done as separate ticket
*Checklist:*
=> Vital statistics fee code

.github/workflows/bcol-api-check.yml, .github/workflows/pay-api-check.yml, .github/workflows/report-api-check.yml, README.md, bcol-api/README.md, bcol-api/requirements.txt, bcol-api/setup.cfg, codecov.yaml, pay-api/README.md, pay-api/requirements.txt, pay-api/setup.cfg, report-api/README.md, report-api/requirements.txt, report-api/setup.cfg
=> Codecov support.

jobs/update-stale-payment/requirements/prod.txt
=> Fixing version in update stale payment job

pay-api/src/pay_api/services/fee_schedule.py, pay-api/tests/unit/services/test_fee_schedule.py
*Issue #:*
- Adding processing fees back to fix issue with fee summary
*Checklist:*
=> Adding processing fees back to fix issue with fee summary

pay-api/src/pay_api/resources/fee.py, pay-api/src/pay_api/services/fee_schedule.py, pay-api/src/pay_api/utils/util.py
*Issue #:*
- Adding Account-Id to allowed headers
*Checklist:*
=> Fee summary fix

pay-api/config.py, pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/services/payment.py, pay-api/tests/unit/api/test_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/3877
- Adding default list of transactions in queries
*Checklist:*
=> 3877 : Adding default list of transactions in queries

pay-api/src/pay_api/schemas/schemas/purchase_history_request.json
*Issue #:*
- Removing startDate and endDate mandatory check for default load
*Checklist:*
=> Removing startDate and endDate mandatory check for default load

pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/services/payment.py
*Issue #:*
-Fixing issue with default csv export
*Checklist:*
=> Fixing issue with default csv export

pay-api/src/pay_api/resources/account.py, pay-api/src/pay_api/services/auth.py, pay-api/src/pay_api/utils/util.py
…ing auth to allow only premium accounts to transactions
*Issue #:*
- fixing issue with None as string being populated in folio number
- adding auth to allow only premium accounts to transactions
*Checklist:*
=> Fixing issue with None as string being populated in folio number

bcol-api/src/bcol_api/schemas/schemas/payment_request.json, bcol-api/src/bcol_api/services/bcol_payment.py, pay-api/src/pay_api/services/bcol_service.py
=> Bcol remove folio as mandatory

pay-api/src/pay_api/services/bcol_service.py
=> Fixing lint error

pay-api/README.md
=> Fire up /business path change deployment.

pay-api/migrations/versions/e8edc889072d_nr_fee_codes.py
*Issue #:*
https://github.com/bcgov/entity/issues/1986
- Adding fee codes for Names Request Online
*Checklist:*
=> Adding NR Fee Code

report-api/report-templates/payment_receipt.html
*Issue #:*
https://github.com/bcgov/entity/issues/4042
- Fix for showing future effective fees.
*Checklist:*
=> 4042: Fix for showing future effective fees.

jobs/update-stale-payment/openshift/cron-update-stale-payment.yaml, jobs/update-stale-payment/requirements/prod.txt
=> Fixed job requirement issue.

.github/workflows/draft-release.yml, .github/workflows/main-pr-check.yml, .github/workflows/pr-label-check.yml, jobs/update-stale-payment/openshift/cron-update-stale-payment.yaml
*Issue #:*
1. Move pr label check to development branch.
2. Fix some typo issues.
*Checklist:*
=> Move pr label check to development branch.

bcol-api/src/bcol_api/resources/bcol_payment.py, bcol-api/src/bcol_api/services/bcol_payment.py, bcol-api/src/bcol_api/utils/constants.py, pay-api/config.py, pay-api/migrations/versions/7ea7ba8fe991_alteration_filing.py, pay-api/src/pay_api/factory/payment_system_factory.py, pay-api/src/pay_api/models/bcol_payment_account.py, pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/services/bcol_service.py, pay-api/src/pay_api/services/internal_pay_service.py, pay-api/src/pay_api/services/paybc_service.py, pay-api/src/pay_api/services/payment.py, pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/services/payment_service.py, pay-api/src/pay_api/utils/enums.py, pay-api/src/pay_api/utils/user_context.py, pay-api/tests/conftest.py, pay-api/tests/unit/api/test_payment.py, pay-api/tests/unit/factory/test_payment_system_factory.py, pay-api/tests/unit/services/test_payment_service.py, pay-api/tests/unit/services/test_payment_system_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/4482
- Changes for adding new filing type code for Notice Of Alteration
- Changes on BCOL API and Pay-API to support BCOL payments using service accounts
*Checklist:*
=> Changes for supporting BCOL payments using service account.

pay-api/src/pay_api/models/invoice.py, pay-api/src/pay_api/resources/invoice_receipt.py, pay-api/src/pay_api/services/oauth_service.py, pay-api/src/pay_api/services/receipt.py, pay-api/tests/unit/api/test_receipt.py, report-api/report-templates/payment_receipt.html
*Issue #:*
https://github.com/bcgov/entity/issues/4358
- Changes for receipt to accommodate Names
*Checklist:*
=> Changes for receipt to accommodate Names

pay-api/config.py, pay-api/src/pay_api/schemas/schemas/payment_info.json, pay-api/src/pay_api/services/__init__.py, pay-api/src/pay_api/services/direct_pay_service.py, pay-api/src/pay_api/services/hashing.py, pay-api/tests/unit/api/test_transaction.py, pay-api/tests/unit/services/test_hashing_service.py, pay-api/tests/unit/services/test_payment_transaction.py
*Issue #:*
https://github.com/bcgov/entity/issues/4242
- changes mainly for url parameters for paybc direct feature
_I added some TODO across the code where i am not sure if its right.Please have a look at them_
*Checklist:*
=> changes for paybc direct payment url

pay-api/config.py, pay-api/src/pay_api/services/auth.py, pay-api/src/pay_api/services/bcol_service.py, pay-api/src/pay_api/utils/user_context.py
*Issue #:*
- Patch Fix to pull the account details for BUSINESS system accounts
*Checklist:*
=> Patch Fix to pull the account details for BUSINESS system accounts

pay-api/src/pay_api/services/direct_pay_service.py, pay-api/tests/unit/services/test_direct_pay_service.py, pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/4242
Added test cases.
*Checklist:*
=> added test cases

pay-api/src/pay_api/schemas/schemas/distribution_code.json, pay-api/tests/utilities/base_test.py
*Issue #:*
- Fixing issue with schema validation for distribution
*Checklist:*
=> Fixing issue with schema validation for distribution

jobs/update-stale-payment/config.py, jobs/update-stale-payment/requirements/prod.txt, jobs/update-stale-payment/update_stale_payment_records.py, pay-api/src/pay_api/services/direct_pay_service.py, pay-api/src/pay_api/services/invoice_reference.py, pay-api/src/pay_api/services/payment_service.py, pay-api/src/pay_api/services/payment_transaction.py, pay-api/src/pay_api/services/receipt.py, pay-api/tests/unit/services/test_payment_service.py, pay-api/tests/unit/services/test_payment_transaction.py, pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/4247
- Adding sentry to job
- Updates to consider EVENT_FAILED transactions on job run
- Reducing the time to 30 minutes to check for in progress transactions, as 4 hours is bit lengthy
- Changing some model save to flush for proper transaction handling
*Checklist:*
=> Changes to handle direct pay transactions by update-stale-jobs

bcol-api/Dockerfile, bcol-api/requirements.txt
=> BCOL docker file update.

pay-api/src/pay_api/services/direct_pay_service.py, pay-api/tests/unit/api/test_payment.py
*Issue #:*
- Changes for handling update for direct pay
*Checklist:*
=> Changes for handling update for direct pay

.github/workflows/report-api-test.yml, bcol-api/Dockerfile, bcol-api/scripts/openssl.cnf
=> Fix BCOL python-ldap openssl issue temporary.

pay-api/src/pay_api/models/statement_settings.py, pay-api/src/pay_api/resources/__init__.py, pay-api/src/pay_api/resources/account_statements_settings.py, pay-api/src/pay_api/services/__init__.py, pay-api/src/pay_api/services/statement.py, pay-api/src/pay_api/services/statement_settings.py, pay-api/tests/unit/api/test_statement_settings.py
*Issue #:*
https://github.com/bcgov/entity/issues/3637
Added GET , PUT endpoint for statement settings
TODO
Add tests
Add the schema validation
Few refactoring.
Working on this still.But would like to get it in dev so that UI integration can be finished
*Checklist:*
=> statement settings endpoints created

jobs/update-failed-distributions/jobs/distribution_job.py, pay-api/src/pay_api/services/statement.py
*Issue #:*
- Filtering out other payment methods for updating GL code
- Adding statement details to report payload
*Checklist:*
=> Filtering revenue update call only for direct pay invoices

jobs/update-failed-distributions/config.py, jobs/update-failed-distributions/invoke_jobs.py, jobs/update-failed-distributions/jobs/statement_job.py, jobs/update-failed-distributions/jobs/statement_notification_job.py, jobs/update-failed-distributions/run_send_statement_notificaton.sh, jobs/update-failed-distributions/statement_notification.html, jobs/update-failed-distributions/utils/auth.py, pay-api/migrations/versions/8f550bdc9491_notification_tables_added.py, pay-api/src/pay_api/models/statement.py, pay-api/src/pay_api/models/statement_recipients.py, pay-api/src/pay_api/utils/enums.py
*Issue #:*
https://github.com/bcgov/entity/issues/3310
New job added
Corrected the email status values in alembic.I will run them manually in DEV
*Checklist:*
=> Statement Notification Job Added

pay-api/src/pay_api/resources/account.py, pay-api/src/pay_api/resources/account_statements.py, pay-api/src/pay_api/resources/invoice_receipt.py, pay-api/src/pay_api/services/payment.py, pay-api/src/pay_api/services/statement.py
*Issue #:*
- Adding  Access-Control-Expose-Headers header to report downloads
*Checklist:*
=> Adding  Access-Control-Expose-Headers header to report downloads

pay-api/src/pay_api/services/statement_recipients.py
*Issue #:*
https://github.com/bcgov/entity/issues/3310
*Checklist:*
=> when no payment account is created , return False

report-api/report-templates/statement_report.html
*Issue #:*
https://github.com/bcgov/entity/issues/3649
- statement pdf layout correction
*Checklist:*
=> statement pdf layout correction

pay-api/src/pay_api/models/statement.py
*Issue #:*
- Adding payment join on statement query
*Checklist:*
=> Adding payment join on statement query

report-api/report-templates/statement_report.html
=> Fixing the issue with PDF not rendering line items

pay-api/src/pay_api/models/statement.py, report-api/report-templates/statement_report.html
=> test development

jobs/payment-jobs/statement_notification.html
*Issue #:*
https://github.com/bcgov/entity/issues/entity4683
Content updates the statement notification email template
*Checklist:*
=> [entity4683] Statement Email Notification Content Changes

pay-api/src/pay_api/models/statement.py, pay-api/tests/unit/api/test_statement.py
*Issue #:*
https://app.zenhub.com/workspaces/entity-5bf2f2164b5806bc2bf60531/issues/bcgov/entity/3638
*Checklist:*
=> Corrected sort order and added test to verify it

jobs/payment-jobs/statement_notification.html, pay-api/src/pay_api/models/statement.py, pay-api/tests/unit/api/test_statement.py, report-api/report-templates/statement_report.html
=> dev to test merge

pay-api/src/pay_api/models/audit.py, pay-api/src/pay_api/models/distribution_code.py, pay-api/src/pay_api/models/invoice.py, pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/models/payment_transaction.py, pay-api/src/pay_api/models/receipt.py, pay-api/src/pay_api/models/statement.py, pay-api/src/pay_api/services/auth.py, pay-api/src/pay_api/services/payment.py, pay-api/src/pay_api/utils/constants.py, report-api/report-templates/statement_report.html, report-api/src/api/__init__.py, report-api/src/api/services/report_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/4821
- statement pdf layout fixes
*Checklist:*
=> statement pdf layout fixes

report-api/report-templates/statement_report.html
*Issue #:*
- Fixing issue with a variable in statement report
*Checklist:*
=> Fixing issue with a variable in statement report

jobs/payment-jobs/tasks/statement_notification_task.py, pay-api/migrations/versions/71c733c91cbf_add_default_weekly_frequency_to_.py
*Issue #:*
https://github.com/bcgov/entity/issues/3637
https://github.com/bcgov/entity/issues/4809
1) skip sending if no recipients
2) modified existing scripts to create entries for only bcol accounts
3) changed link url
*Checklist:*
=> skip sending if no recipients ; modify script to create statements only for bcol accounts

pay-api/src/pay_api/services/statement_settings.py, report-api/report-templates/statement_report.html
=> Test Deployment

jobs/payment-jobs/tasks/statement_task.py, pay-api/src/pay_api/services/statement_settings.py, pay-api/tests/unit/api/test_statement_settings.py, pay-api/tests/unit/services/test_statement_settings.py
*Issue #:*
https://github.com/bcgov/entity/issues/4896
*Checklist:*
=> Fix for weekly statements not getting generated

queue_services/events-listener/requirements/repo-libraries.txt, queue_services/events-listener/src/events_listener/worker.py, queue_services/events-listener/tests/integration/utils.py
*Issue #:*
- Changes to align with the message changes from entities
*Checklist:*
=> Changes to align with the message changes from entities

.github/workflows/bcol-api-cd.yml, .github/workflows/events-listener-cd.yml, .github/workflows/pay-api-cd.yml, .github/workflows/payment-jobs-cd.yml, .github/workflows/report-api-cd.yml
=> Upgrade cd action to 1.1.1.

.github/workflows/bcol-api-cd.yml, .github/workflows/events-listener-cd.yml, .github/workflows/pay-api-cd.yml, .github/workflows/payment-jobs-cd.yml, .github/workflows/report-api-cd.yml
=> Update the cd action tag to latest.

.github/workflows/bcol-api-cd.yml, .github/workflows/events-listener-cd.yml, .github/workflows/pay-api-cd.yml, .github/workflows/payment-jobs-cd.yml, .github/workflows/report-api-cd.yml
=> Update vaults's setting.

.github/workflows/bcol-api-cd.yml, .github/workflows/events-listener-cd.yml, .github/workflows/pay-api-cd.yml, .github/workflows/payment-jobs-cd.yml, .github/workflows/report-api-cd.yml
=> Add OPENSHIFT_REPOSITORY_DEPLOYMENT input.

pay-api/migrations/versions/56c5db141909_refactor_payment_account.py
=> Fixing issue with migration

pay-api/src/pay_api/schemas/schemas/account_info.json, pay-api/src/pay_api/schemas/schemas/business_info.json, pay-api/src/pay_api/schemas/schemas/payment_info.json
*Issue #:*
https://github.com/bcgov/entity/issues/4732
- Changes to schema for create payment account endpoint
- Adding contact info and more information to payment info
*Checklist:*
=> Changes to schema for create payment account endpoint

pay-api/src/pay_api/models/payment.py
*Issue #:*
https://github.com/bcgov/entity/issues/4341
- Search by username on transaction view - case insensitive search
*Checklist:*
=> Search by username on transaction view - case insensitive search

pay-api/requirements.txt, pay-api/src/pay_api/factory/payment_system_factory.py, pay-api/src/pay_api/services/__init__.py, pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/services/bcol_service.py, pay-api/src/pay_api/services/cfs_service.py, pay-api/src/pay_api/services/direct_pay_service.py, pay-api/src/pay_api/services/internal_pay_service.py, pay-api/src/pay_api/services/online_banking_service.py, pay-api/src/pay_api/services/paybc_service.py, pay-api/src/pay_api/services/payment.py, pay-api/src/pay_api/services/payment_service.py, pay-api/src/pay_api/services/payment_transaction.py, pay-api/tests/unit/services/test_payment_system_service.py
=> Changes for new implementation class for online banking

pay-api/src/pay_api/services/bcol_service.py, pay-api/src/pay_api/services/online_banking_service.py, pay-api/src/pay_api/services/payment_service.py
*Issue #:*
- Fixing issue with BCOL account number not populated for staff payments
*Checklist:*
=> Fixing issue with BCOL account number not populated for staff payments

pay-api/migrations/versions/8652bf9c03ff_payment_to_invoice.py
=> Fixing issues with failed migration

docs/docs/api_contract/pay-api-1.0.0.yaml
Added a basic spec for accounts endpoint
*Checklist:*
=> added a basic spec for /accounts endpoint

docs/docs/PayBC Mocking/paybc-1.0.0.yaml, pay-api/src/pay_api/config.py, pay-api/src/pay_api/services/auth.py, pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/services/bcol_service.py, pay-api/src/pay_api/services/cfs_service.py, pay-api/src/pay_api/services/direct_pay_service.py, pay-api/src/pay_api/services/internal_pay_service.py, pay-api/src/pay_api/services/pad_service.py, pay-api/src/pay_api/services/paybc_service.py, pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/services/payment_service.py, pay-api/tests/docker/docker-compose.yml, pay-api/tests/unit/services/test_bcol_service.py, pay-api/tests/unit/services/test_pad_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/4733
- Changes for adding PAD service implementation
- Creates payment details in CFS as part of create account
*Checklist:*
=> Changes for adding PAD service implementation

pay-api/src/pay_api/resources/__init__.py, pay-api/src/pay_api/resources/invoice.py, pay-api/tests/unit/api/test_invoice.py
*Issue #:*
- Adding invoices endpoint to unblock names team.
*Checklist:*
=> Adding invoices endpoint to unblock names team.

.github/workflows/bcol-api-cd.yml, .github/workflows/pay-api-cd.yml, .github/workflows/payment-jobs-cd.yml, .github/workflows/report-api-cd.yml
*Issue #:*
https://github.com/bcgov/entity/issues/4874
- Updating the GHA to use jwt application from relationship vault
*Checklist:*
=> Updating the GHA to use jwt application from relationship vault

jobs/payment-jobs/cron/crontab, jobs/payment-jobs/invoke_jobs.py, jobs/payment-jobs/run_stale_payments.sh, jobs/payment-jobs/tasks/stale_payment_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/4670
- converted the job
- the sentry code was in there ; I just copied.
- the openshift changes l i will do once this gets merged
- didnt remove the existing code  ;once this gets to prod ; will have another PR for removal
*Checklist:*
=> update-stale-payment converted to crond

jobs/payment-jobs/tasks/stale_payment_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/4670
*Checklist:*
=> Fixing the typo

queue_services/events-listener/requirements.txt
*Issue #:*
- Fixing requirements
*Checklist:*
=> Fixing requirements

pay-api/migrations/versions/8652bf9c03ff_payment_to_invoice.py
…ATED records
*Issue #:*
*Checklist:*
=> Fixing issue with migration where it skips DELETE_ACCEPTED and GL_UPDATED

jobs/payment-jobs/config.py
*Issue #:*
https://github.com/bcgov/entity/issues/4670
*Checklist:*
=> added the missing configs

jobs/payment-jobs/LICENSE, jobs/payment-jobs/requirements/dev.txt, jobs/payment-jobs/setup.py, jobs/payment-jobs/tasks/cfs_create_account_task.py, jobs/payment-jobs/tasks/cfs_create_invoice.py, jobs/payment-jobs/tasks/statement_task.py, jobs/payment-jobs/tests/jobs/conftest.py, jobs/payment-jobs/tests/jobs/factory.py, jobs/payment-jobs/tests/jobs/test_cfs_create_account_task.py, jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py, jobs/payment-jobs/tests/jobs/test_distribution_task.py, jobs/payment-jobs/tests/jobs/test_generate_statements.py, jobs/payment-jobs/tests/jobs/test_statement_notification_task.py, pay-api/src/pay_api/services/payment_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/4776
- Fixing error with jobs and pytest
*Checklist:*
=> Fixing error with jobs and pytest

jobs/payment-jobs/tasks/stale_payment_task.py
*Issue #:*
- Passing empty string causes issue with txn number lookup
*Checklist:*
=> Fixing issue with stale payment not picking correct txn number

docs/docs/PayBC Mocking/paybc-1.0.0.yaml, pay-api/tests/docker/docker-compose.yml, pay-api/tests/docker/nginx.conf, pay-api/tests/unit/api/test_bank_accounts.py
*Issue #:*
https://github.com/bcgov/entity/issues/4773
Added the missing tests.
- nginx request body is not available during location ;so have to go for map
*Checklist:*
=> added missing tests for bank endpoint

pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/services/payment_service.py, pay-api/tests/unit/api/test_payment.py
*Issue #:*
- Handling default payments to DIRECT_PAY
*Checklist:*
=> Handling default payments to DIRECT_PAY

.github/workflows/payment-jobs-cd.yml, .github/workflows/payment-jobs-ci.yml, jobs/payment-jobs/config.py, jobs/payment-jobs/requirements/dev.txt, jobs/payment-jobs/requirements/prod.txt, jobs/payment-jobs/tasks/cfs_create_account_task.py, jobs/payment-jobs/tests/docker/docker-compose.yml, jobs/payment-jobs/tests/docker/nginx.conf, jobs/payment-jobs/tests/docker/run.sh, jobs/payment-jobs/tests/docker/setup/demo-realm.json, jobs/payment-jobs/tests/jobs/conftest.py, jobs/payment-jobs/tests/jobs/factory.py, jobs/payment-jobs/tests/jobs/test_cfs_create_account_task.py, pay-api/src/pay_api/services/cfs_service.py, pay-api/src/pay_api/services/online_banking_service.py, pay-api/src/pay_api/services/pad_service.py, pay-api/src/pay_api/services/queue_publisher.py, pay-api/tests/unit/api/test_account.py, pay-api/tests/unit/services/test_payment_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/5016
- Changing PAD and Online Banking account creation and update to job
*Checklist:*
=> Creating CFS accounts offline

jobs/payment-jobs/tasks/cfs_create_account_task.py, pay-api/src/pay_api/services/cfs_service.py
*Issue #:*
- Handling error on CFS Account creation
*Checklist:*
=> Handling error on CFS Account creation

jobs/payment-jobs/requirements/prod.txt
=> Updating pay dependency to bcgov repo

jobs/payment-jobs/config.py, jobs/payment-jobs/invoke_jobs.py, jobs/payment-jobs/requirements/prod.txt, jobs/payment-jobs/tasks/cfs_create_account_task.py, jobs/payment-jobs/tasks/cfs_create_invoice_task.py, jobs/payment-jobs/tests/jobs/factory.py, jobs/payment-jobs/tests/jobs/test_cfs_create_account_task.py, jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py, jobs/payment-jobs/tests/jobs/test_generate_statements.py, pay-api/migrations/versions/2d025cbefda8_settlement_sched_refund_requested_.py, pay-api/src/pay_api/config.py, pay-api/src/pay_api/services/bcol_service.py, pay-api/src/pay_api/services/cfs_service.py, pay-api/src/pay_api/services/direct_pay_service.py, pay-api/src/pay_api/services/internal_pay_service.py, pay-api/src/pay_api/services/paybc_service.py, pay-api/src/pay_api/utils/enums.py, pay-api/src/pay_api/utils/util.py, pay-api/tests/docker/docker-compose.yml, pay-api/tests/unit/services/test_direct_pay_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/4777
- Roll up transactions and create invoice(s) in CFS for PAD transactions
- Create individual invoice for Online Banking Transactions
- Update invoice status and created payment records
- Changing all transaction number to have same pattern. REG<padded 8 zeros with invoice number>
*Checklist:*
=> Roll up transactions and create invoice in CFS

jobs/payment-jobs/config.py, pay-api/src/pay_api/config.py, pay-api/src/pay_api/services/queue_publisher.py, queue_services/events-listener/q_cli.py, queue_services/events-listener/src/events_listener/config.py, queue_services/events-listener/tests/conftest.py, queue_services/events-listener/tests/integration/__init__.py, queue_services/events-listener/tests/integration/test_worker_queue.py
=> Updating config keys

docs/docs/api_contract/pay-api-1.0.0.yaml
*Issue #:*
- Updating API spec to include refund endpoint
*Checklist:*
=> Updating API spec to include refunds endpoint

pay-api/src/pay_api/models/invoice.py, pay-api/src/pay_api/services/invoice.py, pay-api/tests/unit/api/test_payment.py
*Issue #:*
https://github.com/bcgov/entity/issues/5252
- Adding isPaymentActionRequired flag to invoice response
*Checklist:*
=> Adding isPaymentActionRequired flag to invoice response

.github/workflows/ftp-poller-cd.yml, .github/workflows/ftp-poller-ci.yml
=> GH actions for poller job added

jobs/ftp-poller/README.md, jobs/ftp-poller/config.py, jobs/ftp-poller/openshift/ftp-poller-deploy.json, jobs/ftp-poller/services/sftp.py, jobs/ftp-poller/tests/jobs/test_sftp.py
=> Sftp adjustments 

jobs/ftp-poller/README.md, jobs/ftp-poller/config.py, jobs/ftp-poller/openshift/ftp-poller-deploy.json, jobs/ftp-poller/services/sftp.py, jobs/ftp-poller/tests/jobs/test_sftp.py
*Issue #:*
https://github.com/bcgov/entity/issues/5012
* Changes for giving privaty key as a config map file
* Removed the default password which caused issues
* added readme
*Checklist:*
=> Sftp adjustments  (#402)

.github/workflows/bcol-api-cd.yml, .github/workflows/events-listener-cd.yml, .github/workflows/ftp-poller-cd.yml, .github/workflows/pay-api-cd.yml, .github/workflows/payment-jobs-cd.yml, .github/workflows/payment-reconciliations-cd.yml, .github/workflows/report-api-cd.yml
=> Update for set environment variables issue of GHA.

.github/workflows/payment-reconciliations-cd.yml, .github/workflows/payment-reconciliations-ci.yml, .gitignore, jobs/payment-jobs/tasks/cfs_create_invoice_task.py, jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py, pay-api/src/pay_api/config.py, pay-api/src/pay_api/models/payment_transaction.py, pay-api/src/pay_api/services/payment_transaction.py, pay-api/src/pay_api/utils/enums.py, queue_services/payment-reconciliations/app.py, queue_services/payment-reconciliations/q_cli.py, queue_services/payment-reconciliations/requirements.txt, queue_services/payment-reconciliations/requirements/dev.txt, queue_services/payment-reconciliations/requirements/prod.txt, queue_services/payment-reconciliations/requirements/repo-libraries.txt, queue_services/payment-reconciliations/setup.py, queue_services/payment-reconciliations/src/reconciliations/config.py, queue_services/payment-reconciliations/src/reconciliations/enums.py, queue_services/payment-reconciliations/src/reconciliations/minio.py, queue_services/payment-reconciliations/src/reconciliations/worker.py, queue_services/payment-reconciliations/tests/conftest.py, queue_services/payment-reconciliations/tests/docker-compose.yml, queue_services/payment-reconciliations/tests/integration/factory.py, queue_services/payment-reconciliations/tests/integration/test_payment_reconciliations.py, queue_services/payment-reconciliations/tests/integration/utils.py
*Issue #:*
https://github.com/bcgov/entity/issues/4778
- Changes for PAD and Online Banking settlement worker queue
- Changes for including outstanding invoices on rollup
*Checklist:*
=> CAS settlement

jobs/payment-jobs/requirements/prod.txt, queue_services/payment-reconciliations/requirements.txt, queue_services/payment-reconciliations/requirements/repo-libraries.txt
=> Updating requirements to point to bcgov development branch.

jobs/payment-jobs/tasks/distribution_task.py
*Issue #:*
- Fixing issue with distribution task
*Checklist:*
=> Fixing issue with distribution task

jobs/payment-jobs/requirements/prod.txt, queue_services/payment-reconciliations/requirements/repo-libraries.txt
=> Dev to Test

pay-api/src/pay_api/services/cfs_service.py
=> Adding customer profile class to site creation

queue_services/payment-reconciliations/src/reconciliations/enums.py, queue_services/payment-reconciliations/src/reconciliations/worker.py, queue_services/payment-reconciliations/tests/integration/test_payment_reconciliations.py
*Issue #:*
- Changes to reflect CAS settlement file changes
*Checklist:*
=> Changes to reflect CAS settlement file changes

pay-api/src/pay_api/services/payment_account.py
=> Fixing the typo in the mailer config

pay-api/src/pay_api/services/payment_account.py
=> Fixing the typo in the mailer config (#429)

pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/utils/util.py
*Issue #:*
https://github.com/bcgov/entity/issues/5343
Changed the date to 12.00 AM of next day for better PDFs.
*Checklist:*
=> Changed the date from end of the day to 12.00AM

pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/utils/util.py
* Fixing the date format and start of the day issue
*Issue #:*
*Checklist:*
=> Changed the date from end of the day to 12.00AM (#431)

docs/docs/PayBC Mocking/paybc-1.0.0.yaml, pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/resources/payment.py, pay-api/src/pay_api/services/cfs_service.py, pay-api/src/pay_api/services/paybc_service.py, pay-api/src/pay_api/services/payment.py, pay-api/src/pay_api/services/payment_transaction.py, pay-api/src/pay_api/utils/util.py, pay-api/tests/docker/docker-compose.yml, pay-api/tests/unit/api/test_payment.py, pay-api/tests/unit/services/test_payment.py, pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/4920
- POST /payments endpoint for re-trying a failed payment
*Checklist:*
=> Creating POST payments to retry failed payments

pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/services/bcol_service.py, pay-api/src/pay_api/services/direct_pay_service.py, pay-api/src/pay_api/services/internal_pay_service.py, pay-api/src/pay_api/services/online_banking_service.py, pay-api/src/pay_api/services/pad_service.py, pay-api/src/pay_api/services/paybc_service.py, pay-api/tests/unit/services/test_bcol_service.py, pay-api/tests/unit/services/test_direct_pay_service.py, pay-api/tests/unit/services/test_pad_service.py, pay-api/tests/unit/services/test_payment_system_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/4920
- Changes to base_payment_system to make get_payment_system_url as not abstract as it's not applicable in all cases.
*Checklist:*
=> Changes to base_payment_system to make get_payment_system_url as not abstract

pay-api/src/pay_api/services/cfs_service.py, pay-api/src/pay_api/services/oauth_service.py
=> Fixing issue with update site.

pay-api/src/pay_api/models/invoice.py, pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/services/payment.py
=> Fixing issue with amount not matching on new payment for NSF

pay-api/src/pay_api/resources/refund.py
*Issue #:*
- Fix refunds endpoint to accept None payload
*Checklist:*
=> Fixing refund to accept None request

docs/docs/PayBC Mocking/paybc-1.0.0.yaml, pay-api/src/pay_api/services/cfs_service.py, pay-api/src/pay_api/services/paybc_service.py, pay-api/src/pay_api/services/payment.py, pay-api/tests/docker/docker-compose.yml
*Issue #:*
- Fixing creditbalance URL
*Checklist:*
=> Fixing creditbalance URL

pay-api/src/pay_api/services/pad_service.py, pay-api/src/pay_api/services/payment_transaction.py, pay-api/tests/unit/services/test_payment_service.py, pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/4888
- Releasing records for PAD on invoice creation
*Checklist:*
=> Releasing records for PAD on invoice creation

pay-api/src/pay_api/resources/invoice.py, pay-api/src/pay_api/services/payment_service.py, pay-api/tests/unit/services/test_payment_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/4890
*Checklist:*
=> Patch endpoint added for changing the payment method

pay-api/src/pay_api/resources/invoice.py, pay-api/tests/unit/api/test_payment_request.py
*Issue #:*
https://github.com/bcgov/entity/issues/5667
bug fixes and a test
Please ignore the multiple comits.I will squash them
*Checklist:*
=> fixed misc error and added tests

pay-api/src/pay_api/factory/payment_system_factory.py, pay-api/src/pay_api/services/deposit_service.py, pay-api/src/pay_api/services/eft_service.py, pay-api/src/pay_api/services/payment_transaction.py, pay-api/src/pay_api/services/wire_service.py, pay-api/tests/unit/factory/test_payment_system_factory.py, pay-api/tests/unit/services/test_eft_service.py, pay-api/tests/unit/services/test_payment_service.py, pay-api/tests/unit/services/test_wire_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/4734
- Adding service classes for EFT and Wire transfer.
*Checklist:*
=> Adding service classes for EFT and Wire transfer.

pay-api/src/pay_api/services/payment_service.py, pay-api/tests/unit/api/test_payment_request.py
*Issue #:*
https://github.com/bcgov/entity/issues/4890
*Checklist:*
=> Fixed invoice ref creation on direct pay

jobs/payment-jobs/tasks/cfs_create_invoice_task.py, jobs/payment-jobs/tests/jobs/factory.py, jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py, pay-api/src/pay_api/services/refund.py, pay-api/src/pay_api/services/wire_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/4734
- Changing job to create EFT and WIRE invoices in CFS
- Small null check for refund endpoint
*Checklist:*
=> Create EFT, WIRE invoice from job

.github/PULL_REQUEST_TEMPLATE.md
*Issue #:*
- Updating PR template as CI does the checklist tasks
=> Updating PR template as CI does the checklist tasks

docs/docs/PayBC Mocking/paybc-1.0.0.yaml, pay-api/src/pay_api/services/cfs_service.py, pay-api/tests/docker/docker-compose.yml
=> Fixing receipt URL

pay-api/migrations/versions/331c2cdb0b94_fix_payment_account_id_in_payment_table.py, pay-api/src/pay_api/services/payment_transaction.py, pay-api/tests/docker/docker-compose.yml, queue_services/payment-reconciliations/src/reconciliations/worker.py
*Issue #:*
https://github.com/bcgov/entity/issues/5824
- Fixing payment account id in payments table.
=> Fixing payment account id in payments table.

pay-api/src/pay_api/schemas/schemas/account_info.json, pay-api/src/pay_api/services/payment_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/5655
https://github.com/bcgov/entity/issues/5299
*Checklist:*
=> TOS Flags added

pay-api/src/pay_api/services/payment_transaction.py
*Issue #:*
https://github.com/bcgov/entity/issues/5667
=> Fix for OB paying with CC invoiced flow

pay-api/src/pay_api/services/payment_account.py
=> Fix for linked PAD accounts not creating cfs table entries

jobs/payment-jobs/config.py, jobs/payment-jobs/requirements/prod.txt, jobs/payment-jobs/tasks/cfs_create_account_task.py, pay-api/src/pay_api/config.py, pay-api/src/pay_api/services/auth.py, pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/utils/user_context.py, pay-api/src/pay_api/utils/util.py, pay-api/tests/docker/docker-compose.yml, pay-api/tests/unit/api/test_account.py, queue_services/payment-reconciliations/requirements.txt
*Issue #:*
https://github.com/bcgov/entity/issues/5563
Follow up PR is https://github.com/bcgov/sbc-auth/pull/1199
1) called the auth authorisation endpoint.
2) added the permissions to user context so that it easy to look up
3) added mask function
4) added mask to the events
=> Role based masking added

pay-api/src/pay_api/utils/user_context.py
=> fixed the wrong permissions

pay-api/tests/docker/docker-compose.yml
=> updating the wrong branch name

queue_services/payment-reconciliations/src/reconciliations/enums.py, queue_services/payment-reconciliations/src/reconciliations/worker.py, queue_services/payment-reconciliations/tests/integration/factory.py, queue_services/payment-reconciliations/tests/integration/test_payment_reconciliations.py
*Issue #:*
- Adding PADR record type to handle NSF
=> Handling PAD Reversals

pay-api/src/pay_api/services/payment_account.py, pay-api/tests/unit/api/test_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/5064
- Added a new flag as futurePaymentMethod.
- return bank details even when in bcol
=> Return bank details and a new flag for pad activation pending accounts

pay-api/src/pay_api/models/payment_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/5066
=> UI needs PAD accepted details.

pay-api/src/pay_api/schemas/schemas/payment.json
=> Adding DRAWDOWN to enum

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/tasks/activate_pad_account_task.py, jobs/payment-jobs/tasks/cfs_create_invoice_task.py, jobs/payment-jobs/tests/jobs/factory.py, jobs/payment-jobs/tests/jobs/test_generate_statements.py, jobs/payment-jobs/utils/mailer.py
*Issue #:*
https://github.com/bcgov/entity/issues/5352
https://github.com/bcgov/entity/issues/5564
=> added more events

pay-api/src/pay_api/services/auth.py, pay-api/src/pay_api/services/oauth_service.py, pay-api/tests/unit/services/test_direct_pay_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/5826
1) just added the corp type as a header.
I fixed that breaking tests.not related to this though.
=> Fix for adding corp type to support names authorised requests

jobs/payment-jobs/tasks/cfs_create_invoice_task.py
=> Fixing misc. UAT issues

jobs/payment-jobs/config.py
=> Adding missing config details for mailer

jobs/payment-jobs/config.py
* Adding missing config details for mailer
*Issue #:*
=> Adding missing config details for mailer (#503)

pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/services/payment.py, pay-api/src/pay_api/services/payment_transaction.py, queue_services/payment-reconciliations/src/reconciliations/enums.py, queue_services/payment-reconciliations/src/reconciliations/worker.py
*Issue #:*
https://github.com/bcgov/entity/issues/6038
- Handling DWRP, and partial paid NSF payments
=> Handling DWRP, and partial paid NSF payments

pay-api/src/pay_api/services/payment.py, pay-api/src/pay_api/services/payment_transaction.py
*Issue #:*
- 6038 : Fixing NSF partial payments
=> 6038 : Fixing NSF partial payments

jobs/payment-jobs/tasks/cfs_create_invoice_task.py
*Issue #:*
- Adding INACTIVE status to cfs account on creating invoice in PayBC.
=> Adding INACTIVE status to cfs account on creating invoice in PayBC.

pay-api/src/pay_api/resources/account.py, pay-api/src/pay_api/services/pad_service.py, pay-api/src/pay_api/services/payment_account.py, pay-api/tests/unit/api/test_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/6038
- Adding bank info to CFS when the PAD update happens
=> Fixing issue with PAD account update

report-api/report-templates/invoice.html
*Issue #:*
https://github.com/bcgov/entity/issues/5799
=> Generate and Download Invoice - Online Banking#5799

pay-api/src/pay_api/services/fee_schedule.py, pay-api/src/pay_api/services/invoice.py, pay-api/src/pay_api/services/pad_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/5799
- Pass empty business identifier if the PDF is for temp business
- Set the status of the updated account to FREEZE if current account was FREEZE
=> Miscellaneous fixes for invoice PDF and NSF bank update

pay-api/src/pay_api/resources/account.py, pay-api/tests/docker/docker-compose.yml
https://github.com/bcgov/entity/issues/6041
*Issue #:*
https://github.com/bcgov/entity/issues/6041
Added view role to display payment method
=> view roled staff should be able to see payment info 

docs/docs/PayBC Mocking/paybc-1.0.0.yaml, pay-api/src/pay_api/services/cfs_service.py, pay-api/tests/docker/docker-compose.yml, pay-api/tests/unit/api/test_bank_accounts.py
*Issue #:*
https://github.com/bcgov/entity/issues/5723
- Changes for pre-padding bank transit and institution number
=> 5723: Changes for pre-padding bank transit and institution number

pay-api/src/pay_api/config.py
=> Fixed the URL path setting issue.

queue_services/payment-reconciliations/src/reconciliations/worker.py, queue_services/payment-reconciliations/tests/conftest.py
*Issue #:*
bcgov/entity#4895
- Changes for publishing events per payment, not per invoice for online banking emails
=> Changes for sending emails for online banking payments.

pay-api/src/pay_api/resources/account_statements_notifications.py, pay-api/src/pay_api/resources/account_statements_settings.py, pay-api/src/pay_api/utils/constants.py, pay-api/tests/docker/docker-compose.yml
*Issue #:*
https://github.com/bcgov/entity/issues/5893
- added permissions for account statement settings
=> fine grained roles from account statements

jobs/payment-jobs/tasks/cfs_create_invoice_task.py
=> Changing append to extend to fix issues with multiple line items

jobs/payment-jobs/config.py
=> Fixing issue with auth api config value

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/tasks/cfs_create_account_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/5440
=> Adding an event for mailer if PAD account creation fails

jobs/payment-jobs/devops/vaults.json, pay-api/devops/vaults.json, queue_services/payment-reconciliations/devops/vaults.json
=> Changes for adding encryption keys to job

pay-api/src/pay_api/resources/invoice.py, pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/services/online_banking_service.py, pay-api/src/pay_api/services/pad_service.py, pay-api/src/pay_api/services/paybc_service.py, pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/services/payment_service.py, pay-api/tests/unit/api/test_payment_request.py
*Issue #:*
https://github.com/bcgov/entity/issues/5662
- Adding applyCredit arg to invoice PATCH to apply the credit.
=> Changes for releasing records if the account have credit.

jobs/payment-jobs/config.py, jobs/payment-jobs/invoke_jobs.py, jobs/payment-jobs/run_notify_unpaid_invoices.sh, jobs/payment-jobs/tasks/unpaid_invoice_notify_task.py, jobs/payment-jobs/tests/jobs/factory.py, jobs/payment-jobs/tests/jobs/test_unpaid_invoice_notifytask.py
*Issue #:*
https://github.com/bcgov/entity/issues/6043
New task added
=> mail added for pending payment

jobs/payment-jobs/devops/vaults.json
=> added payment-job vault section

pay-api/src/pay_api/services/payment_service.py
*Issue #:*
- Updating the paid field in invoice 
=> Updating paid amount to invoice incase if it's a partial credit

jobs/payment-jobs/tasks/unpaid_invoice_notify_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/6043
=> correcting message type 

.github/workflows/payment-reconciliations-ci.yml, queue_services/payment-reconciliations/requirements.txt, queue_services/payment-reconciliations/tests/conftest.py
*Issue #:6072
https://github.com/bcgov/entity/issues/6072
Add ACCOUNT_SECRET_KEY to env
Start paybc, nats, proxy docker services.  
=> 6072-Fix GHA issue with reconciliations

jobs/payment-jobs/tasks/unpaid_invoice_notify_task.py, jobs/payment-jobs/tests/jobs/test_unpaid_invoice_notifytask.py
*Issue #:*
https://github.com/bcgov/entity/issues/6384
=>  Amount displayed in OB pending amount email

.gitignore, jobs/payment-jobs/config.py, jobs/payment-jobs/devops/vaults.json, jobs/payment-jobs/openshift/payment-job-deploy.json, jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/prod.txt, jobs/payment-jobs/tasks/cgi_ejv_task.py, jobs/payment-jobs/tests/docker/docker-compose.yml, jobs/payment-jobs/tests/jobs/conftest.py, jobs/payment-jobs/tests/jobs/test_cgi_ejv_task.py, jobs/payment-jobs/utils/sftp.py, queue_services/payment-reconciliations/src/reconciliations/config.py
*Issue #:*
https://github.com/bcgov/entity/issues/6250
- Changes for uploading sFTP file
- Using ftp-poller config for sFTP configuration
=> Changes for uploading JV and TRG file to FTP

jobs/ftp-poller/invoke_jobs.py, jobs/ftp-poller/run_cgi_feeder_poller.sh
=> Added missing sh file

jobs/payment-jobs/config.py, jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/prod.txt, jobs/payment-jobs/tasks/cgi_ejv_task.py, pay-api/src/pay_api/config.py, pay-api/src/pay_api/utils/util.py, pay-api/tests/unit/utils/test_util.py
*Issue #:*
https://github.com/bcgov/entity/issues/6397
=> file name changed to reflect business day

pay-api/src/pay_api/models/invoice.py, pay-api/tests/unit/services/test_payment_service.py
=> Changing PAD invoice status to COMPLETED as an interim fix.

pay-api/src/pay_api/services/receipt.py, pay-api/tests/unit/api/test_receipt.py
=> Fix for receipt for pending pad payments

report-api/report-templates/payment_receipt.html
*Issue #:*
* template changes. when PAD is pending state
=>  Handle receipt for PAD (not yet PAID) invoices | template changes

pay-api/src/pay_api/services/receipt.py, report-api/report-templates/payment_receipt.html
*Issue #:*
Added a new variable to pass to report templates as paymentMethodCode since earlier we were passing description.
=> Added paymentMethodCode to be passed to report api

jobs/ftp-poller/run_cgi_feeder_poller.sh, jobs/ftp-poller/run_ftp_poller.sh, jobs/ftp-poller/tasks/cgi_feeder_poller_task.py
=> Fix poller 

report-api/report-templates/payment_receipt.html
=>  Handle receipt for PAD (not yet PAID) invoices

jobs/ftp-poller/config.py, jobs/ftp-poller/tasks/cgi_feeder_poller_task.py
=> trg file removed

jobs/ftp-poller/config.py, jobs/ftp-poller/tasks/cgi_feeder_poller_task.py
=> changed a few configs (#600)

report-api/report-templates/payment_receipt.html
=> Feature/5776 2 (#602)

report-api/report-templates/payment_receipt.html
=> Payment recipt

jobs/ftp-poller/config.py, jobs/ftp-poller/tasks/cgi_feeder_poller_task.py
=> added INBOX ignore

jobs/ftp-poller/config.py, jobs/ftp-poller/tasks/cgi_feeder_poller_task.py, report-api/report-templates/payment_receipt.html
=> dev to master

pay-api/src/pay_api/utils/util.py
=> Changes for fixing fiscal

jobs/ftp-poller/run_ftp_poller.sh
=> fixed param for ftp-poller

jobs/payment-jobs/tasks/unpaid_invoice_notify_task.py, jobs/payment-jobs/tests/jobs/test_unpaid_invoice_notifytask.py
*Issue #:*
https://github.com/bcgov/entity/issues/6384
=> unpaid invoices logic changed

jobs/ftp-poller/tasks/cgi_feeder_poller_task.py, jobs/payment-jobs/tasks/cgi_ejv_task.py
=> Changes for skipping TRG file check on condition

jobs/payment-jobs/tasks/cfs_create_invoice_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/6654
=> Changes for skipping invoice creation for Online banking if the corp type is not enabled

jobs/payment-jobs/tasks/cgi_ejv_task.py
=> Fixing control total issue in JV file

pay-api/src/pay_api/services/auth.py, pay-api/src/pay_api/utils/util.py
*Issue #:*
https://github.com/bcgov/entity/issues/6579
=> Changing the header to Product-Code to match with auth api changes

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/prod.txt
=> fix the git links

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/prod.txt
=> fix the git links (#628)

report-api/report-templates/payment_receipt.html
=> style changed

pay-api/requirements.txt, pay-api/requirements/dev.txt, pay-api/src/pay_api/exceptions/__init__.py, pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/services/bcol_service.py, pay-api/src/pay_api/services/deposit_service.py, pay-api/src/pay_api/services/direct_pay_service.py, pay-api/src/pay_api/services/eft_service.py, pay-api/src/pay_api/services/internal_pay_service.py, pay-api/src/pay_api/services/oauth_service.py, pay-api/src/pay_api/services/online_banking_service.py, pay-api/src/pay_api/services/pad_service.py, pay-api/src/pay_api/services/paybc_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/6708
- Refactoring pay system service and updates for new lint version
=> Refactoring pay system service and updates for new lint version

queue_services/payment-reconciliations/src/reconciliations/ejv_reconciliations.py
=> Fixing issue with reconcilations

report-api/report-templates/payment_receipt.html
=> Fixing issue with receipt

pay-api/src/pay_api/utils/user_context.py
*Issue #:*
https://github.com/bcgov/entity/issues/5487
=> Api gateway integration changes

.github/workflows/bcol-api-cd.yml, .github/workflows/bcol-api-ci.yml, .github/workflows/events-listener-cd.yml, .github/workflows/events-listener-ci.yml, .github/workflows/ftp-poller-cd.yml, .github/workflows/ftp-poller-ci.yml, .github/workflows/pay-api-cd.yml, .github/workflows/pay-api-ci.yml, .github/workflows/payment-jobs-cd.yml, .github/workflows/payment-jobs-ci.yml, .github/workflows/payment-reconciliations-cd.yml, .github/workflows/payment-reconciliations-ci.yml, .github/workflows/report-api-cd.yml, .github/workflows/report-api-ci.yml, bcol-api/Dockerfile, bcol-api/Makefile, jobs/ftp-poller/Dockerfile, jobs/ftp-poller/Makefile, jobs/payment-jobs/Dockerfile, jobs/payment-jobs/Makefile, pay-api/Dockerfile, pay-api/Makefile, queue_services/events-listener/Dockerfile, queue_services/events-listener/Makefile, queue_services/payment-reconciliations/Dockerfile, queue_services/payment-reconciliations/Makefile, report-api/Dockerfile, report-api/Makefile
=> Update Dockerfile, Makefile and CICD flow scripts.

.github/workflows/bcol-api-cd.yml, .github/workflows/events-listener-cd.yml, .github/workflows/ftp-poller-cd.yml, .github/workflows/pay-api-cd.yml, .github/workflows/payment-jobs-cd.yml, .github/workflows/payment-reconciliations-cd.yml, .github/workflows/report-api-cd.yml
=> Fixed development branch issue.

jobs/payment-jobs/invoke_jobs.py, jobs/payment-jobs/requirements.txt, jobs/payment-jobs/run_cgi_ejv_task.sh, jobs/payment-jobs/run_cgi_partner_ejv_task.sh, jobs/payment-jobs/tasks/cgi_ejv.py, jobs/payment-jobs/tasks/ejv_partner_distribution_task.py, jobs/payment-jobs/tests/jobs/test_ejv_partner_distribution_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/7042
=> Refactoring current JV code to support multiple JVs

jobs/payment-jobs/config.py, jobs/payment-jobs/invoke_jobs.py, jobs/payment-jobs/run_cgi_payment_ejv_task.sh, jobs/payment-jobs/tasks/common/__init__.py, jobs/payment-jobs/tasks/common/cgi_ejv.py, jobs/payment-jobs/tasks/ejv_partner_distribution_task.py, jobs/payment-jobs/tasks/ejv_payment_task.py, jobs/payment-jobs/tasks/stale_payment_task.py, jobs/payment-jobs/tests/jobs/factory.py, jobs/payment-jobs/tests/jobs/test_activate_pad_account_task.py, jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py, jobs/payment-jobs/tests/jobs/test_ejv_payment_task.py, jobs/payment-jobs/tests/jobs/test_generate_statements.py
*Issue #:*
https://github.com/bcgov/entity/issues/7042
- Create and upload JV file for gov account payment
=> Changes for creating and uploading JV for gov account payments

jobs/payment-jobs/tasks/ejv_payment_task.py, jobs/payment-jobs/tests/jobs/factory.py, queue_services/payment-reconciliations/src/reconciliations/ejv_reconciliations.py, queue_services/payment-reconciliations/tests/integration/factory.py, queue_services/payment-reconciliations/tests/integration/test_ejv_reconciliations.py
*Issue #:*
https://github.com/bcgov/entity/issues/7042
- Group the JV feedback and process one by one
- Reconcile JV payments for gov account
=> Changes for reconciling multiple JV details in single file and to sync EJV payments

bcol-api/requirements.txt, bcol-api/requirements/prod.txt, bcol-api/src/bcol_api/services/bcol_profile.py, bcol-api/tests/unit/services/test_bcol_profile.py
*Issue #:*
https://github.com/bcgov/entity/issues/6945
Update country field to use 2 letters country code for BCOL account.
=> 6945 - Standardize country code.

pay-api/src/pay_api/services/payment_transaction.py, pay-api/src/pay_api/services/refund.py, pay-api/src/pay_api/utils/enums.py, pay-api/src/pay_api/utils/util.py
=> Miscellaneous bug fixes reported by other teams.

jobs/payment-jobs/requirements.txt, queue_services/events-listener/requirements.txt, queue_services/payment-reconciliations/requirements.txt
=> Updating requirement for new release

jobs/notebook-report/weekly/pay.ipynb
Signed-off-by: Chen <Steven.Chen@gov.bc.ca>
*Issue #:*
https://github.com/bcgov/entity/issues/7552
Added Online Banking and Direct Pay to notebook report
=> Added Online Banking and Direct Pay to notebook report #7552

docs/docs/api_contract/pay-api-1.0.0.yaml
*Issue #:*
https://github.com/bcgov/entity/issues/7264
=> Adding partner on-boarding document

pay-api/migrations/versions/0aa7d4deef8a_nofee_filing_type.py
*Issue #:*
https://github.com/bcgov/entity/issues/7590
=> Changes for adding NOFEE filing type code

pay-api/src/pay_api/resources/account.py, pay-api/src/pay_api/resources/fee_schedule.py, pay-api/src/pay_api/utils/enums.py, pay-api/tests/unit/api/test_account.py, pay-api/tests/unit/api/test_distributions.py, pay-api/tests/unit/api/test_fee.py, pay-api/tests/unit/api/test_payment_request.py
=> Role changes

pay-api/src/pay_api/services/auth.py, pay-api/src/pay_api/utils/user_context.py
*Issue #:*
https://github.com/bcgov/entity/issues/7154
- Changes for fixing gov account pay calculation for business affiliations
- 
=> Changes for fixing gov account pay calculation for business affiliations

queue_services/events-listener/requirements.txt, queue_services/events-listener/requirements/repo-libraries.txt
*Issue #:*
https://github.com/bcgov/entity/issues/3988
=> Fixing the repo back to bcgov

jobs/payment-jobs/config.py, jobs/payment-jobs/tasks/ejv_partner_distribution_task.py, jobs/payment-jobs/tests/jobs/factory.py, jobs/payment-jobs/tests/jobs/test_ejv_partner_distribution_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/7061
Added disbursement delay while fetching invoices.
Invoices are connected to receipts and avoided the invoices which has a receipt after disbursement date [thats why the negation operator]
=> Added disbursement delay

report-api/config.py, report-api/src/api/__init__.py, report-api/tests/unit/conf/test_configuration.py
=> Troubleshooting issue with reports api

pay-api/requirements/prod.txt, pay-api/src/pay_api/services/auth.py, pay-api/src/pay_api/utils/user_context.py, pay-api/tests/unit/api/test_payment_request.py, pay-api/tests/unit/services/test_auth.py
=> Fix for calculating the fees for govm accounts.

pay-api/migrations/versions/9c8a93ba9da2_restricted_ppr_fee_codes.py, pay-api/tests/docker/docker-compose.yml
*Issue #:*
https://github.com/bcgov/entity/issues/6848
RPRR product added
=> Added RPPR product

jobs/payment-jobs/tasks/stale_payment_task.py, jobs/payment-jobs/tests/docker/docker-compose.yml, queue_services/payment-reconciliations/requirements.txt, queue_services/payment-reconciliations/requirements/repo-libraries.txt, queue_services/payment-reconciliations/tests/docker-compose.yml
=> Fixing build error and changing the repo branch to main.

pay-api/src/pay_api/models/invoice.py, report-api/report-templates/payment_receipt.html, report-api/src/api/services/report_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/7716
- Changes to receipt pdf. 
- Excluding NR in adding dynamic details field
=> Changes to receipt pdf. Excluding NR in adding dynamic details field.

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/prod.txt
=> Fixing repo reference.

report-api/report-templates/invoice.html, report-api/report-templates/payment_receipt.html, report-api/report-templates/statement_report.html
*Issue #:*
https://github.com/bcgov/entity/issues/7716
=> Display '-' for empty folio number.

pay-api/src/pay_api/exceptions/__init__.py
=> Defaulting the error response if the error is not configured in DB.

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/prod.txt, pay-api/src/pay_api/models/invoice.py, pay-api/src/pay_api/models/payment_account.py, pay-api/src/pay_api/models/routing_slip.py, pay-api/src/pay_api/resources/__init__.py, pay-api/src/pay_api/resources/fas/routing_slip.py, pay-api/src/pay_api/services/fas/routing_slip.py, pay-api/src/pay_api/utils/enums.py, pay-api/src/pay_api/utils/errors.py, pay-api/src/pay_api/utils/util.py, pay-api/tests/unit/api/fas/__init__.py, pay-api/tests/unit/api/fas/test_routing_slip.py, pay-api/tests/utilities/base_test.py, queue_services/payment-reconciliations/requirements.txt, queue_services/payment-reconciliations/requirements/repo-libraries.txt
*Issue #:*
https://github.com/bcgov/entity/issues/8052
- GET and POST endpoint
=> Changes for POST and GET routing slip

pay-api/src/pay_api/schemas/schemas/payment.json, pay-api/src/pay_api/services/fas/routing_slip.py
=> Marking paymentDate as optional

pay-api/src/pay_api/models/routing_slip.py, pay-api/src/pay_api/resources/fas/routing_slip.py, pay-api/src/pay_api/services/fas/routing_slip.py, pay-api/src/pay_api/utils/enums.py, pay-api/src/pay_api/utils/errors.py, pay-api/tests/unit/api/fas/test_routing_slip.py
*Issue #:*
https://github.com/bcgov/entity/issues/7795
- PATCH endpoint for routing slip to update the status
=> Adding PATCH endpoint for routing slips

pay-api/src/pay_api/config.py, pay-api/src/pay_api/factory/payment_system_factory.py, pay-api/src/pay_api/resources/fas/routing_slip.py, pay-api/src/pay_api/utils/enums.py, pay-api/tests/unit/api/fas/test_routing_slip.py, pay-api/tests/unit/api/test_payment_request.py, pay-api/tests/unit/services/test_distribution_code.py, pay-api/tests/unit/services/test_payment_service.py, pay-api/tests/unit/services/test_payment_transaction.py
*Issue #:*
https://github.com/bcgov/entity/issues/8116
- Adding fas roles to endpoint
- Removing unused config value
=> Adding fas roles to endpoints and cleaning up some unused config.

pay-api/migrations/versions/5b1ae231f7d2_fas_table.py, pay-api/src/pay_api/services/code.py, pay-api/src/pay_api/utils/enums.py, pay-api/tests/unit/api/test_code.py
*Issue #:*
https://github.com/bcgov/entity/issues/8116
=> Adding code endpoint support for routing slip status

pay-api/migrations/versions/5b1ae231f7d2_fas_table.py
*Issue #:*
https://github.com/bcgov/entity/issues/8116
=> Adding On Hold status

report-api/report-templates/statement_report.html
*Issue #:*
https://github.com/bcgov/entity/issues/8161
Added missing bold 
=> added missing font-bold

pay-api/src/pay_api/resources/fas/routing_slip.py, pay-api/src/pay_api/utils/enums.py, pay-api/tests/unit/api/fas/test_routing_slip.py
*Issue #:*
- Adding fas_create role to endpoint
=> Adding fas_create role to endpoint

docs/docs/api_contract/pay-api-1.0.0.yaml, pay-api/src/pay_api/models/invoice.py, pay-api/src/pay_api/models/payment_account.py, pay-api/src/pay_api/resources/invoice.py, pay-api/src/pay_api/services/invoice.py, pay-api/src/pay_api/services/statement_recipients.py, pay-api/tests/unit/api/test_account.py, pay-api/tests/unit/api/test_fee.py, pay-api/tests/unit/api/test_payment_request.py, pay-api/tests/unit/api/test_receipt.py, pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/8266
- Adding a search endpoint for payment requests and including account details in response
=> 8266: Adding a search endpoint for payment requests and including account details in response

pay-api/requirements.txt, pay-api/requirements/dev.txt, pay-api/src/pay_api/models/payment_account.py, pay-api/tests/unit/api/fas/test_routing_slip.py, pay-api/tests/unit/models/test_routing_slip.py, pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/7796
1) added api test with folio search
2) added a base model test 
3) added faker so that we don't have to supply arbitrary values
=> misc tests including folio search and a model test 

pay-api/src/pay_api/models/audit.py, pay-api/src/pay_api/models/base_schema.py, pay-api/src/pay_api/models/invoice.py, pay-api/src/pay_api/models/invoice_reference.py, pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/models/payment_account.py, pay-api/src/pay_api/models/payment_transaction.py, pay-api/src/pay_api/models/routing_slip.py, pay-api/src/pay_api/schemas/schemas/purchase_history_request.json, pay-api/src/pay_api/services/invoice.py, pay-api/src/pay_api/services/payment.py, pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/services/receipt.py, pay-api/src/pay_api/services/statement.py, pay-api/src/pay_api/utils/util.py, pay-api/tests/docker/docker-compose.yml, report-api/report-templates/invoice.html, report-api/report-templates/payment_receipt.html, report-api/report-templates/statement_report.html, report-api/src/api/services/csv_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/8280
- Adding backend schema response to include UTC timezone stamp (+00:00) in response.
- Changes to report templates for consistent format
=> Changes for consistent date format in report and in backend response

pay-api/src/pay_api/services/payment.py
*Issue #:*
https://github.com/bcgov/entity/issues/8280
- Fixing format as per https://github.com/bcgov/entity/issues/8280#issuecomment-914486066
=> Fixing format in CSV as per comment in #8280

report-api/report-templates/routing_slip_report.html
*Issue #:*
https://github.com/bcgov/entity/issues/8594
=> PDF header and footer

docs/docs/api_contract/pay-api-1.0.0.yaml
=> Adding processingFees to the schema, needs to be removed later

pay-api/migrations/versions/609b98d87a72_rpt.py, pay-api/src/pay_api/services/auth.py
*Issue #:*
https://github.com/bcgov/entity/issues/8782
=> Changes for Rural Property Tax

pay-api/migrations/versions/44bd57ece7b0_ppr_filing_types.py, pay-api/src/pay_api/__init__.py, pay-api/src/pay_api/config.py, pay-api/src/pay_api/factory/payment_system_factory.py, pay-api/src/pay_api/models/invoice.py, pay-api/src/pay_api/models/payment_line_item.py, pay-api/src/pay_api/resources/account.py, pay-api/src/pay_api/resources/fas/routing_slip.py, pay-api/src/pay_api/resources/invoice.py, pay-api/src/pay_api/resources/invoice_receipt.py, pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/services/cfs_service.py, pay-api/src/pay_api/services/distribution_code.py, pay-api/src/pay_api/services/oauth_service.py, pay-api/src/pay_api/services/paybc_service.py, pay-api/src/pay_api/services/payment.py, pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/services/payment_line_item.py, pay-api/src/pay_api/services/payment_service.py, pay-api/src/pay_api/services/receipt.py, pay-api/src/pay_api/utils/logging.py
*Issue #:*
https://github.com/bcgov/entity/issues/8641
https://github.com/bcgov/entity/issues/9023
https://github.com/bcgov/entity/issues/8713
- Creating PPR new filing types
- Making fee distribution code on line item to nullable, to not query for $0 line item
- Fixing lint issues
=> Adding PPR filing types, and fixing lint errors

pay-api/migrations/versions/643790dd3334_cso.py
*Issue #:*
https://github.com/bcgov/entity/issues/9206
- CSO Codes
=> 9206: CSO Codes

pay-api/src/pay_api/services/internal_pay_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/9121
Fix for legacy routing slips not creating invoice reference
=> fix for routing slip not creating invoice_reference

pay-api/src/pay_api/services/ejv_pay_service.py, pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/services/payment_service.py, pay-api/tests/unit/api/test_payment_request.py, pay-api/tests/unit/services/test_statement_settings.py, pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/9122
=> Changes for non billable JV accounts

pay-api/migrations/versions/f74980cff974_new_error_codes.py, pay-api/src/pay_api/config.py, pay-api/src/pay_api/services/internal_pay_service.py, pay-api/src/pay_api/utils/errors.py, pay-api/tests/unit/api/test_payment_request.py, pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/9121
=> routing slip validation added

pay-api/src/pay_api/models/routing_slip.py, pay-api/src/pay_api/schemas/schemas/routing_slip_search_request.json, pay-api/tests/unit/api/fas/test_routing_slip.py, pay-api/tests/unit/api/test_payment_request.py
*Issue #:*
https://github.com/bcgov/entity/issues/9124
=> Added cheque search 

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/prod.txt, jobs/payment-jobs/services/routing_slip.py, jobs/payment-jobs/tasks/cfs_create_account_task.py, jobs/payment-jobs/tests/jobs/factory.py, jobs/payment-jobs/tests/jobs/test_cfs_create_routing_slip_account_task.py, pay-api/src/pay_api/models/routing_slip.py, pay-api/src/pay_api/services/fas/routing_slip.py, pay-api/tests/unit/services/test_routing_slip_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/9315
=> changed routing slip account creation to offline job

pay-admin/admin/__init__.py, pay-admin/admin/config.py, pay-admin/admin/keycloak.py, pay-admin/admin/views/__init__.py, pay-admin/admin/views/code.py, pay-admin/admin/views/corp_type.py, pay-admin/admin/views/distribution_code.py, pay-admin/admin/views/fee_code.py, pay-admin/admin/views/fee_schedule.py, pay-admin/admin/views/secured_view.py, pay-admin/devops/vaults.json, pay-admin/openshift/templates/pay-admin-deploy.json, pay-admin/requirements.txt, pay-admin/requirements/repo-libraries.txt, pay-admin/tests/unit/test_views.py, pay-api/src/pay_api/models/corp_type.py, pay-api/src/pay_api/models/distribution_code.py, pay-api/src/pay_api/models/fee_code.py, pay-api/src/pay_api/models/fee_schedule.py, pay-api/src/pay_api/models/filing_type.py, pay-api/src/pay_api/models/payment_account.py, pay-api/src/pay_api/services/distribution_code.py, pay-api/src/pay_api/services/fee_schedule.py
*Issue #:*
https://github.com/bcgov/entity/issues/7926
- Adding views to admin UI
=> Adding views to flask admin UI

jobs/payment-jobs/services/routing_slip.py
*Issue #:*
https://github.com/bcgov/entity/issues/9315
=> changed flush to commit since no commit follows

jobs/payment-jobs/tasks/cfs_create_account_task.py, jobs/payment-jobs/tests/jobs/test_cfs_create_account_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/9442
=> Added exception handling for wrong bank details

pay-api/src/pay_api/resources/invoice_receipt.py, pay-api/src/pay_api/services/receipt.py
*Issue #:*
https://github.com/bcgov/entity/issues/9360
=> Fixed EJV Report Generation

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/prod.txt, jobs/payment-jobs/services/routing_slip.py, jobs/payment-jobs/tasks/cfs_create_account_task.py, pay-api/src/pay_api/config.py, pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/services/cfs_service.py, pay-api/src/pay_api/services/deposit_service.py, pay-api/src/pay_api/services/online_banking_service.py, pay-api/src/pay_api/services/pad_service.py, pay-api/src/pay_api/services/paybc_service.py, pay-api/src/pay_api/services/payment_account.py, pay-api/tests/unit/services/test_bcol_service.py, pay-api/tests/unit/services/test_pad_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/9561
- changes to party name being account id
=> party name changed to account id instead of account name

pay-api/src/pay_api/services/payment_account.py, pay-api/tests/unit/api/test_account.py
=> made account update to work with partial data

docs/docs/api_contract/pay-api-1.0.0.yaml
*Issue #:*
- Fixing the API Spec to update some attributes
=> Fixing the API Spec to update some attributes

docs/docs/api_contract/pay-api-1.0.0.yaml
=> Fixing spec for CSO

docs/docs/PayBC Mocking/paybc-1.0.0.yaml, jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/prod.txt, jobs/payment-jobs/tasks/cfs_create_invoice_task.py, jobs/payment-jobs/tests/docker/docker-compose.yml, jobs/payment-jobs/tests/jobs/factory.py, jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py, pay-api/src/pay_api/models/routing_slip.py, pay-api/src/pay_api/services/cfs_service.py, pay-api/src/pay_api/services/internal_pay_service.py, pay-api/tests/unit/api/test_refund.py
*Issue #:*
https://github.com/bcgov/entity/issues/9320
=> rs invoices made to job

docs/docs/PayBC Mocking/paybc-1.0.0.yaml, jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/prod.txt, jobs/payment-jobs/tasks/cfs_create_invoice_task.py, pay-api/src/pay_api/models/receipt.py, pay-api/src/pay_api/services/cfs_service.py, pay-api/src/pay_api/services/internal_pay_service.py, pay-api/src/pay_api/utils/constants.py, pay-api/tests/unit/api/test_refund.py
*Issue #:*
https://github.com/bcgov/entity/issues/9316
=> Cancel inv cfs

jobs/payment-jobs/config.py, jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/prod.txt
=> fixed cfs_party and rebuilt

pay-api/migrations/versions/b899b44570d0_registration_filing_type.py
*Issue #:*
https://github.com/bcgov/entity/issues/9251
=> 9251: Adding SP and GP FRREG filing types

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/prod.txt, jobs/payment-jobs/tasks/cfs_create_invoice_task.py, pay-api/src/pay_api/services/cfs_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/9320
=> few tweaks in cfs integration

pay-api/migrations/versions/b336780735dc_registration_filing_type.py
*Issue #:*
https://github.com/bcgov/entity/issues/9251
=> Changes for statement of registration filing type codes

queue_services/payment-reconciliations/src/reconciliations/ejv_reconciliations.py
*Issue #:*
- Fixing JV where the distribution was always updated to stop_ejv=true
=> Fixing JV where the distribution was always updated to stop_ejv=true

pay-api/src/pay_api/schemas/schemas/statement_notification_request.json
*Issue #:*
https://github.com/bcgov/entity/issues/10049
=> fix for broken statement settings

pay-api/src/pay_api/resources/account.py, pay-api/src/pay_api/services/payment_account.py, pay-api/tests/unit/api/test_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/10256
=> Added get fee endpoint

docs/docs/api_contract/pay-api-1.0.0.yaml
=> Update spec for adding variable fee

pay-api/src/pay_api/models/payment.py, pay-api/tests/unit/api/test_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/10400
- Filtering the product code specific transaction if token contains product code
=> 10400: Restricting service accounts to only their transactions.

pay-api/src/pay_api/services/fas/routing_slip.py, pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py, pay-api/src/pay_api/utils/enums.py, pay-api/tests/unit/api/fas/test_routing_slip.py
*Issue #:*
https://github.com/bcgov/entity/issues/9381
- Add custom status to allowed list when the status if WRITE OFF REQUESTED
- Change validation to check for original status, if the action is for custom status
=> 9381: Changes for supporting custom status in allowed status list

jobs/payment-jobs/tasks/cfs_create_invoice_task.py, jobs/payment-jobs/tasks/stale_payment_task.py, pay-api/src/pay_api/services/payment_transaction.py
*Issue #:*
https://github.com/bcgov-registries/ops-support/issues/255
=> Fixing stale payment to include service unavailable failed transactions

pay-api/migrations/versions/e7fb85dbffae_fas_audit_fields.py
=> Adding FAS auditable values

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/prod.txt, jobs/payment-jobs/tasks/ap_routing_slip_refund_task.py, jobs/payment-jobs/tasks/common/cgi_ap.py
*Issue #:*
https://github.com/bcgov/entity/issues/10473
- Changes to add correct number of transaction lines in AP Job
=> Changes to add correct number of transaction lines in AP Job

jobs/payment-jobs/services/routing_slip.py, jobs/payment-jobs/tasks/routing_slip_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/10473
=> Fixing FAS token response

report-api/report-templates/payment_receipt.html
*Issue #:*
https://github.com/bcgov/entity/issues/8417
Fixed the title and labels bold font missing issue.
=> Fixed the bold font issue.

docs/docs/architecture/FAS_Intgeration.md, docs/docs/architecture/fas/cancel_transaction.svg, docs/docs/architecture/fas/cancel_transaction_partial.svg, docs/docs/architecture/fas/link.svg, docs/docs/architecture/fas/nsf.svg, docs/docs/architecture/fas/refund_approved.svg, docs/docs/architecture/fas/routing_slip.svg, docs/docs/architecture/fas/routing_slip_transaction.svg, docs/docs/architecture/fas/write_off.svg
=> FAS integration documentation

pay-api/src/pay_api/services/direct_pay_service.py, pay-api/src/pay_api/services/payment_transaction.py, pay-api/tests/unit/services/test_payment_transaction.py
=> Adding some error handling in place to avoid unwanted errors

docs/docs/api_contract/pay-api-1.0.0.yaml
=> Adding refund status to Invoice schema

pay-api/docker-entrypoint.sh, pay-api/gunicorn_config.py
=> Adding gunicorn config to docker entry point

jobs/payment-jobs/tasks/cfs_create_invoice_task.py, queue_services/payment-reconciliations/devops/vaults.json
=> Fixing reconciliation where the account got updated from PAD to DRAWDOWN after transactions are done

pay-api/src/pay_api/services/fas/routing_slip.py
*Issue #:*
https://github.com/bcgov/entity/issues/10507
- Update for Total USD column in daily report generated
=> 10507 - Total USD update for daily report generation Routing slips

pay-api/src/pay_api/services/fas/routing_slip.py, pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py, pay-api/tests/unit/api/fas/test_refund.py, pay-api/tests/unit/api/fas/test_routing_slip.py
*Issue #:*
https://github.com/bcgov/entity/issues/10575
=> FAS - Additional Role Permissions

.github/workflows/report-api-cd.yml, report-api/devops/values.dev.yaml, report-api/devops/values.prod.yaml, report-api/devops/values.test.yaml, report-api/gunicorn_config.py
*Issue #:*
Deploy report api to edb and mhr namespace.
=> Report API CD update.

pay-api/src/pay_api/services/fas/routing_slip.py, report-api/report-templates/routing_slip_report.html
*Issue #:*
https://github.com/bcgov/entity/issues/10507
- update reporting logic in routing slip service to accept null values
=> Feature/10507 report null-type fix

pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py
=> list removal issue fixed

pay-api/src/pay_api/services/fas/routing_slip.py
*Issue #:*
https://github.com/bcgov/entity/issues/10507
=> 10507 - Daily RS report fix for total USD amount  display

jobs/payment-jobs/tasks/cfs_bank_name_updater.py, jobs/payment-jobs/tasks/cfs_create_account_task.py, pay-api/src/pay_api/services/cfs_service.py
=> bank account name changed to org name

jobs/payment-jobs/requirements.txt
=> fixing dependency

jobs/payment-jobs/tasks/ap_routing_slip_refund_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/11059
=> Padding  fix ap line comment

pay-api/src/pay_api/schemas/schemas/routing_slip.json, pay-api/src/pay_api/services/fas/routing_slip.py, pay-api/tests/unit/api/fas/test_routing_slip.py, pay-api/tests/unit/api/test_payment_request.py
*Issue #:*
https://github.com/bcgov/entity/issues/11192
=> 11192 - FAS Routing slip creation validation

jobs/payment-jobs/tasks/routing_slip_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/11211
=> NSF Balance -Fix

report-api/Dockerfile, report-api/gunicorn_config.py
*Issue #:*
1. Add Microsoft fonts into application;
2. Change the timeout to 0;
=> Add ms fonts.

pay-api/src/pay_api/schemas/schemas/business_info.json
*Issue #:*
https://github.com/bcgov/entity/issues/10133
Minor tweak for schema to allow single letter corpTypes.
=> 10133 - Minor tweak for schema to allow single letter corpTypes.

jobs/payment-jobs/tasks/routing_slip_task.py, jobs/payment-jobs/tests/jobs/conftest.py, jobs/payment-jobs/tests/jobs/test_routing_slip_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/11945
Add in try catch for adjust_routing_slips job.
=> 11945 - Add in exception handling for routing slip adjustments

pay-api/migrations/README, pay-api/migrations/versions/059abb33d3c3_add_details_for_rs_cant_link_nsf.py, pay-api/tests/unit/api/fas/test_routing_slip.py
*Issue #:*
https://github.com/bcgov/entity/issues/11989
Update README.
Add in migration for rs_cant_link_nsf.
Add in unit test.
=> 11989 - FAS - Prevent linking from NSF status

pay-api/src/pay_api/models/routing_slip.py, pay-api/tests/unit/api/fas/test_routing_slip.py
*Issue #:*
https://github.com/bcgov/entity/issues/12005
Add in entity filter, with unit test.
=> 12005 - FAS Dashboard: Bugs while searching

pay-api/src/pay_api/models/routing_slip.py, pay-api/tests/unit/api/fas/test_routing_slip.py
*Issue #:*
https://github.com/bcgov/entity/issues/12005
Minor fix, don't include payment method.
=> 12005 - Minor fixes

pay-api/migrations/alembic.ini, pay-api/migrations/versions/f218f09ea2d2_add_missing_indexes_thanks_patrick.py
*Issue #:*
https://github.com/bcgov/entity/issues/12027
Add in missing indexes.
=> 12027 - Add in missing indexes.

pay-api/requirements.txt, pay-api/src/pay_api/models/routing_slip.py, pay-api/src/pay_api/resources/fas/routing_slip.py, pay-api/src/pay_api/schemas/schemas/routing_slip_search_request.json, pay-api/src/pay_api/services/fas/routing_slip.py
*Issue #:*
https://github.com/bcgov/entity/issues/12032
Add in page, limit to json body. This allows it to work with CORS. 
Change routing_slip relationships loading from eager to lazy.
Fix routing_slip_search_request.json.
=> 12032 - FAS - Performance - Query optimization

pay-api/src/pay_api/services/internal_pay_service.py, pay-api/tests/unit/services/test_payment_service.py, pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/12047 
Fix comparison between decimal and float. 
=> 12047  - Feature/fix internal pay

pay-api/src/pay_api/models/routing_slip.py, pay-api/src/pay_api/services/fas/routing_slip.py, pay-api/tests/unit/models/test_routing_slip.py
*Issue #:*
https://github.com/bcgov/entity/issues/12032
Fix the pagination and limit for search.
Fix business_identifier search.
=> 12032 - FAS - Performance - Query optimization 

pay-api/migrations/versions/175c11863186_fix_rs_cant_link_nsf_description.py
https://github.com/bcgov/entity/issues/11989
=> 11989 - Migration to fix error message.

pay-api/src/pay_api/services/fee_schedule.py, pay-api/src/pay_api/services/internal_pay_service.py, pay-api/src/pay_api/utils/util.py, pay-api/tests/unit/api/test_fee.py
*Issue #:*
https://github.com/bcgov/entity/issues/12050
https://github.com/bcgov/entity/issues/12047
Adjust quantity calculation, so it rounds.
=> 12050/12047 - FAS - Incorrectly saying balance is less than transaction amount

pay-api/src/pay_api/models/invoice.py, pay-api/src/pay_api/utils/constants.py, report-api/report-templates/payment_receipt.html
*Issue #:*
https://github.com/bcgov/entity/issues/11527
Minor changes to invoice.py, constants, payment_receipt.html.
=> 11527 - Receipt updates needed for SP/GP Registration

pay-api/src/pay_api/services/payment.py, pay-api/tests/unit/services/test_payment.py
*Issue #:*
https://github.com/bcgov/entity/issues/11924
Move status_code -> status_code_description while maintaining the original status_code.
=> 11924 - API - Status ENUM not following spec

pay-api/src/pay_api/resources/account.py, pay-api/src/pay_api/services/payment.py, pay-api/tests/unit/services/test_payment.py
*Issue #:*
https://github.com/bcgov/entity/issues/11924
Remove status_code_description, it's only used internally.
=> 11924 - Remove status_code_description, it's only used internally.

pay-api/src/pay_api/services/payment_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/12316
Add missing if condition for invoice_reference.
=> 12316 - Add missing if condition for invoice_reference.

jobs/payment-jobs/setup.cfg, jobs/payment-jobs/tasks/ejv_payment_task.py, pay-admin/setup.cfg, pay-api/setup.cfg, pay-api/src/pay_api/exceptions/__init__.py, pay-api/src/pay_api/models/base_schema.py, pay-api/src/pay_api/models/invoice.py, pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/services/bcol_service.py, pay-api/src/pay_api/services/ejv_pay_service.py, pay-api/src/pay_api/services/internal_pay_service.py, pay-api/src/pay_api/services/payment_line_item.py, pay-api/src/pay_api/version.py, queue_services/events-listener/requirements/prod.txt, queue_services/events-listener/setup.cfg, queue_services/payment-reconciliations/requirements/prod.txt, queue_services/payment-reconciliations/setup.cfg
=> 12443 - EJV Job fixes - Payment

pay-api/src/pay_api/utils/util.py
=> 12320 - Small fix for unit tests failing on sunday.

jobs/payment-jobs/tasks/ejv_payment_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/12443
=> 12443 - More EJV job fixes.

jobs/payment-jobs/tasks/common/cgi_ap.py, pay-api/src/pay_api/services/fas/routing_slip.py
=> 12835 - Fix daily report cheque numbers.

jobs/payment-jobs/tasks/cfs_create_invoice_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/11777
Send over invoice date through queues. 
=> 11777 - Fixes for invoice date being incorrect when queue is backed up

jobs/payment-jobs/config.py, jobs/payment-jobs/tasks/common/cgi_ejv.py
*Issue #:*
https://github.com/bcgov/entity/issues/12443
Add in CGI_EJV_SUPPLIER_NUMBER
=> 12443 - Fix ejv supplier number

pay-api/migrations/versions/59fc9d74101f_error_messages_p2.py
https://github.com/bcgov/entity/issues/11991
Missed a few. 
=> 11991 - More error messages for cleanup.

queue_services/payment-reconciliations/requirements/dev.txt, queue_services/payment-reconciliations/src/reconciliations/cgi_reconciliations.py, queue_services/payment-reconciliations/src/reconciliations/config.py
=> Ejv email fix

.github/workflows/payment-reconciliations-ci.yml, queue_services/events-listener/requirements/dev.txt, queue_services/payment-reconciliations/src/reconciliations/cgi_reconciliations.py, queue_services/payment-reconciliations/src/reconciliations/config.py
Fix to skip over AP_REFUNDS for now (they all fail)
=> Fix to skip over AP_REFUNDS for now (they all fail)

jobs/payment-jobs/invoke_jobs.py, jobs/payment-jobs/run_direct_pay_automated_refunds.sh, jobs/payment-jobs/tasks/direct_pay_automated_refund_task.py
=> 13157 - Small job changes

docs/docs/api_contract/pay-api-1.0.1.yaml
A developer at CSO after doing some BCOL testing we noticed this field shows up in invoice.
=> Minor change to add in bcolAccount field to invoice.

pay-api/src/pay_api/services/auth.py, pay-api/src/pay_api/utils/enums.py, pay-api/src/pay_api/version.py, queue_services/payment-reconciliations/logging.conf, queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py, queue_services/payment-reconciliations/src/reconciliations/version.py
Update logging file
Minor bug fixes
Version updates
Pay permission fixes
=> Update logging file + minor fixes + minor pay permission fix

pay-api/devops/vaults.json
*Issue #: N/A*
https://github.com/bcgov/entity/issues/<N/A>
- removed `launchdarkly` from ` vault: "relationships" `
- added lanchdarkly entry into vault.json. 
=> Launchdarkly vault.json fix

jobs/payment-jobs/config.py, jobs/payment-jobs/devops/vaults.json, jobs/payment-jobs/invoke_jobs.py, jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/prod.txt, queue_services/events-listener/devops/vaults.json, queue_services/events-listener/requirements.txt, queue_services/events-listener/requirements/prod.txt, queue_services/events-listener/src/events_listener/config.py, queue_services/events-listener/src/events_listener/worker.py, queue_services/payment-reconciliations/devops/vaults.json, queue_services/payment-reconciliations/requirements.txt, queue_services/payment-reconciliations/requirements/prod.txt, queue_services/payment-reconciliations/src/reconciliations/config.py, queue_services/payment-reconciliations/src/reconciliations/worker.py
*Issue #: 13611*
- imported and initialized LD flag service from `pay-api` into payment-reconciliations and events-listener in queue_service
- imported and initialized LD flag service into invoke_jobs in `\jobs\payment-jobs`
- updated requirements and vaults as required
=> 13611  - added LD flag service to queue services and payment jobs

jobs/payment-jobs/tasks/cfs_create_invoice_task.py, queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
Issue #: https://github.com/bcgov/entity/issues/14055
Pay job logging fix, also payment reconciliation fix
=> 14055 - Pay job logging fix, also payment reconciliation

pay-api/src/pay_api/services/fee_schedule.py
*Issue #:*
https://github.com/bcgov/entity/issues/14180
Pending a business decision from John. 
=> 14180 - Reverse CSO specific changes for service_fees.

pay-api/src/pay_api/services/fee_schedule.py
=> Revert "14180 - Reverse CSO specific changes for service_fees."

pay-api/src/pay_api/models/account_fee.py, pay-api/src/pay_api/models/base_schema.py, pay-api/src/pay_api/models/cfs_account.py, pay-api/src/pay_api/models/distribution_code.py, pay-api/src/pay_api/models/payment_account.py, pay-api/src/pay_api/version.py
This is to facilitate being able to use jupyter notebooks with SBC-AUTH and SBC-PAY at the same time.
=> Add dynamic exclusion of versions field, similar to SBC-AUTH.

jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/12756
=> speed up partner distribution task

docs/docs/api_contract/pay-api-1.0.3.yaml, pay-api/migrations/versions/833b83dc67ac_new_invoice_statuses.py, pay-api/src/pay_api/config.py, pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/services/direct_pay_service.py, pay-api/src/pay_api/services/online_banking_service.py, pay-api/src/pay_api/services/pad_service.py, pay-api/src/pay_api/services/paybc_service.py, pay-api/src/pay_api/utils/enums.py, pay-api/src/pay_api/version.py, pay-api/tests/unit/api/test_refund.py, pay-api/tests/unit/services/test_direct_pay_service.py, pay-api/tests/unit/services/test_refund.py
*Issue #:*
https://github.com/bcgov/entity/issues/14382
Add in two new invoice statuses - We'll need to communicate this out to partners
=> 14382 - Changes for new invoice status codes: CREDITED and CANCELLED.

pay-api/src/pay_api/services/fee_schedule.py, pay-api/tests/unit/api/test_payment_request.py
*Issue #:*
https://github.com/bcgov/entity/issues/14180
Don't set _waived_fee_amount on variable fees.
=> 14180 - Don't set waived fee amount on variable fees

pay-api/requirements/dev.txt, report-api/report-templates/statement_report.html, report-api/requirements/dev.txt
*Issue #:*
https://github.com/bcgov/entity/issues/14107
Fixed the css
=> Bug 14107 Statements have footer rendered on top of the content

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/bcregistry-libraries.txt
*Issue #:*
https://github.com/bcgov/entity/issues/14381
=> 14381 bcol refund confirmation 2

.github/CODEOWNERS, .github/workflows/bcol-api-cd.yml, .github/workflows/bcol-api-ci.yml, .github/workflows/events-listener-cd.yml, .github/workflows/events-listener-ci.yml, .github/workflows/ftp-poller-cd.yml, .github/workflows/ftp-poller-ci.yml, .github/workflows/pay-admin-cd.yml, .github/workflows/pay-admin-ci.yml, .github/workflows/pay-api-cd.yml, .github/workflows/pay-api-ci.yml, .github/workflows/payment-jobs-cd.yml, .github/workflows/payment-jobs-ci.yml, .github/workflows/payment-reconciliations-cd.yml, .github/workflows/payment-reconciliations-ci.yml, .github/workflows/ppr-report-api-cd.yml, .github/workflows/pr-label-check.yml, .github/workflows/report-api-cd.yml, .github/workflows/report-api-ci.yml
*Issue #:*
https://github.com/bcgov/entity/issues/14257
=> Update github workflows, so we don't run into codecov errors.

jobs/payment-jobs/Dockerfile
*Issue #:*
https://github.com/bcgov/entity/issues/14381
needed for oracle connection
=> add oracle stuff to dockerfile

jobs/payment-jobs/requirements.txt, pay-api/src/pay_api/services/cfs_service.py, pay-api/src/pay_api/utils/enums.py
=> Update payment jobs deps.

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/tests/jobs/test_routing_slip_task.py, pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/services/bcol_service.py, pay-api/src/pay_api/services/fee_schedule.py, pay-api/src/pay_api/services/flags.py, pay-api/tests/unit/services/test_flags.py
=> Fix rs jobs - fix flags

jobs/payment-jobs/requirements.txt
=> Repoint requirements.txt to latest main.

jobs/payment-jobs/tasks/bcol_refund_confirmation_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/14381
=> allow job to run with more than 1000 records to update

pay-api/src/pay_api/utils/enums.py
*Issue #14346:*
https://github.com/bcgov/entity/issues/14346
update CfsReceiptStatus
=> 14346 - update CfsReceiptStatus

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/tasks/routing_slip_task.py, jobs/payment-jobs/tests/jobs/test_routing_slip_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/14346
=> 14346 add receipt status check before sending reverse request

docs/docs/database/bca_monthly_invoices.sql
*Issue #:*
https://github.com/bcgov/entity/issues/14507
added a column of FOILO and change FEE CODE to PRODUCT CODE
=> 14507 - added a column of FOILO and change FEE CODE to PRODUCT CODE

docs/docs/database/bca_monthly_invoices.sql
*Issue #:*
https://github.com/bcgov/entity/issues/14507
Convert date from  UTC to PDT/PST
=> 14507 - Convert UTC to PDT/PST

pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py
*Issue [#14168:*](https://github.com/bcgov/entity/issues/14618)
add CORRECTION.value to RoutingSlipStatus
=> 14618 - add CORRECTION.value to RoutingSlipStatus

pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/utils/enums.py
Skip sending queue messages for CSO payments.
=> Skip over sending queue message for CSO payments.

pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/services/payment_transaction.py, pay-api/src/pay_api/utils/enums.py
=> Skip over certain corp types for queue messages.

.github/workflows/notebook-report-cd.yml
Signed-off-by: Steven Chen <steven.chen@gov.bc.ca>
*Issue #:*  #14945
Removed Rollout section from CD file
=> Create job to schedule reports - invoice reconciliation #14945

pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/schemas/schemas/purchase_history_request.json, pay-api/src/pay_api/version.py, pay-api/tests/unit/services/test_payment.py, pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/14376
- still need to update tests
=> backend updates for transaction table

pay-api/src/pay_api/services/fas/routing_slip.py
=> Missing str for decimal

pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/resources/account.py, pay-api/src/pay_api/services/auth.py, pay-api/src/pay_api/services/payment.py, pay-api/src/pay_api/utils/constants.py, pay-api/src/pay_api/utils/enums.py, pay-api/tests/unit/api/test_account.py, pay-api/tests/unit/services/test_payment.py, pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/14377
cleanup and tests still needed
=> enhancements added to transactions history

pay-api/src/pay_api/services/payment_service.py
=> Fix null details.

pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py
=> Add transistion to complete.

jobs/payment-jobs/tasks/routing_slip_task.py, pay-api/src/pay_api/exceptions/__init__.py, pay-api/src/pay_api/resources/payment.py, pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/services/cfs_service.py, pay-api/src/pay_api/services/fas/routing_slip.py, pay-api/src/pay_api/services/invoice.py, pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/services/payment_service.py, queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py, queue_services/payment-reconciliations/src/reconciliations/worker.py
=> Fix lint errors.

pay-api/src/pay_api/services/fas/routing_slip.py, pay-api/tests/unit/api/fas/test_routing_slip.py
Description:
Found a weird case where the CFS account isn't created (Haven't created routing slip and waited 5 minutes). 
=> Fix rs correction api

queue_services/payment-reconciliations/src/reconciliations/cgi_reconciliations.py, queue_services/payment-reconciliations/src/reconciliations/config.py
=> Enable the AP refund reconciliation always.

pay-db/test-data-load/test-data-cleanup.sql, pay-db/test-data-load/test-data-load.sql
*Issue #:*
https://github.com/bcgov/entity/issues/15276
Add in SQL to load in test data for pay.
=> 15276 - Add in SQL to load in test data for pay.

jobs/payment-jobs/tasks/activate_pad_account_task.py, pay-api/src/pay_api/models/payment.py
=> Sorting fix + pad activation date fix.

jobs/payment-jobs/tasks/bcol_refund_confirmation_task.py
=> bcol refund fix float/decimal conversion

docs/docs/api_contract/pay-api-1.0.3.yaml
=> add in additionalProperties for Invoice object.

pay-api/src/pay_api/resources/account.py
*Issue #14850:*
https://github.com/bcgov/entity/issues/14850
=> 14850 - allow basic accounts access to transaction route

pay-api/src/pay_api/resources/account.py, pay-api/tests/unit/api/test_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/14850
=> 14850 - Unit test for basic account - transaction screen

pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/services/bcol_service.py, pay-api/src/pay_api/services/payment.py
Will be adding in a unit test in my other PR.
=> Fix for BCOL + missing fields.

docs/docs/api_contract/pay-api-1.0.3.yaml
=> Fix additionalProperties.

jobs/payment-jobs/tasks/direct_pay_automated_refund_task.py, jobs/payment-jobs/tests/jobs/test_direct_pay_automated_refund_task.py
=> Remove time check in task, just do this via CRONTAB instead.

pay-api/src/pay_api/models/payment_account.py
=> Change auth_account_id to accountId..

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/tasks/statement_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/15467 
=> 15467 - Revert requirements.txt.

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/tasks/ap_task.py, jobs/payment-jobs/tasks/common/cgi_ap.py, jobs/payment-jobs/tasks/common/dataclasses.py, jobs/payment-jobs/tasks/statement_task.py, pay-api/src/pay_api/utils/util.py
=> AP disbursement changes + statement tweak.

queue_services/payment-reconciliations/src/reconciliations/cgi_reconciliations.py
=> Add in line to print out invoice id.

bcol-api/src/bcol_api/resources/bcol_payment.py, bcol-api/src/bcol_api/services/bcol_payment.py, bcol-api/tests/conftest.py, bcol-api/tests/unit/services/test_bcol_payment.py, pay-api/migrations/versions/2023_03_21_33bbd4d9a85c_.py, pay-api/src/pay_api/models/corp_type.py, pay-api/src/pay_api/models/fee_schedule.py, pay-api/src/pay_api/services/bcol_service.py, pay-api/tests/unit/services/test_bcol_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/15699
This needs to be tied to the next auth release as well. AUTH-WEB allows $1.05, $0 (ESRA), $1.50, $1.00, $0 (everything else)
=> 15699 - Changes to accomodate 3 tiers of service fees in BCOL.

bcol-api/src/bcol_api/services/bcol_payment.py, bcol-api/tests/unit/api/test_bcol_payment.py
=> Cast to float

pay-admin/admin/views/corp_type.py
=> New columns for pay-admin.

jobs/payment-jobs/requirements.txt
=> PAY-JOBS - Use the latest version of pay-api.

jobs/payment-jobs/tasks/ejv_partner_distribution_task.py, jobs/payment-jobs/tasks/ejv_payment_task.py, jobs/payment-jobs/tests/jobs/test_ejv_payment_task.py, jobs/payment-jobs/utils/date.py
=> Add in weekend check for CGI feeders.

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/prod.txt
=> Update requirements for jobs.

pay-api/src/pay_api/services/bcol_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/16458
=> 16458 - cast service_fee

jobs/payment-jobs/requirements.txt, queue_services/payment-reconciliations/requirements.txt
=> update requirements dependency for pay-api

report-api/report-templates/invoice.html, report-api/report-templates/payment_receipt.html, report-api/report-templates/routing_slip_report.html
*Issue #:*
https://github.com/bcgov/entity/issues/17477
eg. routing_slip payment report
=> 17477 - documents footer fix

docs/docs/api_contract/pay-api-1.0.4.yaml, jobs/payment-jobs/tests/docker/docker-compose.yml, pay-api/tests/docker/docker-compose.yml
=> Update and rename pay-api-1.0.3.yaml to pay-api-1.0.4.yaml

pay-api/src/pay_api/services/statement.py
=> Fix conditional check for oldest_overdue_date

pay-api/migrations/versions/2023_09_28_456234145e5e_eft_processing.py, pay-api/src/pay_api/models/__init__.py, pay-api/src/pay_api/models/eft_file.py, pay-api/src/pay_api/models/eft_process_status_code.py, pay-api/src/pay_api/models/eft_transaction.py, pay-api/src/pay_api/utils/enums.py, pay-api/tests/unit/models/test_eft_file.py, pay-api/tests/unit/models/test_eft_transaction.py
*Issue #:*
https://github.com/bcgov/entity/issues/17828
- initial EFT File processing models for TDI17
=> 17828 - initial EFT file processing models

pay-api/src/pay_api/models/payment.py
=> Add in the two dates that were missing.

pay-api/src/pay_api/services/payment.py
https://github.com/bcgov/entity/issues/17836
Added the Transaction ID column to the csv export 
=> 17836 - pay api transaction id

jobs/payment-jobs/flags.json, jobs/payment-jobs/requirements.txt, jobs/payment-jobs/requirements/dev.txt, jobs/payment-jobs/tasks/statement_notification_task.py, jobs/payment-jobs/tests/jobs/factory.py, jobs/payment-jobs/tests/jobs/test_statement_notification_task.py, jobs/payment-jobs/tests/services/test_flags.py, jobs/payment-jobs/utils/mailer.py
*Issue #:*
https://github.com/bcgov/entity/issues/17831
- Update logic to publish new statement notification for EFT
- Add feature flag logic to enable EFT processing
- Add basic feature flag tests
- Add statement notification tests for previous and new logic 
- Add publish to mailer helper (previous template is within payment jobs)
=> 17831 - EFT Monthly Statement

jobs/payment-jobs/requirements.txt
=> payment-jobs - sbc-pay dependency hash update

docs/docs/PayBC Mocking/paybc-1.0.0.yaml, jobs/payment-jobs/tasks/common/dataclasses.py, jobs/payment-jobs/tasks/common/enums.py, jobs/payment-jobs/tasks/direct_pay_automated_refund_task.py, jobs/payment-jobs/tasks/distribution_task.py, jobs/payment-jobs/tests/jobs/test_direct_pay_automated_refund_task.py, pay-api/src/pay_api/services/direct_pay_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/18012
=> 18012 - Minimum changes for new PayBC partial refunds.

pay-api/src/pay_api/services/payment_account.py
=> Minor tweak for enable_eft.

jobs/payment-jobs/tasks/cfs_create_invoice_task.py
=> Fix error logging for payment jobs.

report-api/report-templates/invoice.html
*Issue #:*
https://github.com/bcgov/entity/issues/18423
- Updated report-api based on the newly defined requirement for cfs account number description
=> 18423 - REPORT-API CFS New Requirement Update

jobs/payment-jobs/requirements.txt
*Issue #:*
https://github.com/bcgov/entity/issues/18767
=> 18767 - Update requirements.txt for payment-jobs

jobs/payment-jobs/requirements.txt
=> Update sbc-pay reference in payment-jobs.

jobs/notebook-report/Dockerfile
=> Dockerfile config update

jobs/notebook-report/README.md, jobs/notebook-report/notebookreport.py, jobs/notebook-report/openshift/templates/cronjob.yaml
*Issue #:*
https://github.com/bcgov/entity/issues/18758
=> 18758 - update readme, fix weekly report issue, update cronjob.yaml

queue_services/payment-reconciliations/src/reconciliations/cgi_reconciliations.py
=> Add in credited for disbursement_status

queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
=> Add in lines that checks for CC invoices.

pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/models/statement.py, pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/services/statement.py, pay-api/src/pay_api/utils/util.py, pay-api/src/pay_api/version.py, pay-api/tests/unit/services/test_statement.py
*Issue #:*
https://github.com/bcgov/entity/issues/18493
- add payment methods based on payment account history per statement
- add invoice for statement additional filtering to support payment job updates for generating statements
- logic to generate interim statement when switching to EFT payment method
=> 18493 - EFT Statement updates

jobs/payment-jobs/requirements.txt, jobs/payment-jobs/tasks/statement_task.py, jobs/payment-jobs/tests/jobs/factory.py, jobs/payment-jobs/tests/jobs/test_generate_statements.py, jobs/payment-jobs/tests/jobs/test_statement_due_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/18493
- handle interim statement logic
- tests to confirm statements are properly generated even with an interim statement
=> 18493 - Update EFT statement generation

report-api/report-templates/eft_instructions.html
*Issue #:18014 *
https://github.com/bcgov/entity/issues/18014
=> 18014 - Update eft instructions

pay-api/migrations/versions/2023_12_05_b65365f7852b_.py
=> Fix migration revision

queue_services/payment-reconciliations/requirements.txt, queue_services/payment-reconciliations/src/reconciliations/eft/eft_base.py, queue_services/payment-reconciliations/src/reconciliations/eft/eft_reconciliation.py, queue_services/payment-reconciliations/src/reconciliations/version.py, queue_services/payment-reconciliations/tests/integration/test_eft_reconciliation.py
*Issue #:*
https://github.com/bcgov/entity/issues/18681
- improve tracking of credits to TDI17 transaction
- change credits to per transaction rather than rolling it up for improved traceability
- update tests to check against transaction ids and new invoice links table is populated for invoice_ids that credits are applied to
=> 18681 - Update EFT TDI17 processing logic

queue_services/payment-reconciliations/requirements.txt, queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
*Issue #:17534*
https://github.com/bcgov/entity/issues/17534
=> 17534- Reconciliation tweaks

jobs/payment-jobs/config.py, jobs/payment-jobs/invoke_jobs.py, jobs/payment-jobs/requirements.txt, jobs/payment-jobs/run_eft_transfer_task.sh, jobs/payment-jobs/tasks/eft_transfer_task.py, jobs/payment-jobs/tests/jobs/factory.py, jobs/payment-jobs/tests/jobs/test_eft_transfer_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/18681
- Create EFT Transfer Task job to transfer funds from EFT Holding GL to invoice line item distribution GL
=> 18681 - EFT Transfer task job

pay-api/src/pay_api/services/non_sufficient_funds.py
=> 16467 - NSF Calculation Fixes and PDF Download

pay-api/src/pay_api/models/routing_slip.py, pay-api/tests/unit/api/fas/test_refund.py
*Issue #:*
https://github.com/bcgov/entity/issues/19222
=> 19222 - Add other refund states to get routing slip route

pay-api/src/pay_api/resources/v1/eft_short_names.py, pay-api/src/pay_api/utils/enums.py, pay-api/tests/unit/api/test_eft_short_names.py, pay-api/tests/unit/api/test_eft_transactions.py
*Issue #:*
https://github.com/bcgov/entity/issues/19673
=> 19673 - Create eft_staff role to access EFT shortname functionality

pay-api/src/pay_api/models/invoice.py
=> Add in branch_name

pay-api/src/pay_api/models/__init__.py, pay-api/src/pay_api/resources/v1/account.py, pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/version.py, pay-api/tests/conftest.py, pay-api/tests/unit/api/test_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/19803
=> 19803 - Changes to search, to exclude inactive org ids

pay-api/src/pay_api/services/direct_pay_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/19759 
=> 19759 - Changes after testing with PAYBC

queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
*Issue #:19929*
https://github.com/bcgov/entity/issues/19929
=> 19929 - Checking for failed payments in NSF reconciliation flow

bcol-api/src/bcol_api/services/bcol_payment.py
=> Add in invoice number to logging

pay-api/src/pay_api/services/refund.py, pay-api/tests/unit/api/test_partial_refund.py
=> Add in feature flag for partial refunds

pay-api/src/pay_api/models/invoice.py, pay-api/src/pay_api/services/invoice.py, pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/services/payment_transaction.py, pay-api/src/pay_api/services/receipt.py, pay-api/tests/unit/services/test_payment_transaction.py, report-api/report-templates/non_sufficient_funds.html
*Issue #:*
https://github.com/bcgov/entity/issues/20037
=> 20037 - Fix NSF unlock receipt

pay-api/src/pay_api/services/receipt.py
=> Add in initializer for details

pay-api/migrations/versions/2024_02_28_bacb2b859d78_partial_refund_disbursement.py, pay-api/src/pay_api/models/refunds_partial.py
*Issue #:*
https://github.com/bcgov/entity/issues/19875
=> 19875 - Add Disbursement to refunds_partial

pay-api/manage.py, pay-api/wsgi.py
*Issue #:*
https://github.com/bcgov/entity/issues/19875
=> 19875 - Pay Migration bug fix

jobs/payment-jobs/tasks/cfs_create_account_task.py, pay-api/src/pay_api/services/eft_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/19724
=> 19724_2 - EFT - Create CFS account job 

.github/workflows/pay-api-cd-gcp.yml
=> Add pay api gcp CD flow.

jobs/payment-jobs/devops/gcp/clouddeploy-targets.yaml
=> Feature queue python upgrade

jobs/notebook-report/daily/vs_reconciliation_details.ipynb, jobs/notebook-report/monthly/vs_reconciliation_summary.ipynb
*Issue #:*
https://github.com/bcgov/entity/issues/20607
=> 20607 - Add in TZ conversion

.github/workflows/pay-api-cd-gcp.yml, jobs/notebook-report/daily/vs_reconciliation_details.ipynb, jobs/notebook-report/monthly/vs_reconciliation_summary.ipynb, report-api/requirements.txt
=> Sync from main

pay-api/src/pay_api/services/__init__.py
*Issue #:*
https://github.com/bcgov/entity/issues/19723
=> 19723 - Exposing eft short names service

jobs/payment-jobs/invoke_jobs.py, jobs/payment-jobs/poetry.lock, jobs/payment-jobs/tasks/electronic_funds_transfer_task.py, jobs/payment-jobs/tests/jobs/factory.py, jobs/payment-jobs/tests/jobs/test_electronic_funds_transfer_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/Linking EFTs
=> 19723 - Linking EFT Job

pay-api/src/pay_api/models/__init__.py, pay-api/src/pay_api/models/eft_short_names.py, pay-api/src/pay_api/resources/v1/eft_short_names.py, pay-api/src/pay_api/services/__init__.py, pay-api/src/pay_api/services/eft_short_name_summaries.py, pay-api/src/pay_api/services/eft_short_names.py, pay-api/src/pay_api/utils/util.py, pay-api/src/pay_api/version.py, pay-api/tests/unit/api/test_cors_preflight.py, pay-api/tests/unit/api/test_eft_short_names.py
*Issue #:*
https://github.com/bcgov/entity/issues/20414
- new route for eft short name summary search to support new UI table
=> 20414 - EFT Short name summaries search

pay-api/src/pay_api/models/eft_short_names.py, pay-api/src/pay_api/resources/v1/eft_short_names.py, pay-api/src/pay_api/services/eft_short_names.py, pay-api/src/pay_api/version.py, pay-api/tests/unit/api/test_eft_short_names.py
*Issue #:*
https://github.com/bcgov/entity/issues/20420
- refactor for EFT Enabled Accounts Table search
- clean up params / schema
=> 20420 - EFT Short name search

.github/workflows/bcol-api-ci.yml, .github/workflows/ftp-poller-ci.yml, .github/workflows/notebook-report-ci.yml, .github/workflows/pay-admin-ci.yml, .github/workflows/pay-api-ci.yml, .github/workflows/pay-queue-ci.yml, .github/workflows/payment-jobs-ci.yml, .github/workflows/report-api-ci.yml, pay-api/migrations/versions/2024_05_07_4b3bd37727a5_20417_eft_credit_invoice_links.py, pay-api/src/pay_api/models/eft_credit_invoice_link.py, pay-api/src/pay_api/models/eft_short_name_links.py, pay-api/src/pay_api/models/eft_transaction.py, pay-api/src/pay_api/resources/v1/eft_short_names.py, pay-api/src/pay_api/services/eft_short_name_summaries.py, pay-api/src/pay_api/services/eft_short_names.py, pay-api/src/pay_api/services/eft_transactions.py, pay-api/src/pay_api/utils/enums.py, pay-api/src/pay_api/version.py, pay-api/tests/unit/api/test_eft_short_names.py, pay-api/tests/unit/api/test_eft_transactions.py, pay-api/tests/unit/models/test_eft_credit_invoice_link.py
*Issue #:*
https://github.com/bcgov/entity/issues/20417
- Implement EFT link search
- Refactor EFT transactions search (funds received union with funds applied)
- Updates to EFT credit invoice link model. We needed to capture the status so we can have pending payments and the amount of credit the link is pulling so it can be used for calculate the owing amount even when payments are pending.
=> 20417 - EFT Shortname links / transaction search

pay-api/src/pay_api/utils/enums.py, pay-api/src/pay_api/utils/util.py, pay-queue/src/pay_queue/__init__.py
Use this when determining a topic:
=> Read from cache for corp_types. Add in cache to pay-queue.

pay-api/src/pay_api/version.py
=> 21472 - update sbc-pay version for release 1.21.0

report-api/Makefile, report-api/requirements.txt, report-api/requirements/prod.txt, report-api/requirements/repo-libraries.txt
*Issue #:*
https://github.com/bcgov/entity/issues/21584 
=> 21584 - REPORT-API - Cleanup deps

pay-api/src/pay_api/services/payment_account.py, pay-api/tests/unit/services/test_statement.py
*Issue #:*
https://github.com/bcgov/entity/issues/20719
=> 20719 - Add interim statement logic when change payment away from EFT

pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/services/payment_transaction.py
*Issue #:*
https://github.com/bcgov/entity/issues/20088
Updating unlock_frozen_accounts to take in payment_id and payment_account_id for EFT unlocking
=> 20088 - Updating unlock_frozen_accounts to take in payment_id and payment_account_id

jobs/payment-jobs/poetry.lock, jobs/payment-jobs/pyproject.toml, jobs/payment-jobs/tasks/common/dataclasses.py, jobs/payment-jobs/tasks/ejv_partner_distribution_task.py, pay-api/src/pay_api/services/refund.py, pay-api/tests/unit/services/test_refund.py, pay-queue/src/pay_queue/services/cgi_reconciliations.py
*Issue #:*
https://github.com/bcgov/entity/issues/21676
=> 21676 - Add in credits for is_reversal also add in refund_date

pay-queue/src/pay_queue/services/payment_reconciliations.py
=> Small fix for reconciliation, return statement was nuked

pay-api/tests/docker/docker-compose-arm64.yml
=> Create a docker-compose file for Arm64 testing

pay-queue/Dockerfile, pay-queue/gunicorn_config.py
=> Add in gunicorn_config also don't use werkzeug

bcol-api/Dockerfile, pay-admin/Dockerfile
=> Small fixes for pods

pay-queue/src/pay_queue/resources/worker.py
=> Logging tweak to include exception

report-api/report-templates/eft/eft_statement_details.html, report-api/report-templates/eft/eft_statement_transactions.html
*Issue #:*
https://github.com/bcgov/entity/issues/20719
- EFT template fix when there is no previous statement payment date available
=> 20719 - EFT Statement Template Fixes

jobs/payment-jobs/tasks/common/dataclasses.py, jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
=> Include Credited invoices for is_reversal

DEVELOPER_NOTES.md
Minor update to developer notes
=> 20719 - Update DEVELOPER_NOTES.md to include new auth account id

jobs/payment-jobs/tasks/cfs_create_invoice_task.py
=> Fix sqlalchemy warning

bcol-api/Makefile, jobs/ftp-poller/Makefile, jobs/payment-jobs/Makefile, pay-admin/Makefile, pay-api/Makefile, pay-queue/Makefile
=> Small fix for dev .env

pay-api/migrations/versions/b6e28faea978_rename_tables_to_plurals.py
=> Fix warning for migration

pay-api/src/pay_api/services/refund.py
*Issue #:*
https://github.com/bcgov/entity/issues/22081
=> 22081 - Refund issue - possible request can be None

.github/workflows/bcol-api-ci.yml, .github/workflows/ftp-poller-ci.yml, .github/workflows/notebook-report-ci.yml, .github/workflows/pay-admin-ci.yml, .github/workflows/pay-api-ci.yml, .github/workflows/pay-queue-ci.yml, .github/workflows/payment-jobs-ci.yml
=> Update setup-python in CI

pay-api/src/pay_api/services/eft_short_names.py, pay-api/src/pay_api/services/statement.py
=> Small fix for sqlalchemy warnings

jobs/payment-jobs/poetry.lock, pay-api/src/pay_api/models/base_model.py, pay-api/src/pay_api/models/statement.py, pay-api/src/pay_api/services/payment_account.py, pay-queue/poetry.lock
=> Warning fixes, update deps

.gitignore, pay-admin/admin/__init__.py, pay-admin/admin/config.py, pay-admin/admin/keycloak.py, pay-admin/admin/views/secured_view.py, pay-admin/poetry.lock, pay-admin/pyproject.toml
=> PAY-ADMIN - Fix for issues with cookies, also fix OIDC so it uses JWKS etc.

pay-admin/Dockerfile, pay-admin/admin/__init__.py, pay-admin/admin/config.py
=> PAY-ADMIN - Docker fixes

pay-queue/src/pay_queue/services/payment_reconciliations.py
*Issue #:*
https://github.com/bcgov/entity/issues/19513
=> 19513 - Fix - can't locate env variable IT_OPS_EMAIL on dev

pay-api/src/pay_api/services/payment_account.py
=> Set pad_cfs_account to INACTIVE on PENDING/PENDING_PAD_ACTIVATION

pay-api/src/pay_api/config.py, pay-api/src/pay_api/services/bcol_service.py
=> Minor tweak to BCOL-API, extra slash doesn't work

jobs/notebook-report/config.py, jobs/notebook-report/notebookreport.py
*Issue #21622*
https://github.com/bcgov/entity/issues/21622
=> 21622 - adding partners

pay-api/src/pay_api/__init__.py
=> Fix migration logging

.github/workflows/pay-queue-ci.yml
*Issue #:*
https://github.com/bcgov/entity/issues/19513
=> 19513 - Pay-queue yml file missing env

pay-queue/src/pay_queue/services/payment_reconciliations.py, pay-queue/src/pay_queue/templates/payment_reconciliation_failed_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/19513
=> 19513 - Add more error catching for csv feedback reconciliation

pay-queue/devops/vaults.json
*Issue #:*
https://github.com/bcgov/entity/issues/
=> Add keycloak vault to pay queue

pay-queue/devops/vaults.json
*Issue #:*
https://github.com/bcgov/entity/issues/
=> Add entity vault to pay queue

pay-queue/devops/vaults.json
=> 19513 - Add "api-points" to shared vault

pay-queue/src/pay_queue/services/payment_reconciliations.py
*Issue #:*
https://github.com/bcgov/entity/issues/19513
=> 19513 - Add traceback to csv feedback process error handling

pay-api/migrations/versions/2024_07_12_f921d5e32835_add_expense_authority_email.py, pay-api/migrations/versions/2024_07_22_f9c15c7f29f5_.py, pay-api/src/pay_api/models/eft_refund_email_list.py, pay-api/src/pay_api/services/eft_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/21535
1. Update url in eft refund email
2. Re-create table eft_refund_email_list with auto-increment id
=> 21535 - Update url in eft refund email

jobs/payment-jobs/poetry.lock, jobs/payment-jobs/pyproject.toml, jobs/payment-jobs/tasks/statement_due_task.py, jobs/payment-jobs/utils/auth_event.py
Relies on:
https://github.com/bcgov/sbc-auth/pull/2944
=> 20087 - Add in additional emails

jobs/payment-jobs/invoke_jobs.py, jobs/payment-jobs/poetry.lock, jobs/payment-jobs/tasks/statement_due_task.py, jobs/payment-jobs/tests/jobs/test_statement_due_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/22625
=> 22625 - Add in action date override

.github/workflows/bcol-api-ci.yml
=> Small ci change fix docker-compose for bcol-api

jobs/payment-jobs/tasks/statement_due_task.py
=> Add in check for overdue_notification_date

jobs/payment-jobs/tasks/statement_due_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/22625
=> 22625 - Payment job statement finalization

jobs/payment-jobs/tasks/cfs_create_invoice_task.py
=> EFT - Create Invoice Clean up

pay-api/migrations/versions/2024_08_08_17ca5cd561ca_.py, pay-api/src/pay_api/models/invoice.py, pay-api/src/pay_api/models/statement_invoices.py, pay-api/src/pay_api/services/statement.py, pay-queue/poetry.lock, pay-queue/pyproject.toml, pay-queue/src/pay_queue/services/cgi_reconciliations.py, pay-queue/tests/integration/test_cgi_reconciliations.py
Adding in indexes that were missing for the is_owing.
Refactor part of the statement is_owing so it works under the toggle.
Add in to populate disbursement_reversal_date
=> Production release fixes

jobs/payment-jobs/poetry.lock, jobs/payment-jobs/pyproject.toml, jobs/payment-jobs/tasks/statement_task.py, jobs/payment-jobs/tests/jobs/test_generate_statements.py, pay-api/migrations/versions/2024_08_08_5cb9c5f5896c_.py, pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/models/statement.py, pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/services/payment_service.py, pay-api/src/pay_api/services/statement.py, pay-api/tests/unit/api/test_payment_request.py, pay-api/tests/unit/services/test_statement.py, pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/22667
=> 22667 - EFT interm statements payment method incorrect

pay-api/poetry.lock, pay-api/pyproject.toml
=> Use sql versioning form sbc-connect-common

pay-api/src/pay_api/services/payment.py, pay-api/src/pay_api/services/statement.py, pay-api/src/pay_api/version.py, pay-api/tests/unit/services/test_statement.py
- remove unused input that is erroring
=> EFT Statement Report Fix

docs/docs/api_contract/pay-api.yaml, pay-api/src/pay_api/models/invoice.py, pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/version.py, pay-api/tests/unit/api/test_account.py
=> Add in disbursement reversal date for CSO

jobs/ftp-poller/config.py
=> Update / Clean up EFT SFTP config

.github/workflows/bcol-api-ci.yml, .github/workflows/ftp-poller-ci.yml, .github/workflows/notebook-report-ci.yml, .github/workflows/pay-admin-ci.yml, .github/workflows/pay-api-ci.yml, .github/workflows/pay-queue-ci.yml, .github/workflows/payment-jobs-ci.yml, jobs/payment-jobs/Makefile, jobs/payment-jobs/poetry.lock, jobs/payment-jobs/pyproject.toml, jobs/payment-jobs/tasks/ejv_partner_distribution_task.py, jobs/payment-jobs/tasks/statement_task.py, jobs/payment-jobs/tests/jobs/test_generate_statements.py, pay-api/poetry.lock, pay-api/pyproject.toml, pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/models/payment_line_item.py, pay-api/src/pay_api/services/statement.py
*Issue #:*
https://github.com/bcgov/entity/issues/22803 
=> 22803 - Fix 65535+ query parameter error - Sync with prod release

pay-api/src/pay_api/services/statement.py, pay-api/tests/unit/api/test_statement.py
*Issue #:*
https://github.com/bcgov/entity/issues/22678
=> 22678 - Fix due date

pay-api/src/pay_api/services/direct_pay_service.py, pay-api/tests/unit/api/test_refund.py, pay-api/tests/unit/services/test_direct_pay_service.py
…nt returns
*Issue #:*
https://github.com/bcgov/entity/issues/22775
=> 22775 - Paybc refund endpoint error handling enhancement

pay-api/src/pay_api/services/payment_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/22841
=> 22841 - Add enable-payment-change-from-eft feature flag

pay-queue/src/pay_queue/services/eft/eft_reconciliation.py, pay-queue/tests/integration/factory.py, pay-queue/tests/integration/test_eft_reconciliation.py
*Issue #:*
https://github.com/bcgov/entity/issues/22873
- Automatically apply pending payments to short name account links
=> 22873 - EFT Auto payment

jobs/payment-jobs/poetry.lock, jobs/payment-jobs/pyproject.toml, jobs/payment-jobs/tasks/cfs_create_invoice_task.py, jobs/payment-jobs/tasks/eft_task.py, jobs/payment-jobs/tests/jobs/test_eft_task.py, pay-api/src/pay_api/models/eft_credit_invoice_link.py, pay-api/src/pay_api/models/eft_refund.py, pay-api/src/pay_api/services/cfs_service.py, pay-api/src/pay_api/services/eft_service.py, pay-api/src/pay_api/services/eft_short_names.py, pay-api/src/pay_api/services/statement.py, pay-api/tests/unit/services/test_cfs_service.py, pay-api/tests/unit/services/test_eft_service.py, pay-api/tests/unit/services/test_statement.py, pay-api/tests/utilities/base_test.py, pay-queue/src/pay_queue/services/eft/eft_reconciliation.py
*Issue #:*
https://github.com/bcgov/entity/issues/21597
https://github.com/bcgov/entity/issues/20741
https://github.com/bcgov/entity/issues/22906
=> 21597 & 20741 - Changes for refund api and eft service

pay-api/src/pay_api/services/receipt.py
*Issue #:*
https://github.com/bcgov/entity/issues/22912 
=> 22912 - Fix receipt generation for EFT

jobs/payment-jobs/tasks/eft_task.py
=> Add in a condition to filter out non-ACTIVE invoice references

pay-api/src/pay_api/services/auth.py, pay-api/src/pay_api/services/eft_short_names.py, pay-api/src/pay_api/services/email_service.py, pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/services/statement.py, pay-api/src/pay_api/templates/eft_reverse_payment.html, pay-api/tests/conftest.py, pay-api/tests/unit/api/test_eft_payment_actions.py, pay-api/tests/unit/services/test_statement.py
*Issue #:*
https://github.com/bcgov/entity/issues/22830
- client email for reverse eft payment action
=> 22830 - Reverse Payment Email Notification

pay-api/src/pay_api/services/eft_short_names.py
*Issue #:*
https://github.com/bcgov/entity/issues/22840
- fix incorrect input for send_emai()l recipients
=> 22840 - build recipient list instead of comma delimited string

jobs/payment-jobs/tests/jobs/factory.py, pay-api/src/pay_api/models/__init__.py, pay-api/src/pay_api/models/statement.py, pay-api/src/pay_api/services/non_sufficient_funds.py, pay-api/tests/unit/services/test_non_sufficient_funds.py
*Issue #:*
https://github.com/bcgov/entity/issues/22994
=> 22994 - Fix NSF call so it returns statements

jobs/payment-jobs/poetry.lock, jobs/payment-jobs/pyproject.toml, jobs/payment-jobs/tasks/stale_payment_task.py, pay-api/poetry.lock, pay-api/src/pay_api/services/direct_pay_service.py, pay-api/tests/unit/services/test_direct_pay_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/22775
=> 22775 - Tweaks for stale_payment 'OrderStatus' object has no attribute issue

pay-api/src/pay_api/templates/eft_reverse_payment.html
*Issue #:*
https://github.com/bcgov/entity/issues/22840
- Requirements update for email template from UXA Feedback
=> 22840 - Reverse Payment Email - UXA Feedback

jobs/payment-jobs/tasks/stale_payment_task.py, pay-queue/src/pay_queue/resources/worker.py, pay-queue/src/pay_queue/services/eft/eft_reconciliation.py, pay-queue/src/pay_queue/services/email_service.py, pay-queue/src/pay_queue/services/payment_reconciliations.py, pay-queue/tests/integration/test_eft_reconciliation.py, pay-queue/tests/integration/test_payment_reconciliations.py
*Issue #:*
https://github.com/bcgov/entity/issues/19514
=> 19514 - EFT TDI17 Feedback monitoring

pay-api/src/pay_api/utils/enums.py
*Issue #:*
https://github.com/bcgov/entity/issues/22263 
=> 22263 - Updating enums for EFT Refunds AP Job

pay-api/migrations/README.md, pay-api/pre-hook-update-db.sh, pay-api/src/pay_api/__init__.py, pay-api/src/pay_api/config.py
=> Prehook changes

pay-api/poetry.lock, pay-api/pyproject.toml
=> Point to personal repo so we don't get race condition

pay-api/poetry.lock, pay-api/pyproject.toml
=> Revert "Point to personal repo so we don't get race condition"

jobs/ftp-poller/poetry.lock, jobs/payment-jobs/poetry.lock, pay-admin/poetry.lock, pay-api/poetry.lock, pay-api/pyproject.toml, pay-queue/poetry.lock, pay-queue/pyproject.toml
=> More security changes

jobs/ftp-poller/poetry.lock, jobs/payment-jobs/poetry.lock, pay-admin/poetry.lock, pay-queue/poetry.lock
=> Update latest sentry

pay-api/src/pay_api/services/eft_short_names.py
=> Small fix for statement owing

jobs/payment-jobs/tasks/stale_payment_task.py
=> Fix 404 error on verify created direct_pay invoice

jobs/payment-jobs/poetry.lock, jobs/payment-jobs/pyproject.toml, pay-api/src/pay_api/services/oauth_service.py
=> Fix logging 404 etc

jobs/payment-jobs/poetry.lock, jobs/payment-jobs/pyproject.toml, pay-api/src/pay_api/services/oauth_service.py
There's some weirdness with boolean and Response, it seems like it doesn't always work correctly unless you explicitly look for is None or is not None.
=> Logging changes part3

jobs/payment-jobs/tasks/stale_payment_task.py
=> Add exception to _verify_created_direct_pay_invoices

pay-api/src/pay_api/models/eft_short_names.py, pay-api/src/pay_api/services/eft_short_name_summaries.py, pay-api/src/pay_api/services/eft_short_names.py, pay-api/src/pay_api/utils/enums.py, pay-api/tests/unit/api/test_eft_short_names.py
*Issue #:*
https://github.com/bcgov/entity/issues/21594
=> 21594 - Refund requested badge on short name management list

jobs/payment-jobs/poetry.lock, jobs/payment-jobs/pyproject.toml, pay-api/src/pay_api/models/eft_credit.py, pay-api/src/pay_api/services/eft_service.py, pay-api/src/pay_api/services/eft_short_name_summaries.py, pay-api/src/pay_api/services/eft_short_names.py, pay-api/tests/conftest.py, pay-api/tests/unit/api/test_eft_payment_actions.py, pay-api/tests/unit/services/test_eft_service.py, pay-queue/poetry.lock, pay-queue/pyproject.toml, pay-queue/tests/integration/test_eft_reconciliation.py
*Issue #:*
https://github.com/bcgov/entity/issues/22969
=> 22969 - Refactor EFT Shortnames

jobs/payment-jobs/tasks/eft_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/22655
=> 22655 - Fix eft_task, cancel same invoice_number invoices if consolidated

pay-api/tests/unit/api/test_eft_short_name_history.py
*Issue #:*
https://github.com/bcgov/entity/issues/21539
- Add / Fix short name history tests
=> 21539 - Fix incomplete short name refund test

pay-api/src/pay_api/services/auth.py
=> Small tweak when {} serializes to null which converts to None  Flask 1 -> Flask 3

jobs/payment-jobs/Makefile
=> Disable vault due to deprecation

bcol-api/Makefile, jobs/ftp-poller/Makefile, jobs/payment-jobs/Makefile, pay-admin/Makefile, pay-api/Makefile, pay-queue/Makefile
*Issue #:*
https://github.com/bcgov/entity/issues/23653
=> 23653 - Fix CD Pipelines for Pay as 1pass CLI is depreciated

jobs/payment-jobs/poetry.lock, jobs/payment-jobs/pyproject.toml, jobs/payment-jobs/services/email_service.py, pay-api/src/pay_api/services/auth.py
*Issue #:*
https://github.com/bcgov/entity/issues/21516
- fix LD Flag override
- fix email template short name details typo
=> 21516 - email / ld flag fix

pay-api/src/pay_api/services/eft_refund.py, pay-api/src/pay_api/version.py, pay-api/tests/unit/api/test_eft_short_names.py
*Issue #:*
https://github.com/bcgov/entity/issues/21536
- fix create eft refund status
=> 21536 - EFT refund status fix

pay-queue/src/pay_queue/config.py, pay-queue/src/pay_queue/external/gcp_auth.py, pay-queue/src/pay_queue/resources/worker.py, pay-queue/tests/conftest.py
Reverts bcgov/sbc-pay#1778
Still need this until GCP migration
=> Revert "Remove unnecessary auth for queues"

jobs/payment-jobs/tasks/eft_task.py, jobs/payment-jobs/tests/jobs/test_eft_task.py
=> Remove disbursement_status_code check

pay-api/src/pay_api/services/eft_service.py
=> Missing invoice_balance = 0

pay-api/src/pay_api/dtos/eft_shortname.py, pay-api/src/pay_api/models/base_model.py, pay-api/src/pay_api/resources/v1/eft_short_names.py, pay-api/src/pay_api/services/eft_refund.py, pay-api/tests/unit/api/test_eft_short_names.py, pay-api/tests/utilities/base_test.py
=> Small tweaks for EFT patch approve declined route + Add in get route for refund

jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
=> Add in check for EjvLinkModel so it wont duplicate on PLI

releases/release_to_zenhub_auth.py
*Issue #:*
https://github.com/bcgov/entity/issues/23936
=> 23936 - For auth release for now

pay-api/src/pay_api/config.py, pay-api/src/pay_api/resources/v1/invoice.py, pay-api/src/pay_api/schemas/schemas/payment_request.json, pay-api/src/pay_api/services/payment_service.py, pay-api/tests/unit/api/test_payment_request.py
*Issue #:*
https://github.com/bcgov/entity/issues/23942
=> 23942 - Small tweaks to invoice creation flow for skipPayment - for STRR/NRO and other various sandbox users

pay-api/src/pay_api/resources/v1/transaction.py, pay-api/tests/unit/api/test_transaction.py
*Issue #:*
https://github.com/bcgov/entity/issues/23942
https://github.com/bcgov/sbc-auth/pull/3087 relies on this
=> 23942  - Add in valid redirect url

pay-api/src/pay_api/services/payment_service.py
=> Missing payment row

pay-api/src/pay_api/config.py, pay-api/src/pay_api/services/payment_service.py, pay-api/tests/unit/api/test_payment_request.py
*Issue #:*
https://github.com/bcgov/entity/issues/23942
=> 23942_p2 - Small fix for other payment methods than DIRECT_PAY

pay-api/src/pay_api/services/auth.py
https://github.com/bcgov/sbc-auth/pull/3129
=> Add in feature flag remove-premium-restrictions

pay-api/migrations/versions/2024_10_22_a430eb2b744e_add_refund_status_to_routing_slip.py, pay-api/migrations/versions/2024_10_28_c76e8338de35_add_processing_to_all_rs_refund_requests.py
*Issue #:*
https://github.com/bcgov/entity/issues/19361
=> 19361 - UXA fix for Returned Undeliverable to FAS

pay-api/migrations/versions/2024_10_22_a430eb2b744e_add_refund_status_to_routing_slip.py
*Issue #:*
https://github.com/bcgov/entity/issues/19361
=> 19361 - Fix foreigin key issue on routing slip status change

.github/workflows/bcol-api-cd-gold.yml, .github/workflows/bcol-api-cd.yml
*Issue #:*
https://github.com/bcgov/entity/issues/23247 
=> 23247 - Enable CD for BCOL API GOLD

pay-api/src/pay_api/utils/util.py, pay-api/src/pay_api/version.py, pay-api/tests/unit/utils/test_util.py
- strip www and trailing slashes from urls for comparison
- add test for validating redirect urls
=> Validate redirect url enhancements

pay-api/migrations/versions/2024_10_31_5fa0fea09841_set_routing_slip_status_again.py
=> Small tweak for migration

jobs/payment-jobs/tasks/stale_payment_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/24281
=> 24281 - Skip completed payment on _verify_created_direct_pay_invoices

pay-admin/admin/config.py
https://github.com/bcgov/entity/issues/24339
=> 24339 - Pay admin secret changes

jobs/payment-jobs/tasks/bcol_refund_confirmation_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/20346
=> Datawarehouse refactor bug fix

releases/util.py
=> Add in searching for \d with no space

pay-api/src/pay_api/services/payment.py, pay-api/src/pay_api/services/statement.py, pay-api/tests/unit/services/test_payment.py, pay-api/tests/unit/services/test_payment_service.py, pay-api/tests/unit/services/test_statement.py, pay-api/tests/utilities/base_test.py
=> Revert "24432 - Bottom of EFT statement dynamic amount owing should be immutable"

jobs/payment-jobs/tasks/stale_payment_task.py
=> Stale payment job bug fix

jobs/payment-jobs/poetry.lock, jobs/payment-jobs/pyproject.toml, jobs/payment-jobs/tasks/ap_task.py, jobs/payment-jobs/tasks/cfs_bank_name_updater.py
=> Simplify query, add in try catch

jobs/payment-jobs/tasks/ap_task.py
=> Add in condition for None

pay-api/migrations/versions/2024_11_29_c6f04824d529_increase_contact_name_length_to_100_in_.py
=> Increasing contact_name column length to 100 in routing_slips

pay-api/src/pay_api/services/payment_account.py
https://github.com/bcgov/entity/issues/24671
Fix for statement notification set to false
=> 24671- EFT Warranty - Small bug fix for statement_notification_enabled

jobs/payment-jobs/tasks/cfs_create_account_task.py, jobs/payment-jobs/tests/jobs/test_activate_pad_account_task.py, jobs/payment-jobs/tests/jobs/test_cfs_create_account_task.py, jobs/payment-jobs/tests/jobs/test_cfs_create_routing_slip_account_task.py, jobs/payment-jobs/tests/jobs/utils.py
*Issue #:*
https://github.com/bcgov/entity/issues/24685
Add in check for job to see if it's within business hours
=> 24685 - Add in check for create_cfs_accounts job to see if it's within business hours

jobs/payment-jobs/poetry.lock, pay-api/migrations/versions/2024_12_04_4f3a44eeade8_add_eft_cas_supplier_site.py, pay-api/src/pay_api/models/eft_refund.py, pay-queue/poetry.lock
*Issue #:*
https://github.com/bcgov/entity/issues/24695
=> 24695 - Fix CI error

releases/util.py
=> Minor change to remove duplicates

jobs/notebook-report/daily/cso_reconciliation_details.ipynb, jobs/notebook-report/daily/vs_reconciliation_details.ipynb
=> 21559 - fix sqlmagic.style

pay-api/src/pay_api/services/payment_service.py, pay-queue/src/pay_queue/services/payment_reconciliations.py, pay-queue/tests/integration/test_payment_reconciliations.py
=> Add in receipt for skip payment bug - Small EFT tweak for pay-queue

pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/resources/v1/account.py, pay-api/src/pay_api/services/payment.py, pay-api/tests/unit/api/test_account.py, pay-api/tests/unit/services/test_payment.py
*Issue #:*
https://github.com/bcgov/entity/issues/24811
=> 24811 - Add in new excludeCounts search filter while maintaining backwards compatability

pay-api/src/pay_api/models/payment.py
=> Increase from 60k to 100k on CSV export

pay-api/src/pay_api/resources/v1/account.py, pay-api/src/pay_api/services/auth.py, pay-api/src/pay_api/version.py
*Issue #:*
https://github.com/bcgov/entity/issues/24648
- transaction search role clean up
=> 24648-search-transactions-role-updates

pay-queue/poetry.lock
=> Fix deps for pay-queue

pay-api/src/pay_api/services/eft_short_names.py, pay-api/tests/unit/api/test_eft_short_names.py
*Issue #:*
https://github.com/bcgov/entity/issues/25334
- Test fixes
=> 25334-EFT Statement Payment fixes

releases/release_to_zenhub.py, releases/release_to_zenhub_auth.py, releases/util.py
=> Add in automation for the end release date, still need to manually do the start

jobs/notebook-report/Makefile
=> Remove update-env

pay-api/src/pay_api/utils/enums.py, pay-api/src/pay_api/utils/util.py
*Issue #:*
https://github.com/bcgov/entity/issues/22411
- small tweak here, btr filing will now process similar to a regular lear filing (btr -> lear -> pay -> business pay -> lear filer)
=> API - topic publish for btr product filing

pay-api/migrations/versions/2025_02_11_dd1ed43ad732_.py
=> Set PRODUCT for BTR so queue messages may flow

pay-api/src/pay_api/utils/util.py
=> Add in condition for daily

pay-api/src/pay_api/services/invoice.py
=> fix invoice.business_identifier check

jobs/payment-jobs/config.py, pay-queue/devops/vaults.gcp.env, pay-queue/src/pay_queue/services/payment_reconciliations.py
*Issue #:*
https://github.com/bcgov/entity/issues/25813
=> Fix credit sync - Test environment

pay-api/src/pay_api/services/eft_service.py
=> eft-payment-compare-fix

pay-api/src/pay_api/services/eft_service.py
=> EFT-Payment-Fix-to-main

docs/docs/api_contract/pay-api.yaml
Changing the server section for the new DNS names
=> Update pay-api.yaml for new DNS names

pay-api/src/pay_api/utils/util.py
=> Add in App-Name

jobs/payment-jobs/config.py, pay-api/src/pay_api/services/code.py
=> Remove unused secret, add in bug fix

jobs/payment-jobs/tests/docker/docker-compose.yml, pay-api/tests/docker/docker-compose-arm64.yml, pay-api/tests/docker/docker-compose.yml
=> Repoint docker to auth-api.yaml

pay-queue/src/pay_queue/services/payment_reconciliations.py, pay-queue/tests/integration/test_payment_reconciliations.py
*Issue #:*
https://github.com/bcgov/entity/issues/26974
=> Skip "-C" PAD invoice reference on Payment Reconciliation

pay-api/src/pay_api/services/refund.py, pay-api/src/pay_api/utils/enums.py
=> Small change for invoice refunds

.github/CODEOWNERS, pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/services/email_service.py, pay-api/src/pay_api/templates/credit_add_notification.html, pay-api/tests/conftest.py, pay-api/tests/unit/api/test_partial_refund.py, pay-api/tests/unit/api/test_refund.py, pay-api/tests/unit/services/test_refund.py
*Issue #:*
https://github.com/bcgov/entity/issues/25980
=> 25980 - Send feedback to client that credit is available on acct

pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/templates/credit_add_notification.html, pay-api/tests/unit/services/test_refund.py
*Issue #:*
https://github.com/bcgov/entity/issues/25980
ux tweaks - https://www.figma.com/design/0vRutcPRtoUIkPTQtG257r/Account-Update---Payment-Methods-and-Account-Type?node-id=6295-20&t=J7hRfN1G7tqx3pBB-0#1235240836
=> 25980 Tweaks - Feedback to client that credit is available on acct

pay-api/src/pay_api/dtos/product.py, pay-api/src/pay_api/models/__init__.py, pay-api/src/pay_api/models/fee_schedule.py, pay-api/src/pay_api/resources/v1/bank_accounts.py, pay-api/src/pay_api/resources/v1/fee.py, pay-api/src/pay_api/services/fee_schedule.py, pay-api/tests/unit/api/test_account.py, pay-api/tests/unit/api/test_fee.py, pay-api/tests/unit/models/test_fee_schedule.py, pay-api/tests/unit/services/test_fee_schedule.py
*Issue #:*
https://github.com/bcgov/entity/issues/15518
=> 15518 - Pay API - means of accessing the cost of a filing and the list of filings

jobs/payment-jobs/poetry.lock, jobs/payment-jobs/pyproject.toml, jobs/payment-jobs/tasks/ejv_payment_task.py, jobs/payment-jobs/tests/jobs/factory.py, jobs/payment-jobs/tests/jobs/test_ejv_payment_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/19758
EJV partial refund - payment-jobs updates only
=> 19758 - EJV partial refund job updates

pay-queue/poetry.lock, pay-queue/pyproject.toml, pay-queue/src/pay_queue/services/cgi_reconciliations.py, pay-queue/tests/integration/test_cgi_reconciliations.py
*Issue #:*
https://github.com/bcgov/entity/issues/19758
EJV partial refund - payment-queue updates only
tested existing cgi_reconciliation(no partial refund) functionalities with FEEDBACK.F3505.20250505220023
=> 19758 - EJV partial refund queue updates 

jobs/payment-jobs/poetry.lock, pay-queue/poetry.lock
*Issue #:*
https://github.com/bcgov/entity/issues/27426
=> 27426 - Pay-queue and pay-jobs point at latest pay-api in main

pay-api/src/pay_api/services/base_payment_system.py
*Issue #:*
https://github.com/bcgov/entity/issues/25980
=> 25980 - Small tweak to credit notification title

pay-api/src/pay_api/dtos/product.py, pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/services/eft_short_name_historical.py, pay-api/tests/conftest.py, pay-api/tests/unit/api/test_partial_refund.py, pay-api/tests/unit/services/test_eft_short_name_historical.py, pay-api/tests/unit/services/test_partner_disbursements.py, pay-api/tests/unit/services/test_refund.py, pay-queue/src/pay_queue/services/cgi_reconciliations.py
=> Poetry black changes

pay-api/src/pay_api/services/cfs_service.py, pay-queue/poetry.lock, pay-queue/pyproject.toml, pay-queue/src/pay_queue/services/payment_reconciliations.py
=> Sync payqueue ob hotfix

jobs/payment-jobs/Dockerfile
*Issue #:*
fixing this issue while deployment:
=> Fix job deployment issue

jobs/payment-jobs/Dockerfile
=> Fix job deployment issue 2: can't find uid for user web

jobs/payment-jobs/tasks/common/dataclasses.py, jobs/payment-jobs/tasks/ejv_payment_task.py
=> Revert "28527 - Ejv disbursement code refactor"

jobs/payment-jobs/tasks/common/dataclasses.py, jobs/payment-jobs/tasks/ejv_payment_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/28527
=> 28527 - Ejv disbursement code refactor

jobs/payment-jobs/tasks/ap_task.py
=> 28580 - Add a log to ap_task

jobs/payment-jobs/tasks/ap_task.py, jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
=> Remove extra logs

pay-api/src/pay_api/config.py
*Issue #:*
https://github.com/bcgov/entity/issues/27506
=> 27506 - add IT_OPS_EMAIL to pay-api

pay-api/src/pay_api/config.py
*Issue #:*
https://github.com/bcgov/entity/issues/28662
=> 28662_p2 - Use base64 decoding

pay-api/src/pay_api/services/base_payment_system.py
=> Add in logging for credit notification failure also wrap in try catch

jobs/notebook-report/devops/gcp/clouddeploy.yaml
*Issue #:*
https://github.com/bcgov/entity/issues/29032
=> 29032 - Add in cloud deploy

pay-api/src/pay_api/services/code.py
=> Fix payment blocking to add in CC

jobs/payment-jobs/tasks/ap_task.py, jobs/payment-jobs/tasks/common/cgi_ejv.py, jobs/payment-jobs/tasks/ejv_partner_distribution_task.py, jobs/payment-jobs/tasks/ejv_payment_task.py
https://github.com/bcgov/entity/issues/29439
=> 29439 - Fix EJV file names so they are consistent

pay-api/src/pay_api/config.py, pay-api/src/pay_api/resources/v1/eft_short_names.py, pay-api/src/pay_api/services/eft_short_name_summaries.py, pay-api/src/pay_api/services/eft_short_names.py, pay-api/tests/unit/api/test_eft_short_names.py
*Issue #:*
https://github.com/bcgov/entity/issues/27404 
add sorting to Unsettled Amount column
=> 27404 - added sorting to Unsettled Amount column

pay-api/src/pay_api/services/base_payment_system.py, pay-api/src/pay_api/services/refund.py, pay-api/src/pay_api/utils/enums.py, pay-api/tests/unit/api/test_partial_refund.py
*Issue #:*
https://github.com/bcgov/entity/issues/29177 
=> 29177 - added PARTIALLY_REVERSED state in reversal queue message

pay-api/src/pay_api/models/applied_credits.py, pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/models/refunds_partial.py, pay-api/src/pay_api/utils/enums.py, pay-api/tests/unit/api/test_account.py, pay-api/tests/unit/models/test_refund_partial_search.py, pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/26504
=> 26504 - Add in additional fields and handle other statuses/payment methods

pay-api/migrations/versions/2025_07_24_94ca57d30196_partial_refund_add_is_credit.py, pay-api/pyproject.toml, pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/models/refunds_partial.py, pay-api/src/pay_api/services/payment_service.py, pay-api/src/pay_api/services/refund.py, pay-api/tests/unit/api/test_account.py, pay-api/tests/unit/api/test_partial_refund.py, pay-api/tests/unit/models/test_refund_partial_search.py, pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/26504
=> 26504 - Bug fixes for new Payment Method / Invoice Statuses

pay-api/src/pay_api/models/statement.py, pay-api/src/pay_api/services/statement.py, pay-api/tests/unit/api/test_eft_payment_actions.py
=> Use service instead of model

jobs/payment-jobs/tasks/cfs_create_invoice_task.py, jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/21713
Create invoice job exception notification
=> added notification for create invoice failure

pay-api/src/pay_api/templates/job_failed_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/21713
making table name optional in the template
=> 21713 - making table name optional in the template

pay-api/src/pay_api/services/auth.py, pay-api/src/pay_api/services/base_payment_system.py
*Issue #:*
https://github.com/bcgov/entity/issues/29398
=> 29398 - fix credits email not working on prod

jobs/payment-jobs/invoke_jobs.py
*Issue #:*
https://github.com/bcgov/entity/issues/21713
Add more logs in Invoke Jobs
=> 21713 - added more logs in Invoke Jobs

pay-admin/admin/views/fee_schedule.py
*Issue #:*
https://github.com/bcgov/entity/issues/30048
=> 30048 - Add gst_added to fee schedule

pay-queue/src/pay_queue/services/cgi_reconciliations.py
…unds
*Issue #:*
fix(cgi_reconciliations): ensure line_items is a list for Partial Refund
=> fix(cgi_reconciliations): ensure line_items is a list for PR

jobs/ftp-poller/poetry.lock, jobs/ftp-poller/pyproject.toml, jobs/payment-jobs/poetry.lock, jobs/payment-jobs/pyproject.toml, jobs/payment-jobs/tasks/routing_slip_task.py, pay-admin/poetry.lock, pay-admin/pyproject.toml, pay-api/migrations/versions/2025_08_13_18c691c0edd2_remove_old_gst_column.py, pay-api/src/pay_api/models/invoice.py, pay-api/src/pay_api/models/payment.py, pay-api/src/pay_api/models/payment_line_item.py, pay-api/src/pay_api/schemas/schemas/invoice.json, pay-api/src/pay_api/schemas/schemas/line_item.json, pay-api/src/pay_api/services/fee_schedule.py, pay-api/src/pay_api/services/invoice.py, pay-api/src/pay_api/services/payment.py, pay-api/src/pay_api/services/payment_line_item.py, pay-api/src/pay_api/services/payment_service.py, pay-api/tests/unit/api/test_fee.py, pay-api/tests/unit/services/test_fee_schedule.py, pay-api/tests/unit/services/test_payment.py, pay-api/tests/unit/services/test_payment_line_item.py, pay-api/tests/unit/services/test_payment_service.py, pay-api/tests/unit/services/test_statement.py, pay-api/tests/utilities/base_test.py, pay-queue/poetry.lock, pay-queue/pyproject.toml, pay-queue/src/pay_queue/services/payment_reconciliations.py
=> Enable payment line item gst fields in API

pay-api/src/pay_api/services/cfs_service.py, pay-api/tests/unit/services/test_cfs_service.py
=> Remove gst calculations from AR computation

pay-api/src/pay_api/services/cfs_service.py, pay-api/tests/unit/services/test_cfs_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/30323 
=> 30323 - Revert AR payload to include tax amounts excluding tax_classification

jobs/ftp-poller/poetry.lock, jobs/ftp-poller/pyproject.toml, jobs/payment-jobs/poetry.lock, jobs/payment-jobs/pyproject.toml, jobs/payment-jobs/tasks/stale_payment_task.py, pay-admin/poetry.lock, pay-admin/pyproject.toml, pay-api/src/pay_api/models/invoice.py, pay-api/src/pay_api/models/payment_transaction.py, pay-api/src/pay_api/services/payment_service.py, pay-api/src/pay_api/services/payment_transaction.py, pay-api/tests/unit/services/test_payment_transaction.py, pay-queue/poetry.lock, pay-queue/pyproject.toml
*Issue #:*
https://github.com/bcgov/entity/issues/30290
=> 30290 - Modify stale payment job to consider transactions that are failed

pay-api/devops/gcp/clouddeploy.yaml
*Issue #:*
https://github.com/bcgov/entity/issues/27061
=> 27061 - Increase PAY test env memory to 1G

pay-api/src/pay_api/services/paybc_service.py, pay-api/tests/unit/services/test_paybc_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/29958
=> 29958 - Fix url for pay-connector

pay-api/src/pay_api/services/payment.py, pay-api/src/pay_api/services/payment_calculations.py, pay-api/src/pay_api/services/statement.py, pay-api/tests/unit/services/test_payment.py, pay-api/tests/unit/services/test_statement.py
*Issue #:*
https://github.com/bcgov/entity/issues/29484
report-api changes: https://github.com/bcgov/bcros-common/pull/212
=> 29484 Add summary page to statement

jobs/ftp-poller/poetry.lock, jobs/ftp-poller/pyproject.toml, jobs/payment-jobs/config.py, jobs/payment-jobs/poetry.lock, jobs/payment-jobs/pyproject.toml, pay-admin/poetry.lock, pay-admin/pyproject.toml, pay-api/src/pay_api/config.py, pay-api/src/pay_api/services/email_service.py, pay-queue/poetry.lock, pay-queue/pyproject.toml, pay-queue/src/pay_queue/config.py, pay-queue/src/pay_queue/services/email_service.py
=> Fix ITOPS email

pay-api/migrations/versions/2025_09_19_c1e2b8b9384f_update_payment_description.py, pay-api/src/pay_api/services/payment_calculations.py, pay-api/src/pay_api/utils/enums.py, pay-api/tests/unit/services/test_statement.py
*Issue #:*
https://github.com/bcgov/entity/issues/29485
https://github.com/bcgov/entity/issues/29484
=> 29485 - Statement summary page tweaks

pay-api/src/pay_api/models/statement_settings.py, pay-api/src/pay_api/services/activity_log_publisher.py, pay-api/src/pay_api/services/payment_account.py, pay-api/src/pay_api/services/statement.py, pay-api/src/pay_api/services/statement_settings.py, pay-api/src/pay_api/utils/dataclasses.py, pay-api/tests/unit/services/test_activity_log_publisher.py, pay-api/tests/unit/services/test_statement.py
*Issue #:*
https://github.com/bcgov/entity/issues/30308 
=> 30308 - Activity Log - Statement changes continued
