- pay-api/tests/postman/pay-api.postman_collection.json
*Issue #:*
https://github.com/bcgov/entity/issues/602
https://github.com/bcgov/entity/issues/634
Updating postman collection with GET and PUT transactions endpoint.
> Updating Postman collection with GET and PUT transactions endpoint

- pay-api/config.py
*Issue #:*
Changing the report api URL to mock for pytest
> Changing the report api URL to mock for pytest

- jobs/update-stale-payment/config.py
- pay-api/config.py
*Issue #:*
Changes for config to PAYBC_CONNECT_TIMEOUT
Update stale payment records is failing coz of the config value not formatted.
> Changes for config to PAYBC_CONNECT_TIMEOUT

- openshift/templates/api-config.json
- pay-api/config.py
- pay-api/src/pay_api/__init__.py
- pay-api/src/pay_api/factory/payment_system_factory.py
- pay-api/src/pay_api/models/__init__.py
- pay-api/src/pay_api/resources/transaction.py
- pay-api/src/pay_api/services/auth.py
- pay-api/src/pay_api/services/payment_service.py
- pay-api/src/pay_api/services/payment_transaction.py
- pay-api/src/pay_api/services/queue_publisher.py
- pay-api/src/pay_api/utils/enums.py
- pay-api/src/pay_api/utils/errors.py
- pay-api/src/pay_api/utils/util.py
- pay-api/tests/unit/api/test_payment.py
- pay-api/tests/unit/api/test_receipt.py
- pay-api/tests/unit/api/test_transaction.py
- pay-api/tests/unit/conf/test_version.py
- pay-api/tests/unit/factory/test_payment_system_factory.py
- pay-api/tests/unit/services/test_auth.py
- pay-api/tests/unit/services/test_bcol_service.py
- pay-api/tests/unit/services/test_invoice_reference.py
- pay-api/tests/unit/services/test_payment_service.py
- pay-api/tests/unit/services/test_payment_transaction.py
- pay-api/tests/unit/services/test_receipt.py
- pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/1987
- Changes to support service account API calls
- Changes to make transactions endpoints open and adding redirect url validation
- Fixed existing flake8 errors
- Changed transactions patch to receive json instead of url param
*Checklist:*
> 1987: Changes for non-authenticated user payment

- pay-api/src/pay_api/services/oauth_service.py
- pay-api/src/pay_api/services/paybc_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/1872
- If site creation throws 400 get sites[0] to use as the current site
*Checklist:*
> 1872: Changes to get sites if site creation fails

- pay-api/src/pay_api/services/paybc_service.py
*Issue #:*
Removing space from transaction number to avoid PayBC error
*Checklist:*
> Removing space from transaction number to avoid PayBC error

- pay-api/src/pay_api/services/payment.py
- report-api/report-templates/payment_transactions.html
- report-api/src/api/resources/report.py
- report-api/tests/unit/api/test_reports.py
*Issue #:*
https://github.com/bcgov/entity/issues/3286
- Adding pdf template and changes in pay-api to download pdf report
*Checklist:*
> Adding pdf template and download for transaction reports

- docs/docs/PayBC Mocking/paybc-1.0.0.yaml
- pay-api/config.py
- pay-api/src/pay_api/resources/transaction.py
- pay-api/src/pay_api/services/direct_pay_service.py
- pay-api/src/pay_api/services/fee_schedule.py
- pay-api/src/pay_api/services/paybc_service.py
- pay-api/src/pay_api/utils/util.py
- pay-api/tests/docker/docker-compose.yml
- pay-api/tests/unit/api/test_transaction.py
- pay-api/tests/unit/services/test_direct_pay_service.py
- pay-api/tests/unit/services/test_payment_transaction.py
*Issue #:*
https://github.com/bcgov/entity/issues/4243
- Updating PATCH /transactions/{id} endpoint to handle return from both paybc invoiced CC payment and direct pay
- Updating paybc mock to include mock for new endpoint
- Handling all the API calls and hash validation on direct pay return
*Checklist:*
> Handling return from direct pay to auth

- pay-api/src/pay_api/models/statement_settings.py
*Issue #:*
https://github.com/bcgov/entity/issues/4896
Stripped time information from the date comparison.The time part was causing issues with comparison and the case where weekly statement end date is today , weekly statements were not getting generated.
*Checklist:*
> fixed bug with weekly statements not getting generatd

- pay-api/src/pay_api/services/statement_settings.py
- pay-api/tests/conftest.py
- pay-api/tests/unit/api/test_statement_settings.py
*Issue #:*
https://github.com/bcgov/entity/issues/5120
UI needs the date as last date+1
*Checklist:*
> Fix for wrong start date for frequency change in statements

- pay-api/src/pay_api/config.py
- pay-api/src/pay_api/models/cfs_account.py
- pay-api/src/pay_api/resources/account.py
- pay-api/src/pay_api/services/base_payment_system.py
- pay-api/src/pay_api/services/bcol_service.py
- pay-api/src/pay_api/services/cfs_service.py
- pay-api/src/pay_api/services/direct_pay_service.py
- pay-api/src/pay_api/services/internal_pay_service.py
- pay-api/src/pay_api/services/online_banking_service.py
- pay-api/src/pay_api/services/pad_service.py
- pay-api/src/pay_api/services/paybc_service.py
- pay-api/src/pay_api/services/payment_account.py
- pay-api/tests/unit/api/test_account.py
- pay-api/tests/unit/services/test_pad_service.py
- pay-api/tests/unit/services/test_payment_system_service.py
- pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/4776
- Handling CFS down scenario for Online Banking and PAD accounts
- Return 202 if CFS is down
- Return 201 if CFS is up for POST
- Return 200 is CFS is up for PUT
*Checklist:*
> Handling Online Banking and PAD account creation when CFS is down

- docs/docs/PayBC Mocking/paybc-1.0.0.yaml
- pay-api/src/pay_api/services/cfs_service.py
- pay-api/tests/docker/docker-compose.yml
- pay-api/tests/unit/services/test_cfs_service.py
* Bank validation errors are fixed
*Issue #:*
https://github.com/bcgov/entity/issues/4773
- The CFS API returns 400  with a payload for the invalid bank account details. So checked 200 or 400 for error status. 
- handled the errors in the backend and returned a graceful response so that its easier to handle it in the front end .
*Checklist:*
> Bank validation error handled

- pay-api/src/pay_api/config.py
- pay-api/src/pay_api/services/payment_account.py
- pay-api/tests/unit/services/test_payment_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/5343
The date saved now will be in converted to UCT... so suppose ,(thursday night) date will be saved as (thursday night+7)..
The jobs are already in UTC.. so might not need any changes... becauase at midnight when the job runs, the utc time will 12+7...
*Checklist:*
> Fixed activation time in utc

- jobs/payment-jobs/tasks/cfs_create_invoice_task.py
- jobs/payment-jobs/tests/docker/docker-compose.yml
- jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
- pay-api/tests/docker/docker-compose.yml
- queue_services/payment-reconciliations/tests/docker-compose.yml
*Issue #:*
https://github.com/bcgov/entity/issues/4854
- Hold creating invoices if CFS Account is FROZEN
*Checklist:*
> Hold creating invoices if CFS Account is FROZEN

- pay-api/src/pay_api/services/payment_account.py
- pay-api/tests/unit/services/test_payment_account.py
*Issue #:*
The bug was caused by the setting of payment type as draw down TOO EARLY. [drawdown is the effective payment method since the pad is in activation period and draw down takes precedence] . Since it was set as drawdown , the cfs account creation logic wouldnt execute. 
This is fixed by simply moving the logic to the end of the block so that no other things are affected.
Added a test as well.
> Fix for linked PAD accounts not creating cfs table entries

- jobs/payment-jobs/tasks/cfs_create_account_task.py
- pay-api/src/pay_api/services/payment_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/5779
1) added pad tos user id so that account mailer can use to address the account creator
2) removed the event which is not needed
3) corrected masking
> added the pad tos accepted user id in event reponse , masking corrected

- pay-api/src/pay_api/services/payment_account.py
- pay-api/tests/unit/api/test_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/5095
the logic is to put cfs_account to inactive if the `if pay_system.get_payment_system_code() == PaymentSystem.PAYBC.value:` is false. I hope that works and wont break anything else 
An update/creation of payment account comes and if system code is not PAYBC , we will set cfsaccount to inactive
> deactivte cfs account when goes to bcol

- pay-api/src/pay_api/services/payment_account.py
- pay-api/tests/unit/services/test_payment_account.py
*Issue #:*
PAD activation date is set only if there is pad activated by user.
> defaulting of pad_tos_accepted_date is removed

- pay-api/src/pay_api/services/cfs_service.py
A fix related to a UI bug. Not necessarily need to be fixed here ;but for the sake of consistency , fixing it here.
service returns the validation messages as a list when CFS is available and validation is carried out successfully.But when the CFS is down , it was returning single string message. Thats been changed. 
The error message when CFS is not supposed to be used by UI ;but because of a bug it's been read and it failed  because it expected a list.
> returning message as a list incase of error scenarios

- pay-api/src/pay_api/resources/payment.py
*Issue #:*
Fixing permissions so that staff can get the failed payment statuses
added the view and edit to the api. 
> Fixing permissions so that staff can get the failed payment statuses

- pay-api/src/pay_api/resources/invoice_receipt.py
Riaz found out that Nr reciepts are failing with below error .
{“message”:”SBC Pay API exception.\r\n\r\n__init__() got an unexpected keyword argument ‘paymentMethodDescription’”}
I think they are checking  schema in their side .So this is a fix to address the issue.
*Issue #:*
> removed paymentMethodDescription from reciept schema so that Nr is not failing

- queue_services/payment-reconciliations/requirements.txt
- queue_services/payment-reconciliations/requirements/prod.txt
- queue_services/payment-reconciliations/src/reconciliations/ejv_reconciliations.py
*Issue #:*
https://github.com/bcgov/entity/issues/6351
- Reconciliation was changing the status on both credit and debit, fixed it to set it only for credits as debit is always registry GL code
> Fixing issue with setting wrong status for JV distribution.

- pay-api/migrations/versions/03b2c7caed21_populate_receipt_number_payments.py
- pay-api/src/pay_api/services/payment.py
- pay-api/src/pay_api/services/payment_transaction.py
- pay-api/tests/unit/services/test_payment_transaction.py
*Issue #:*
https://github.com/bcgov/entity/issues/7896
> Changes for populating receipt_number to payments table for all payment types

- pay-api/src/pay_api/models/routing_slip.py
- pay-api/src/pay_api/resources/fas/routing_slip.py
- pay-api/tests/unit/api/fas/test_routing_slip.py
- pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/8104
- defaulted return all to true if no pagination is passed.
- As discussed in UX meeting, changes from our original plan
initiator is the staff who creates the routing slip
date filter is for the routing slip date.
> changed initiator, date fields and return all

- pay-api/src/pay_api/models/fee_schedule.py
- pay-api/src/pay_api/resources/fee_schedule.py
- pay-api/src/pay_api/services/fee_schedule.py
- pay-api/tests/unit/api/test_fee_schedule.py
*Issue #:*
https://github.com/bcgov/entity/issues/8631
- Added corp type and filing type details into schema
- Added a description search.. the search is not perfect ;I will improve it later.Put a TODO for this.. 
> added corp type and filing type to fee schedules endpoint

- pay-api/src/pay_api/services/auth.py
- pay-api/tests/unit/api/test_payment_request.py
- pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/8659
When the businessId is empty , we wont call auth and auth_response will be None.so auth_response is set to empty dict to avoid breaking further code.
> auth_response None

- jobs/payment-jobs/requirements.txt
- jobs/payment-jobs/tasks/cfs_create_invoice_task.py
- pay-api/src/pay_api/services/bcol_service.py
- queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
*Issue #:*
https://github.com/bcgov/entity/issues/9017
- Adding sentry alert if no invoice is found on reconciliation
- Setting the transaction number in CFS to first invoice number
> Fixes on reconciliation

- pay-api/src/pay_api/services/ejv_pay_service.py
- pay-api/src/pay_api/services/refund.py
*Issue #:*
- Changes to invoice status for EJV refunds
> Changes to invoice status for EJV refunds

- pay-api/src/pay_api/resources/account.py
- pay-api/src/pay_api/services/payment_account.py
- pay-api/src/pay_api/utils/enums.py
- pay-api/tests/unit/api/test_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/9800
- Allow service account with create_sanbox_account role to allow creating sandbox accounts
- Set the sandbox account status to ACTIVE and set the PAD activation time to now
> Changes for allowing a sandbox account to be created by service account

- pay-api/src/pay_api/services/base_payment_system.py
- pay-api/src/pay_api/services/bcol_service.py
- pay-api/src/pay_api/services/ejv_pay_service.py
- pay-api/src/pay_api/services/internal_pay_service.py
- pay-api/src/pay_api/services/pad_service.py
- pay-api/src/pay_api/utils/enums.py
- pay-api/src/pay_api/utils/user_context.py
- pay-api/tests/unit/api/test_payment_request.py
*Issue #:*
https://github.com/bcgov/entity/issues/9801
- Changes for marking payment records as complete for sandbox tokens
> Changes for marking payment records as complete for sandbox tokens

- report-api/Dockerfile
- report-api/entrypoint.sh
*Issue #:*
- Adjusting report API timeout to 360 seconds in gunicorn
> Adjusting report API timeout to 360 seconds in gunicorn

- pay-api/src/pay_api/schemas/schemas/routing_slip.json
- pay-api/tests/unit/api/fas/test_routing_slip.py
- pay-api/tests/unit/api/test_payment_request.py
- pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/10068
- Update routingslip.json to add min and max legth for rs number
- test cases to validate
> 10068 - API validation for routing slip number length

- jobs/payment-jobs/tasks/cfs_create_invoice_task.py
- jobs/payment-jobs/tasks/stale_payment_task.py
- queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
*Issue #:*
- Try a GET on invoice is POST error-ed out, as it happened few times in PROD
- Adding INACTIVE cfs account as well during reconciliation, as an account changed from PAD to DRAWDOWN doesn't get reconciled
- Mark the transaction as CANCELLED, if there are no action required on the payment on stale payment job
> Trying a GET on invoice, if invoice creation fails.

- jobs/payment-jobs/tasks/routing_slip_task.py
- jobs/payment-jobs/tests/jobs/test_routing_slip_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/10414
https://github.com/bcgov/entity/issues/10413
> Changing NSF routing slip status to ACTIVE once linking is complete

- jobs/payment-jobs/requirements.txt
- pay-api/src/pay_api/services/fee_schedule.py
*Issue #:*
- Calculate the account level service fee only if fee schedule got service fee configured.
> Calculate the account level service fee only if fee schedule got service fee configured.

- queue_services/payment-reconciliations/requirements.txt
- queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
*Issue #:*
- Do not create duplicate COMPLETED payments for same invoice number
- Remove false alarm if same message is published again
> Avoid duplicate entries and fix false alarm on reconciliations

- pay-api/requirements.txt
- queue_services/events-listener/requirements/prod.txt
- queue_services/payment-reconciliations/requirements/prod.txt
- queue_services/payment-reconciliations/tests/conftest.py
- queue_services/payment-reconciliations/tests/docker-compose.yml
Pin Jinja 2 to 3.0.3. to fix the failing CI workflows.
Use a fixed version of Minio, use the new environment variables for it's secrets.
Fix the migration path for other operating systems.
> 12019 - Fix failing CI workflows

- jobs/payment-jobs/tasks/cfs_create_account_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/11957
Move the try catch up higher. This way the entire cfs_create_account task doesn't bail out if we receive a 401 from auth api.
> 11957 - Payment job fixes 

- pay-api/src/pay_api/services/payment_service.py
- pay-api/tests/unit/api/test_payment_request.py
*Issue #:*
https://github.com/bcgov/entity/issues/11924
Remove folioNumber reading from auth token. 
> 11924 - Small fix for folioNumber, it's reading from the token but can be blank.

- pay-api/src/pay_api/services/payment_service.py
Fix for: https://sentry.io/organizations/registries/issues/3411689127/?project=1762954 - payment_requests patch - unsupported operand type(s) for +: 'int' and 'NoneType'
> Fix: unsupported operand type(s) for +: 'int' and 'NoneType'

- bcol-api/devops/vaults.json
- bcol-api/docs/dotenv_template
- bcol-api/requirements/prod.txt
- bcol-api/setup.cfg
- bcol-api/src/bcol_api/__init__.py
- bcol-api/src/bcol_api/config.py
- bcol-api/src/bcol_api/services/bcol_payment.py
- bcol-api/src/bcol_api/services/bcol_profile.py
- jobs/ftp-poller/config.py
- jobs/ftp-poller/devops/vaults.json
- jobs/ftp-poller/invoke_jobs.py
- jobs/ftp-poller/setup.cfg
- jobs/payment-jobs/config.py
- jobs/payment-jobs/devops/vaults.json
- jobs/payment-jobs/invoke_jobs.py
- jobs/payment-jobs/tasks/cfs_bank_name_updater.py
- pay-admin/devops/vaults.json
- pay-api/devops/vaults.json
- pay-api/docs/dotenv_template
- pay-api/src/pay_api/__init__.py
- pay-api/src/pay_api/config.py
- queue_services/events-listener/devops/vaults.json
- queue_services/events-listener/src/events_listener/config.py
- queue_services/payment-reconciliations/devops/vaults.json
- queue_services/payment-reconciliations/src/reconciliations/config.py
- report-api/setup.cfg
- report-api/src/api/__init__.py
Signed-off-by: Chen <Steven.Chen@gov.bc.ca>
*Issue #:*
https://github.com/bcgov/entity/issues/12422
Turn Sentry Off by using SENTRY_ENABLE FLAG instead of SENTRY_DSN
> Turn Sentry Off by using SENTRY_ENABLE FLAG instead of SENTRY_DSN#12422

- .github/workflows/payment-reconciliations-ci.yml
- queue_services/events-listener/requirements/dev.txt
- queue_services/payment-reconciliations/src/reconciliations/cgi_reconciliations.py
- queue_services/payment-reconciliations/src/reconciliations/config.py
* Fix to skip over AP_REFUNDS for now (they all fail)
* Update workflows.
*Issue #:*
> Fix to skip over AP_REFUNDS for now (they all fail) (#972)

- pay-api/src/pay_api/services/base_payment_system.py
*Issue #: 9431*
https://github.com/bcgov/entity/issues/9431
- added invoice_number as key to filingDescription in refund_data
- might need to change `bcol_refund_email-template` in `account-mailer` too
> 9431 - Added key to BCOL refund emails

- docs/docs/api_contract/pay-api-1.0.2.yaml
- jobs/payment-jobs/tests/docker/docker-compose.yml
- pay-api/tests/docker/docker-compose.yml
*Issue #:*
https://github.com/bcgov/entity/issues/14137
> 14137 - Update API spec to include SETTLEMENT_SCHED

- pay-api/src/pay_api/services/fee_schedule.py
> Revert "Revert "14180 - Reverse CSO specific changes for service_fees.""

- pay-api/src/pay_api/schemas/schemas/filing_info.json
> Put in max length for folio number, filing identifier.

- pay-api/migrations/versions/fd5c02bb9e01_.py
- pay-api/src/pay_api/models/payment.py
- pay-api/src/pay_api/models/routing_slip.py
- pay-api/src/pay_api/services/fas/routing_slip.py
- pay-api/tests/unit/api/fas/test_routing_slip.py
*Issue #:*
https://github.com/bcgov/entity/issues/14618
PAY-API changes for routing slip corrections
> 14618 - PAY-API changes for routing slip corrections - Part 1 

- pay-api/migrations/versions/39c2491d0a07_migration_for_business_details.py
- pay-api/src/pay_api/models/invoice.py
- pay-api/src/pay_api/models/payment.py
- pay-api/src/pay_api/services/payment.py
- pay-api/src/pay_api/utils/constants.py
- pay-api/src/pay_api/version.py
*Issue #:*
https://github.com/bcgov/entity/issues/12777
- Remove LEAR code, which can possibly be called on every invoice queried (corp type code lookup for receipt)
- Include migration for above, also fix it in lear: https://github.com/bcgov/lear/pull/1881
- Optimize `search_purchase_history` to use only needed fields and joins
- Fix `create_payment_report_details` so it wont requery the database when the information is already available
> 12777 - System Exit 1 / Performance fixes for Invoice searching, also statement building

- pay-api/src/pay_api/services/fas/routing_slip.py
*Issue #:*
https://github.com/bcgov/entity/issues/14618
Fix from feedback, casting float to Decimal.
```
File "/opt/app-root/src/pay_api/services/fas/routing_slip.py", line 417, in update
correction_total, comment = cls._calculate_correction_and_comment(rs_number, request_json)
File "/opt/app-root/src/pay_api/services/fas/routing_slip.py", line 435, in _calculate_correction_and_comment
correction_total += paid_amount - payment.paid_amount
TypeError: unsupported operand type(s) for -: 'float' and 'decimal.Decimal'
```
> 14618 - Fix from feedback, casting float to Decimal.

- .github/workflows/notebook-report-cd.yml
- jobs/notebook-report/daily/reconciliation_details.ipynb
- jobs/notebook-report/monthly/reconciliation_summary.ipynb
*Issue #:* 
https://github.com/bcgov/entity/issues/14945
Updated the report to include updated_on and invoice_number
> Create job to schedule reports - invoice reconciliation #14945

- pay-api/src/pay_api/services/bcol_service.py
Fixes this, as it could be valid. 
```
2023-02-21 15:13:06,492 - pay_api - ERROR in bcol_service:bcol_service.py:101 - create_invoice: 400 Client Error: BAD REQUEST for url: https://bcol-api.apps.silver.devops.gov.bc.ca/api/v1/payments
2023-02-21 15:13:06,494 - pay_api - ERROR in payment_service:payment_service.py:126 - create_invoice: Rolling back as error occured!
```
> Fix for bcol logging.

- queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
Fixes error:
unsupported operand type(s) for -: 'decimal.Decimal' and 'float' https://registries.sentry.io/issues/3947202203/?end=2023-02-21T10%3A23%3A06&project=1762954&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&referrer=issue-stream&sort=inbox&start=2022-11-23T10%3A23%3A06&utc=true
> Use decimal instead of float. 

- jobs/notebook-report/notebookreport.py
*Issue #:* 2247
All notebook reports (including Namex, LEAR, PAY notebook reports) were sent but didn't deliver to the receivers. The reason for this is that the contents in the email body were filter by the email server. Need to update codes to fix this issue.
https://app.zenhub.com/workspaces/entity-5bf2f2164b5806bc2bf60531/issues/gh/bcgov-registries/ops-support/2247
> To fix all notebook reports Sent but not delivered Issue#2247

- jobs/payment-jobs/invoke_jobs.py
- jobs/payment-jobs/tasks/statement_task.py
- jobs/payment-jobs/tests/jobs/test_generate_statements.py
- pay-api/src/pay_api/models/payment_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/15467
Allow statements job to have a date override - that way we can generate statements where there are gaps.
I've also moved the statement job to 8 UTC (from 7 UTC), this way it doesn't cause gaps when daylight savings switches.
Usage:
`python invoke_jobs.py GENERATE_STATEMENTS 2022-01-01`
> 15467 - Allow statements job to have a date override

- jobs/payment-jobs/requirements.txt
- pay-api/src/pay_api/resources/account.py
*Issue #:*
https://github.com/bcgov/entity/issues/15257
Would return internal error 500, not the bad request error correctly.
> 15257- Fix for exception not coming back correctly.

- jobs/payment-jobs/requirements.txt
- jobs/payment-jobs/tasks/statement_task.py
- jobs/payment-jobs/tests/jobs/test_generate_statements.py
- pay-api/src/pay_api/models/statement.py
- pay-api/src/pay_api/version.py
https://www.github.com/bcgov/issues/5467
This gets rid of duplicate statements, without needing to have a query to remove duplicates.
> 15467 - Statement enhancements, remove duplicates - fix the sort order in pay as well.

- jobs/payment-jobs/tasks/statement_task.py
> Add in db.session.flush()

- DEVELOPER_NOTES.md
> Adding in developer notes

- queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
```
2023-03-15 21:40:45,595 - asyncio - ERROR in worker:worker.py:76 - cb_subscription_handler: Queue Error: {"specversion": "1.x-wip", "type": "bc.registry.payment.casSettlementUploaded", "source": "https://api.business.bcregistry.gov.bc.ca/v1/business/BC1234567/filing/12345678", "id": "C234-1234-1234", "time": "2020-08-28T17:37:34.651294+00:00", "datacontenttype": "application/json", "data": {"fileName": "BCR_PAYMENT_APPL_20230228.csv", "source": "MINIO", "location": "payment-sftp"}}
Traceback (most recent call last):
File "/opt/app-root/src/reconciliations/worker.py", line 73, in cb_subscription_handler
await process_event(event_message, FLASK_APP)
File "/opt/app-root/src/reconciliations/worker.py", line 58, in process_event
await reconcile_payments(event_message)
File …
```
> Small fix for payment reconciliation for online banking.

- DEVELOPER_NOTES.md
- pay-api/migrations/versions/2023_03_07_f4a1388844ed_.py
- pay-api/src/pay_api/models/credit.py
- pay-api/src/pay_api/version.py
Add in a details field in credits - that way we can capture information regarding the credits.
> Add in data for no fee, add in details field for credits, update developer notes.

- jobs/payment-jobs/tasks/statement_task.py
> Performance tweak statements

- pay-api/requirements.txt
- pay-api/requirements/prod.txt
- pay-api/requirements/repo-libraries.txt
- pay-api/setup.cfg
- pay-api/src/pay_api/config.py
- pay-api/src/pay_api/services/gcp_queue_publisher.py
- pay-api/src/pay_api/services/payment_transaction.py
*Issue #:* /bcgov/entity#16405
Partial add of the new alternate queue. Backed off some changes and the simple cloudevent for the older version of python.
This takes care of Step1 - add minimal publish to sbc-pay
> partial of the new queue service

- pay-api/devops/vaults.json
This will enable the posting of messages to the queue in dev only
Adding the vault for gcp-queue payment section for dev-test-sandbox-prod
Only dev has values, but the keys are in the 1Password vault.
> adding the vault for gcp-queue

- pay-api/src/pay_api/resources/account.py
*Issue #:*
https://github.com/bcgov/entity/issues/17529
> 17529 - Remove isPremium check from CSV export.

- report-api/report-templates/invoice.html
*Issue #:*
https://github.com/bcgov/entity/issues/17477
invoice before:
invoice update as:
> 17477 - Correct overwriting at footer of Online Banking Payment Invoice

- pay-api/src/pay_api/resources/v1/account_statements.py
- pay-api/src/pay_api/services/statement.py
- pay-api/tests/unit/api/test_statement.py
*Issue #:*
https://github.com/bcgov/entity/issues/17829
Return invoices that are included in summaries, for the pending balance.
> 17829 - Implement summary route for statements.

- jobs/payment-jobs/tests/docker/docker-compose.yml
- pay-api/src/pay_api/models/invoice.py
- pay-api/src/pay_api/utils/converter.py
"Would it be possible to set the appropriate date fields for the following transactions on your side so I can test our reconciliation is getting them correctly?
713332
713330
712969 refund
Paid Date, Refund Date, or Disbursement Date
"
> Add in fields back to the response for CSO.

- pay-api/src/pay_api/models/statement.py
- pay-api/src/pay_api/services/statement.py
- pay-api/tests/unit/services/test_statement.py
> 17829 - Add in new is_overdue flag

- jobs/ftp-poller/config.py
- jobs/ftp-poller/invoke_jobs.py
- jobs/ftp-poller/run_eft_ftp_poller.sh
- jobs/ftp-poller/tasks/eft_poller_ftp.py
- jobs/ftp-poller/utils/constants.py
*Issue #:*
https://github.com/bcgov/entity/issues/17827
- initial SFT poller set up for EFT File retrieval
> 17827 - initial TDI17 file retrieval setup

- pay-api/src/pay_api/services/payment.py
*Issue #:*
https://github.com/bcgov/entity/issues/17836
Invoice Reference Number is added to the PAY-API transactions csv export.
> 17836 - PAY-API Added Invoice Reference Number to the csv export

- report-api/report-templates/payment_receipt.html
*Issue #:*
https://github.com/bcgov/entity/issues/17382
> 17382 - Update the Wording based on PAD Receipts

- pay-api/src/pay_api/models/invoice.py
- pay-api/src/pay_api/services/statement.py
- pay-api/tests/unit/models/test_invoice.py
*Issue #:*
https://github.com/bcgov/entity/issues/17224
https://github.com/bcgov/entity/issues/17829
- set default overdue date when creating an invoice
- update account summary logic invoice statuses to filter on and allow filtering on a particular statement
> 17224/17829 - EFT over due status handling updates

- pay-api/migrations/versions/2023_10_26_2ef58b39cafc_add_eft_enable_to_payment_accounts.py
Issue with CD
75File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
76cursor.execute(statement, parameters)
77sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) column "eft_enable" of relation "payment_accounts" contains null values
78
79[SQL: ALTER TABLE payment_accounts ADD COLUMN eft_enable BOOLEAN NOT NULL]
> Remove default=False, put in server_default='f'

- pay-api/src/pay_api/services/payment_account.py
- pay-api/src/pay_api/utils/enums.py
*Issue #:*
https://github.com/bcgov/entity/issues/18395
> 18395 - Implement EFT available notification

- jobs/payment-jobs/tasks/ap_task.py
> Fix batch limit for AP refunds.

- pay-api/src/pay_api/services/base_payment_system.py
- pay-api/src/pay_api/services/bcol_service.py
- pay-api/src/pay_api/services/direct_pay_service.py
- pay-api/src/pay_api/services/ejv_pay_service.py
- pay-api/src/pay_api/services/internal_pay_service.py
- pay-api/src/pay_api/services/online_banking_service.py
- pay-api/src/pay_api/services/pad_service.py
- pay-api/src/pay_api/services/paybc_service.py
- pay-api/src/pay_api/services/refund.py
- pay-api/tests/unit/services/test_direct_pay_service.py
- pay-api/tests/unit/services/test_payment_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/18510
Should fix: https://github.com/bcgov/entity/issues/17772
> 18510 - Add extra step to set transactions to REFUNDED if billable = 'f'

- queue_services/payment-reconciliations/requirements.txt
- queue_services/payment-reconciliations/src/reconciliations/config.py
- queue_services/payment-reconciliations/src/reconciliations/eft/eft_errors.py
- queue_services/payment-reconciliations/src/reconciliations/eft/eft_reconciliation.py
- queue_services/payment-reconciliations/src/reconciliations/eft/eft_record.py
- queue_services/payment-reconciliations/src/reconciliations/enums.py
- queue_services/payment-reconciliations/src/reconciliations/version.py
- queue_services/payment-reconciliations/src/reconciliations/worker.py
- queue_services/payment-reconciliations/tests/integration/factory.py
- queue_services/payment-reconciliations/tests/integration/test_eft_reconciliation.py
- queue_services/payment-reconciliations/tests/integration/utils.py
- queue_services/payment-reconciliations/tests/unit/test_eft_file_parser.py
*Issue #:*
https://github.com/bcgov/entity/issues/18468
- Add eft payment reconciliation for TDI17
- Add eft credit record creation for TDI17 over payment
> EFT Reconciliation

- pay-api/src/pay_api/models/base_model.py
- pay-api/src/pay_api/resources/v1/account.py
- pay-api/src/pay_api/services/payment_account.py
- pay-api/tests/unit/api/test_account.py
- pay-api/tests/unit/api/test_cors_preflight.py
*Issue #:*
https://github.com/bcgov/entity/issues/10680
Changes to allow account fees to be removed all at once.
https://github.com/bcgov/sbc-auth/pull/2636 depends on this
> 10680 - Changes to allow account fees to be removed all at once.

- jobs/payment-jobs/tasks/common/dataclasses.py
- jobs/payment-jobs/tasks/direct_pay_automated_refund_task.py
- jobs/payment-jobs/tests/jobs/test_direct_pay_automated_refund_task.py
> Fix paybc changes.

- jobs/payment-jobs/tasks/statement_due_task.py
- jobs/payment-jobs/tests/jobs/test_statement_due_task.py
- jobs/payment-jobs/utils/mailer.py
- pay-api/src/pay_api/services/eft_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/18574
- fixed statement notification queue event typo in parameter (caused account mailer parsing errors)
- added dataclass for statement notification event
- refactor reminder logic to be fully driven by overdue rather than static dates within a month (more accurate and easier for testing/verification)
- Fix bad queries for EFT payment reminders (joins, timezone issues)
- Fix to release payments on pay-api when creating an invoice for EFT payment method
> 18574 - EFT Verification Fixes

- jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
- jobs/payment-jobs/tasks/ejv_payment_task.py
- pay-api/migrations/versions/2023_11_30_49eaec3210e0_.py
- pay-api/src/pay_api/models/ejv_invoice_link.py
*Issue #:*
https://github.com/bcgov/entity/issues/18767
Add in new sequence column via model, migration and job.
> 18767 - Add in new sequence column via model, migration and job.

- pay-api/src/pay_api/services/payment_account.py
- pay-api/src/pay_api/version.py
- pay-api/tests/unit/services/test_payment_account.py
*Issue #:*
https://github.com/bcgov/entity/issues/18762 
- update default statement settings for EFT payment method for account creation
- update payment method change logic to check for EFT and ensure the correct statement frequency
> 18762 - EFT automatically set statement frequency to monthly

- pay-api/migrations/versions/2024_01_23_0b1f9c35b1fb_.py
- pay-api/src/pay_api/models/non_sufficient_funds.py
- pay-api/src/pay_api/services/non_sufficient_funds.py
- pay-api/tests/unit/api/test_non_sufficient_funds.py
- pay-api/tests/unit/services/test_non_sufficient_funds.py
- queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
Adding cfs_account_id field to non_sufficient_funds, and adding the CSV reconciliation description to non_sufficient_funds
*Issue #:*
> 17534 - nsf tweaks

- pay-api/src/pay_api/models/eft_short_names.py
- pay-api/src/pay_api/services/eft_short_names.py
- pay-api/src/pay_api/utils/util.py
- pay-api/src/pay_api/version.py
- pay-api/tests/unit/api/test_eft_short_names.py
*Issue #:*
https://github.com/bcgov/entity/issues/19331
- add account name and branch to support Linked short name search
> 19331-EFT-Shortname-search

- pay-api/src/pay_api/models/eft_short_names.py
- pay-api/src/pay_api/resources/v1/eft_short_names.py
- pay-api/src/pay_api/services/eft_short_names.py
- pay-api/src/pay_api/utils/util.py
- pay-api/tests/unit/api/test_eft_short_names.py
- pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/19331
- account_id search
- account_name search
- account_branch search
- updated queries and filters to make use of new payment_account.branch_name
- added filter for a list of account ids for upcoming linking modal
> 19331 - EFT Shortname search

- pay-api/src/pay_api/models/custom_query.py
- pay-api/src/pay_api/models/eft_short_names.py
- pay-api/src/pay_api/resources/v1/eft_short_names.py
- pay-api/src/pay_api/services/eft_short_names.py
- pay-api/src/pay_api/version.py
- pay-api/tests/unit/api/test_eft_short_names.py
*Issue #:*
https://github.com/bcgov/entity/issues/19330
https://github.com/bcgov/entity/issues/19333
- update mapper for shortname mapper
- update short name search date filters to date ranges
- update fetching single short name to include account and transaction details (use search with id)
> 19330-19333-EFT-shortname-search-updates

- pay-api/src/pay_api/models/custom_query.py
*Issue #:*
https://github.com/bcgov/entity/issues/19330
- fix date range filter to and and_ clause
> 19330 eft shortname date range fix

- pay-api/src/pay_api/models/routing_slip.py
*Issue #:*
https://github.com/bcgov/entity/issues/19755
> PAY-API - Update Get Routing Slip to include refund_amount

- docs/docs/PayBC Mocking/paybc-1.0.0.yaml
- pay-api/setup.cfg
- pay-api/src/pay_api/models/__init__.py
- pay-api/src/pay_api/models/refunds_partial.py
- pay-api/src/pay_api/services/base_payment_system.py
- pay-api/src/pay_api/services/bcol_service.py
- pay-api/src/pay_api/services/direct_pay_service.py
- pay-api/src/pay_api/services/ejv_pay_service.py
- pay-api/src/pay_api/services/internal_pay_service.py
- pay-api/src/pay_api/services/online_banking_service.py
- pay-api/src/pay_api/services/pad_service.py
- pay-api/src/pay_api/services/paybc_service.py
- pay-api/src/pay_api/services/refund.py
- pay-api/src/pay_api/utils/converter.py
- pay-api/src/pay_api/utils/enums.py
- pay-api/tests/docker/docker-compose.yml
- pay-api/tests/unit/services/test_direct_pay_service.py
- pay-api/tests/unit/services/test_payment_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/19759
> 19759 - Partial refunds PAYBC implementation

- queue_services/payment-reconciliations/src/reconciliations/enums.py
> Fix the description field, it's incorrect

- pay-api/src/pay_api/services/direct_pay_service.py
- pay-api/src/pay_api/utils/enums.py
- pay-api/tests/unit/api/test_partial_refund.py
- pay-api/tests/unit/services/test_direct_pay_service.py
Added BASE_FEES, FUTURE_EFFECTIVE_FEES, and PRIORITY_FEES Removed OTHER_FEES
*Issue #:*
https://github.com/bcgov/entity/issues/19912
> 19912- Updating partial refunds type enums

- .github/workflows/pay-api-cd-gcp.yml
> Add pay api gcp CD flow. (#1446)

- pay-api/src/pay_api/services/eft_service.py
- pay-api/src/pay_api/services/payment_account.py
- pay-api/tests/unit/api/test_account.py
- pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/19936
> 19936 - EFT - PAY-API changes to handle CFS when switching payment methods

- .github/workflows/bcol-api-ci.yml
- .github/workflows/events-listener-ci.yml
- .github/workflows/ftp-poller-ci.yml
- .github/workflows/notebook-report-ci.yml
- .github/workflows/pay-admin-ci.yml
- .github/workflows/pay-api-ci.yml
- .github/workflows/payment-jobs-ci.yml
- .github/workflows/payment-reconciliations-ci.yml
- .github/workflows/report-api-ci.yml
> don't fail CI if codecov fails.

- pay-api/src/pay_api/models/eft_short_names.py
- pay-api/src/pay_api/services/eft_short_names.py
*Issue #:*
https://github.com/bcgov/entity/issues/20421
> 20421 - Add cfs account status to search eft names

- pay-api/src/pay_api/services/__init__.py
- pay-api/tests/unit/services/test_statement.py
- pay-queue/poetry.lock
- pay-queue/src/pay_queue/services/eft/eft_reconciliation.py
- pay-queue/src/pay_queue/services/payment_reconciliations.py
*Issue #:*
https://github.com/bcgov/entity/issues/20088
Unlocking overdue BCROS account when paid with exact amount
> 20088 - Unlock associated accounts when paid with exact amount

- jobs/notebook-report/monthly/cso_reconciliation_summary.ipynb
*Issue #:*
https://github.com/bcgov/entity/issues/20069
> 20069 - All Partners Monthly reports with details of transactions

- jobs/payment-jobs/invoke_jobs.py
- jobs/payment-jobs/tasks/statement_task.py
- jobs/payment-jobs/tests/jobs/test_generate_statements.py
- pay-api/src/pay_api/services/payment_account.py
- pay-api/src/pay_api/version.py
- pay-api/tests/unit/services/test_statement.py
*Issue #:*
https://github.com/bcgov/entity/issues/20719
- fixes incorrect date ranges generated for interim statement settings
- Add ability to generate statements filtered by account. This allows us to generate a monthly statement early on a specific account without affecting other accounts
> 20719- Interim Statements Settings Fix

- pay-api/src/pay_api/models/routing_slip.py
Fixes:
sqlalchemy.exc.ProgrammingError: (pg8000.dbapi.ProgrammingError) {'S': 'ERROR', 'V': 'ERROR', 'C': '42883', 'M': 'operator does not exist: numeric = character varying', 'H': 'No operator matches the given name and argument types. You might need to add explicit type casts.', 'P': '1404', 'F': 'parse_oper.c', 'L': '647', 'R': 'op_error'}
> Cast to numeric

- pay-api/migrations/versions/2024_07_16_f98666d9809a_.py
- pay-api/src/pay_api/models/invoice.py
This brought down the time from 9s -> 74ms
> Add in composite index for invoice_status_code and payment_account_id

- pay-api/migrations/alembic.ini
- pay-api/migrations/env.py
*Issue #:*
https://github.com/bcgov/entity/issues/22480
Add in handling that skips the verison tables for now
> 22480 - Skip version tables in migrations

- .github/workflows/ftp-poller-ci.yml
- .github/workflows/pay-api-ci.yml
- .github/workflows/pay-queue-ci.yml
- .github/workflows/payment-jobs-ci.yml
- jobs/payment-jobs/poetry.lock
- jobs/payment-jobs/pyproject.toml
- jobs/payment-jobs/tasks/statement_due_task.py
- jobs/payment-jobs/tests/jobs/test_statement_due_task.py
- pay-admin/poetry.lock
- pay-admin/pyproject.toml
- pay-api/src/pay_api/models/invoice.py
- pay-api/src/pay_api/utils/util.py
- pay-api/tests/unit/models/test_invoice.py
*Issue #:*
https://github.com/bcgov/entity/issues/22625
EFT Invoice created on January 1st -> Statement Day Feburary 1st -> Client asked to pay by Feburary 28th -> overdue date March 15th
EFT Invoice created on January 31st -> Statement Day Feburary 1st -> Client asked to pay by Feburary 28th -> overdue date March 15th
After the statement has been issued:
7 day reminder = Feb 21 ( due date - 7)
final reminder = Feb 28 (due date)
overdue/account lock email = March 15 - SBC finance etc. CC'd / Kaine CC'd
> 22625 - Move to 1 month + 15 days instead of 1 month for overdue

- jobs/payment-jobs/tasks/cfs_create_account_task.py
- jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
- jobs/payment-jobs/tasks/unpaid_invoice_notify_task.py
- jobs/payment-jobs/tests/jobs/factory.py
- jobs/payment-jobs/tests/jobs/test_activate_pad_account_task.py
- jobs/payment-jobs/tests/jobs/test_ejv_partner_distribution_task.py
- jobs/payment-jobs/tests/jobs/test_ejv_partner_partial_refund_distribution_task.py
- jobs/payment-jobs/tests/jobs/test_unpaid_invoice_notifytask.py
- pay-api/migrations/versions/6f0fe9f23d8c_distribution_code_changes.py
- pay-api/src/pay_api/resources/v1/fee.py
- pay-api/src/pay_api/services/statement.py
- pay-api/src/pay_api/services/statement_settings.py
- pay-api/tests/unit/api/test_statement_settings.py
- pay-api/tests/unit/factory/test_payment_system_factory.py
- pay-api/tests/unit/services/test_payment_account.py
- pay-api/tests/unit/services/test_statement.py
- pay-api/tests/unit/services/test_statement_settings.py
- pay-api/tests/utilities/base_test.py
- pay-queue/tests/integration/factory.py
> Use datetime.now(tz=timezone.utc) instead of datetime.today

- pay-api/src/pay_api/models/invoice.py
- pay-api/tests/unit/services/test_invoice.py
- pay-api/tests/unit/services/test_payment_service.py
> Add in section for EFT CREATED -> to be returned as COMPLETED

- pay-api/src/pay_api/services/eft_short_names.py
- pay-api/src/pay_api/version.py
- pay-api/tests/unit/api/test_eft_payment_actions.py
*Issue #:*
https://github.com/bcgov/entity/issues/21528
- update EFT payment reversal action to populate missing amount and receipt information from COMPLETED link
> 21528 - EFT Reverse Payment Fix

- pay-queue/src/pay_queue/services/payment_reconciliations.py
> Fix the credit syncing so it falls back to ONLINE_BANKING

- jobs/payment-jobs/invoke_jobs.py
- jobs/payment-jobs/tasks/eft_task.py
- jobs/payment-jobs/tasks/statement_task.py
- jobs/payment-jobs/tests/jobs/test_eft_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/22770
> 22770 - Refactor EFT job so it works with multiple EFT credit invoice links

- pay-api/src/pay_api/resources/v1/eft_short_names.py
- pay-api/src/pay_api/services/eft_short_names.py
- pay-api/src/pay_api/services/payment_account.py
- pay-api/src/pay_api/version.py
- pay-api/tests/conftest.py
- pay-api/tests/unit/api/test_account.py
- pay-api/tests/unit/api/test_eft_short_names.py
*Issue #:*
https://github.com/bcgov/entity/issues/20415
- update search eft accounts to check against CFS accounts, we should no longer need to call auth so this was removed
- added accountIdList query parameter back to short name search to allow for searches that are partial matches to properly surface status and amount owing information
- update tests
> 20415 - Fix / Update to linking modal backend calls

- pay-api/src/pay_api/services/statement.py
- pay-api/tests/unit/api/test_account.py
- pay-api/tests/unit/api/test_statement.py
*Issue #:*
https://github.com/bcgov/entity/issues/22672
> 22672 - Fix missing Approved invoices on get_invoices_owing_amount

- pay-api/migrations/versions/2024_08_14_4410b7fc6437_eft_invoice_refund_historical.py
- pay-api/src/pay_api/models/eft_short_names_historical.py
- pay-api/src/pay_api/services/eft_short_name_historical.py
- pay-api/src/pay_api/services/eft_short_names.py
- pay-api/src/pay_api/utils/enums.py
- pay-api/src/pay_api/version.py
- pay-api/tests/unit/api/test_eft_short_name_history.py
*Issue #:*
https://github.com/bcgov/entity/issues/21597
- supporting eft shortname history updates in preparation for invoice refund
- fix for checking latest link states
> 21597-EFT History Invoice Refund

- pay-api/src/pay_api/services/eft_short_names.py
- pay-api/tests/unit/api/test_statement.py
*Issue #:*
https://github.com/bcgov/entity/issues/20415
https://github.com/bcgov/entity/issues/21981
- Payment Method filter on statement owing summary (this query specifically for short name usage, so it should be filtering by EFT code)
- Fix links subquery so it pulls the latest record for an account, and considers the most recent link (could have been unlinked from a different account)
> 20415 - fix EFT linking search counts / pagination

- jobs/payment-jobs/poetry.lock
- jobs/payment-jobs/pyproject.toml
- jobs/payment-jobs/tasks/eft_task.py
- jobs/payment-jobs/tests/jobs/test_eft_task.py
- pay-api/poetry.lock
- pay-api/src/pay_api/services/cfs_service.py
- pay-api/tests/unit/services/test_cfs_service.py
> Refund fixes

- jobs/payment-jobs/invoke_jobs.py
- jobs/payment-jobs/tasks/cfs_create_invoice_task.py
- jobs/payment-jobs/tasks/statement_due_task.py
- jobs/payment-jobs/tests/jobs/test_statement_due_task.py
Usage: 
 `python3 invoke_jobs.py STATEMENTS_DUE 2024-08-31 2447`
> Add in extra params so statement due task can be called with auth_account_id param

- jobs/payment-jobs/poetry.lock
- jobs/payment-jobs/pyproject.toml
- jobs/payment-jobs/tasks/statement_due_task.py
- jobs/payment-jobs/tests/jobs/test_statement_due_task.py
- jobs/payment-jobs/utils/mailer.py
- pay-api/src/pay_api/models/eft_short_name_links.py
- pay-api/src/pay_api/services/statement.py
- pay-api/tests/unit/api/test_statement.py
- pay-api/tests/unit/services/test_statement.py
*Issue #:*
https://github.com/bcgov/entity/issues/21560
https://github.com/bcgov/entity/issues/22391
- statement_due_task - add link count for statement templates to determine template content
- eft statement summary - add link count to show caution text for multi linked accounts with an amount owing
> 22391, 21560 - Statement Owing Caution, Reminder notifications

- pay-api/src/pay_api/services/statement.py
- pay-api/src/pay_api/utils/enums.py
- pay-api/tests/unit/services/test_statement.py
*Issue #:*
https://github.com/bcgov/entity/issues/22895
> 22895 - Refactor statements template into one file

- jobs/payment-jobs/pyproject.toml
- pay-api/src/pay_api/models/eft_credit.py
- pay-api/src/pay_api/models/eft_short_name_links.py
- pay-api/src/pay_api/resources/v1/account_statements.py
- pay-api/src/pay_api/services/eft_service.py
- pay-api/src/pay_api/services/eft_short_names.py
- pay-api/src/pay_api/services/statement.py
- pay-api/tests/unit/api/test_eft_payment_actions.py
- pay-api/tests/unit/api/test_statement.py
- pay-api/tests/unit/services/test_eft_service.py
- pay-queue/poetry.lock
- pay-queue/pyproject.toml
- pay-queue/src/pay_queue/services/eft/eft_reconciliation.py
- pay-queue/tests/integration/test_eft_reconciliation.py
*Issue #:*
https://github.com/bcgov/entity/issues/22391
- Add statement summary multi account under payment logic
- short name service refactor for eft credit balance to avoid cyclic issue
> 22391 - EFT Multi Account under payment

- pay-api/migrations/versions/2024_09_13_1fadb0e78d8c_21570_short_name_supplier_info.py
- pay-api/src/pay_api/models/eft_short_names.py
- pay-api/src/pay_api/resources/v1/eft_short_names.py
- pay-api/src/pay_api/schemas/schemas/eft_short_name.json
- pay-api/src/pay_api/services/eft_short_names.py
- pay-api/src/pay_api/version.py
- pay-api/tests/unit/api/test_cors_preflight.py
- pay-api/tests/unit/api/test_eft_short_names.py
- pay-api/tests/unit/models/test_eft_short_names.py
*Issue #:*
https://github.com/bcgov/entity/issues/21570
- add short name columns for preferred email / cas supplier number
- add patch route to populate email / cas supplier number
> 21570 - Email / CAS Supplier Number

- pay-api/src/pay_api/utils/enums.py
- pay-api/src/pay_api/utils/util.py
> Add in business search for credit card

- pay-api/src/pay_api/models/statement.py
> Statement - from_date / to_date - Fix UTC, add 8 hours so GUI shows it in PDT/PST

- pay-api/migrations/versions/2024_09_18_67407611eec8_21539_shortname_refund_history.py
- pay-api/migrations/versions/2024_09_19_29f59e6f147b_EFT_Refunds.py
- pay-api/src/pay_api/models/eft_refund.py
- pay-api/src/pay_api/models/eft_short_names_historical.py
- pay-api/src/pay_api/services/eft_service.py
- pay-api/src/pay_api/services/eft_short_name_historical.py
- pay-api/src/pay_api/utils/enums.py
- pay-api/src/pay_api/version.py
- pay-api/tests/unit/api/test_eft_short_names.py
- pay-api/tests/unit/models/test_eft_refund.py
- pay-api/tests/unit/services/test_eft_short_name_historical.py
- pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/21539
- Updates to support short name refund history
> 21539 - Short name refund history support

- pay-api/src/pay_api/models/eft_short_names_historical.py
- pay-api/src/pay_api/services/eft_short_name_historical.py
- pay-api/tests/unit/api/test_eft_short_name_history.py
*Issue #:*
https://github.com/bcgov/entity/issues/21539
- add eft_refund_id to short name history response
> 21539 - Short name history eft refund fix

- DEVELOPER_NOTES.md
- jobs/payment-jobs/invoke_jobs.py
- jobs/payment-jobs/tasks/statement_due_task.py
- jobs/payment-jobs/tests/jobs/test_statement_due_task.py
- jobs/payment-jobs/utils/mailer.py
*Issue #:*
https://github.com/bcgov/entity/issues/20787
- statement due task overrides to allow isolated execution of notifications and overdue status updates
> 20787 - allow specific action overrides

- jobs/payment-jobs/invoke_jobs.py
- jobs/payment-jobs/run_eft_overpayment_notification_task.sh
- jobs/payment-jobs/services/email_service.py
- jobs/payment-jobs/tasks/eft_overpayment_notification_task.py
- jobs/payment-jobs/tasks/eft_statement_due_task.py
- jobs/payment-jobs/templates/eft_overpayment.html
- jobs/payment-jobs/tests/jobs/conftest.py
- jobs/payment-jobs/tests/jobs/test_eft_overpayment_notification_task.py
- jobs/payment-jobs/tests/jobs/test_eft_statement_due_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/21516
- rename statement_due_task to eft_statement_due_task for clarity
- eft_overpayment_notification_task job for unlinked accounts with credits remaining for 30 days and linked over payments
> 21516 - EFT Over payment notification task

- pay-api/src/pay_api/resources/v1/fas/routing_slip.py
- pay-api/src/pay_api/utils/enums.py
Fixes [https://github.com/bcgov/sbc-pay/security/code-scanning/5](https://github.com/bcgov/sbc-pay/security/code-scanning/5)
To fix the problem, we need to ensure that the `date` parameter is properly sanitized before it is used to generate the `pdf` content. This can be done by validating the `date` parameter to ensure it conforms to an expected format (e.g., YYYY-MM-DD) before passing it to the `RoutingSlipService.create_daily_reports` method.
1. Import the `re` module for regular expression matching.
2. Add a validation step for the `date` parameter to ensure it matches the expected date format.
3. If the `date` parameter is invalid, return an appropriate error response.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Fix code scanning alert no. 5: Reflected server-side cross-site scripting

- jobs/payment-jobs/poetry.lock
- jobs/payment-jobs/pyproject.toml
- jobs/payment-jobs/tasks/eft_overpayment_notification_task.py
- jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
- jobs/payment-jobs/tests/jobs/test_ejv_partner_distribution_task.py
- pay-api/migrations/versions/2024_10_01_56c4542db0d7_.py
- pay-api/migrations/versions/2024_10_10_ed487561aeeb_.py
- pay-api/pyproject.toml
- pay-api/src/pay_api/models/partner_disbursements.py
- pay-api/src/pay_api/services/__init__.py
- pay-api/src/pay_api/services/eft_refund.py
- pay-api/src/pay_api/services/eft_service.py
- pay-api/src/pay_api/services/partner_disbursements.py
- pay-api/src/pay_api/utils/enums.py
- pay-api/tests/unit/api/test_eft_payment_actions.py
- pay-api/tests/unit/services/test_eft_service.py
- pay-api/tests/unit/services/test_partner_disbursements.py
- pay-api/tests/utilities/base_test.py
- pay-queue/poetry.lock
- pay-queue/pyproject.toml
- pay-queue/tests/integration/test_cgi_reconciliations.py
> Small fixes and tweaks for partner reversals

- pay-api/src/pay_api/services/eft_service.py
So multiple rows can populate and we don't get partial disbursements
> Remove distinct

- pay-api/src/pay_api/models/eft_refund.py
- pay-api/src/pay_api/services/auth.py
- pay-api/src/pay_api/services/eft_refund.py
- pay-api/src/pay_api/services/email_service.py
> Tweaks for send_email

- bcol-api/poetry.lock
- jobs/ftp-poller/poetry.lock
- pay-api/poetry.lock
- pay-api/tests/unit/api/fas/test_routing_slip.py
https://github.com/bcgov/sbc-common-components/pull/375
> Fix references to sbc-common-components to use new camelCase serialization

- pay-api/src/pay_api/factory/payment_system_factory.py
- pay-api/src/pay_api/utils/enums.py
*Issue #:*
https://github.com/bcgov/entity/issues/24133
> 24133 - Add in new tip_internal_payment_override role

- jobs/payment-jobs/invoke_jobs.py
> Fix argument

- jobs/payment-jobs/config.py
- jobs/payment-jobs/tasks/direct_pay_automated_refund_task.py
- jobs/payment-jobs/tasks/distribution_task.py
- jobs/payment-jobs/tests/jobs/mocks.py
- pay-api/src/pay_api/config.py
- pay-api/src/pay_api/models/credit.py
- pay-api/src/pay_api/resources/v1/account.py
- pay-api/src/pay_api/services/cfs_service.py
- pay-api/src/pay_api/services/direct_pay_service.py
- pay-api/src/pay_api/services/paybc_service.py
- pay-api/tests/unit/api/test_partial_refund.py
*Issue #:*
https://github.com/bcgov/entity/issues/20767
> 20767 - Put in additional_headers for reverse proxy

- pay-api/migrations/versions/2024_11_08_0f02d5964a63_24336.py
*Issue #:*
https://github.com/bcgov/entity/issues/24336
- migration to add missing column to short name histort
> 24336 - fix missing short name history column

- jobs/payment-jobs/tasks/ap_task.py
- jobs/payment-jobs/tests/jobs/test_ap_task.py
> Check disbursement status for none

- pay-api/src/pay_api/models/payment.py
> Revert db.session.query

- pay-api/src/pay_api/models/payment.py
- pay-api/src/pay_api/utils/sqlalchemy.py
> More performance enhancements

- pay-api/devops/vaults.gcp.env
- pay-api/src/pay_api/__init__.py
- pay-api/src/pay_api/config.py
*Issue #:*
https://github.com/bcgov/entity/issues/24653
> 24653 - Add in changes for ENABLE_403_LOGGING

- pay-api/src/pay_api/resources/v1/account.py
- pay-api/src/pay_api/resources/v1/account_statements.py
- pay-api/src/pay_api/resources/v1/account_statements_notifications.py
- pay-api/src/pay_api/resources/v1/account_statements_settings.py
- pay-api/src/pay_api/utils/enums.py
- pay-api/src/pay_api/version.py
*Issue #:*
https://github.com/bcgov/entity/issues/24652
- updates to support new keycloak group contact_centre_staff
> 24652 - updates for KC group contact_centre_staff

- pay-api/src/pay_api/resources/v1/account.py
- pay-api/src/pay_api/resources/v1/account_statements.py
- pay-api/src/pay_api/services/payment_service.py
- pay-api/src/pay_api/utils/enums.py
- pay-api/src/pay_api/utils/user_context.py
> Override Sandbox DIRECT_PAY / ONLINE_BANKING to PAD payment method

- pay-api/src/pay_api/services/direct_pay_service.py
- pay-api/tests/unit/services/test_direct_pay_service.py
*Issue #:*
https://github.com/bcgov/entity/issues/25372
> 25372 - Support $1.50/$1.00 service fees with $0 base fee in DIRECT_PAY

- jobs/payment-jobs/tasks/eft_statement_due_task.py
- jobs/payment-jobs/tests/jobs/test_eft_statement_due_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/25596
- Update so locking mechanism doesn't just look at the most recent statement (cover the case where we manually defer the overdue date in the db)
- Updated to handle multiple overdue statements
- Updated to properly evaluate new overdue invoices even on a currently locked account and properly add NSF invoice records and update statement.has_overdue_invoices date
- Expanded logic to prevent locking an account multiple times in the same job run or subsequent job runs when an account is already locked
> 25596 - EFT Locking Fixes

- pay-api/src/pay_api/services/code.py
> Fix null return for payment Methods

- jobs/payment-jobs/config.py
- pay-queue/src/pay_queue/config.py
- pay-queue/src/pay_queue/services/payment_reconciliations.py
> Fix secret for topics

- pay-api/migrations/versions/2025_03_17_f6e2fd9710b7_26465_eft_refund_data_fix.py
- pay-api/src/pay_api/models/eft_short_names_historical.py
- pay-api/src/pay_api/services/eft_short_name_historical.py
- pay-api/tests/unit/api/test_eft_short_name_history.py
- pay-api/tests/utilities/base_test.py
*Issue #:*
https://github.com/bcgov/entity/issues/26465
- add refund method and cheque status for eft short name history
- data fix for existing refunds
> 26465 - EFT Shortname history update / migration data fix

- jobs/payment-jobs/tasks/cfs_create_invoice_task.py
- jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/15674
> 15674 - Add invoice_number as params to PAD confirmation email

- jobs/payment-jobs/poetry.lock
- jobs/payment-jobs/pyproject.toml
- jobs/payment-jobs/tasks/ap_task.py
- jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
- jobs/payment-jobs/tests/jobs/test_ap_task.py
- jobs/payment-jobs/tests/jobs/test_ejv_partner_distribution_task.py
- jobs/payment-jobs/utils/enums.py
- pay-api/src/pay_api/services/email_service.py
- pay-api/templates/job_failed_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/28580
Add alert for failing Routing slip refunds job;
Refactor job notification email handling to pay-api; (currently used by ap_task, ejv_distribution_task)
> 28580 - Alert for failing Routing slip refunds job

- pay-api/migrations/versions/2025_05_28_b927265cf3a1_eft_refund_decision_by.py
- pay-api/src/pay_api/models/eft_refund.py
- pay-api/src/pay_api/services/eft_refund.py
- pay-api/tests/unit/api/test_eft_short_names.py
- pay-api/tests/unit/models/test_eft_refund.py
*Issue #:*
https://github.com/bcgov/entity/issues/19544
- Change EFT Refund approve / decline to use decision_by
> 28627 - EFT Refund use decision_by instead of updated_by

- pay-api/src/pay_api/models/eft_short_names_historical.py
- pay-api/src/pay_api/services/eft_short_name_historical.py
- pay-api/src/pay_api/version.py
- pay-api/tests/unit/api/test_eft_short_name_history.py
*Issue #:*
https://github.com/bcgov/entity/issues/28898
- updates so UI can separate system date vs transaction date (could be a date from external source - e.g TDI17)
- fix default sorting to be driven off system create date for proper ordering when transaction_date may be backdated since it has an external source (e.g. TDI17 is processed today, but the deposit day is from 2-3 days ago)
> 28898 - EFT History updates

- pay-api/src/pay_api/services/payment_service.py
Routing slips were showing up as DIRECT_PAY, not INTERNAL for example. Check needed to move
> Payment Blocking Fix

- pay-api/migrations/versions/2024_04_12_29867cf1bd9e_19496_eft_short_names_updates.py
- pay-api/tests/unit/models/test_history_table_columns.py
Small unit tests that check the integrity of migrations ensure that the history table lines up with the regular tables
> History table unit test checking

- pay-api/devops/gcp/clouddeploy.yaml
- pay-api/src/pay_api/services/payment_calculations.py
*Issue #:*
https://github.com/bcgov/entity/issues/27061
GCP is showing "memory limit of 1024 MiB exceeded with 1042 MiB used."
I tested locally with a larger statement and the memory usage was around 800 MB. It seems GCP handles memory control a bit differently, so I'm trying to set the test environment the same as prod to see if the error still occurs.
> 27061 - Increase PAY test env memory
